### ISSUE TITLE
Header and Footer support

### ISSUE THREAD

**Issue by conorbev** [yjwen/org-reveal#103]
As discussed in pull request #101 could you please implement support for adding headers and/or footers to your presentation? My main use case is to be able to display a logo or banner at the top or bottom of the screen.

**Comment by yjwen** [comment]
Code updated. Please see https://github.com/yjwen/org-reveal/#slide-headerfooter for detail.

**Comment by conorbev** [comment]
Thank you. The documentation looks great. Will it make it into the stable branch anytime soon? (I have ox-reveal installed via melpa)

**Comment by yjwen** [comment]
I've just merged master into stable. So once melpa pulls the latest stable branch, you can use the header/footer feature also.
