### ISSUE TITLE
org-export-execute-babel-code: Wrong number of arguments

### ISSUE THREAD

**Issue by f0086** [yjwen/org-reveal#104]
Getting this error when creating the export (C-c C-e R R):

![s1425905373-13936](https://cloud.githubusercontent.com/assets/121972/6555132/53e2ee20-c663-11e4-99b0-593bd0d9e81c.png)

GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.7) of 2015-01-17 on bisson
Org-mode version 8.2.10 (release_8.2.10 @ /home/aaron/.emacs.d/el-get/org-mode/lisp/)
I use the el-get version of org-reveal (https://github.com/dimitri/el-get/blob/af98fb208d788bfe87715b08d16b18f520ada050/recipes/org-reveal.rcp)

**Comment by yjwen** [comment]
Looks like a API mismatch between Org-mode and org-reveal.

Could you please try the org-reveal in MELPA (package name ox-reveal), It is pulling the "stable" branch of org-reveal, which should match the released versions of Org-mode.

Org-reveal's "master" branch is in pair with Org-mode's development version that pulled from its git repository.

Regards,
Yujie

**Comment by f0086** [comment]
I've tried with the MELPA version (ox-reveal). Now I get this error:

        org-export--parse-option-keyword: End of file during parsing

**Comment by yjwen** [comment]
OK. I see.

Can you please paste a minimum org-file that can reproduce the issue? I will need one to some debugging.

**Comment by f0086** [comment]
Are there any required fields/syntax I need to use? I've tried with a blank org-file with some headings in it.

**Comment by yjwen** [comment]
Yes. There are different branch of org-reveal to match the APIs of different Org-mode release.

8.2x Org-mode (Emacs stock, ELPA) <-- org-reveal "stable" branch (MELPA)
8.3x Org-mode (git) <-- org-reveal "master" branch
