### ISSUE TITLE
disable table of contents

### ISSUE THREAD

**Issue by psifertex** [yjwen/org-reveal#105]
Is there a way to disable the table of contents slide?

**Comment by psifertex** [comment]
Nevermind! Missed the toc option before, noticed it later. Sorry about that.

**Comment by yjwen** [comment]
Not a matter. For any other issue, please let me know. :)

2015-03-20 5:34 GMT+08:00 Jordan <notifications@github.com>:

**Comment by edmz** [comment]
How can I disable it? I see the source reads from a plist, but don't know how to access or define that. Thanks!

**Comment by psifertex** [comment]
`#+OPTIONS: toc:nil`

**Comment by hello-code** [comment]
Can not disable `Table of content` !
```
#+TITLE: HELLO
#+REVEAL_ROOT: http://cdn.jsdelivr.net/reveal.js/2.5.0/
#+REVEAL_TRANS: linear
#+OPTIONS:toc:nil
* HELLO 1997
** HELLO 2000
** HELLO 3000
* WORLD 2000
** WORLD 3000
```


**How can I disable it?**
OMG! I found it! There is a **space** in front of the `toc:nil` !
