### ISSUE TITLE
MELPA org + ox-reveal no longer works

### ISSUE THREAD

**Issue by lvh** [yjwen/org-reveal#108]
I'm not entirely sure if this was an update to ox-reveal or org, but it appears to fail even when I uninstall the org package and fall back to the default version.

When compiling an empty document:

```
org-reveal-toc: Wrong type argument: arrayp, nil
```

When compiling a file with notes in it:

```
replace-regexp-in-string: Wrong type argument: stringp, ((quote class) quote notes)
```

Versions installed through MELPA & default GNU repository, ox-reveal:

```
ox-reveal is an installed package.

     Status: Installed in `~/.emacs.d/elpa/ox-reveal-20150325.2313/' (unsigned).
    Archive: n/a
    Version: 20150325.2313
   Requires: org-8.0
    Summary: reveal.js Presentation Back-End for Org Export Engine
   Keywords: outlines hypermedia slideshow presentation 
    Other versions: 20150325.2313 (melpa).
```

```
org is an installed package.

     Status: Installed in `~/.emacs.d/elpa/org-20150330/',
             shadowing a built-in package (unsigned).
    Archive: n/a
    Version: 20150330
    Summary: Outline-based notes management and organizer
    Other versions: 20150330 (gnu), builtin.
```

However it also fails if I uninstall org-mode:

```
Org-mode version 8.2.10 (release_8.2.10 @ /opt/homebrew-cask/Caskroom/emacs/24.4/Emacs.app/Contents/Resources/lisp/org/)
```

**Comment by lvh** [comment]
Checking out 42f58f3 fixed the problem. Bisecting is tricky, because it's bisecting a master merge, so it keeps complaining that I'm running a released version of org.

**Comment by yjwen** [comment]
I tried with ELPA Org and MELPA ox-reveal. The Readme.org can be exported without error.
The versions are:
  * ELPA Org 20150330
  * MELPA ox-reveal 20150402.821

Could you please try the latest packages and check your lock setting/

**Comment by psifertex** [comment]
I've got the same problem with slides I was working on just a few weeks ago, but your readme.org renders fine. Specifically, my error is `replace-regexp-in-string: Wrong type argument: stringp, ((quote class) quote notes)`. It looks like any slides with slide-notes are triggering the bug for me. Also, in an unrelated bug it looks like `toc:0` doesn't work anymore and I had to switch it to `nil`.

**Comment by psifertex** [comment]
Found the bug. I was going to submit a pull request, but the version I'm using in elpa had enough other changes that I couldn't actually test on the latest source with this patch applied. That said, I reverted patch 24bd4e48 and that in addition to the `nil` toc change above got me going again:
```331,332c331,334
<            (org-reveal-tag 'aside '(('class . 'notes))
<                            (org-export-string-as block-string 'html 'body-only)))
---
>            (concat
>             "<aside class=\"notes\">\n"
>             (org-export-string-as block-string 'html 'body-only)
>             "</aside>"))```

**Comment by yjwen** [comment]
Thanks for finding out the bug! It was introduced in master branch and I missed to test the note feature.

Just fixed and pushed to the stable branch.

**Comment by Compro-Prasad** [comment]
Unable to install `ox-reveal` from MELPA.
```
package-compute-transaction: Need package ‘org-20150330’, but only 9.1.13 is available
```
