### ISSUE TITLE
Current version produces broken HTML when adding fragment styles

### ISSUE THREAD

**Issue by lvh** [yjwen/org-reveal#109]
Following slide:

```
** Distributed Systems 101

   "Just enough" distributed systems

   #+ATTR_REVEAL: :frag roll-in
   * to whet your appetite
   * to shoot yourself in the foot
```

List renders to:

```
<ulclass="fragment roll-in"="">
<li>to whet your appetite</li>
<li>to shoot yourself in the foot</li>
</ulclass="fragment>
```

This happens regardless of whether `#+REVEAL_DEFAULT_FRAG_STYLE` is set.

**Comment by lvh** [comment]
I'm not sure how this can happen, since the fragment class appears to be created here: https://github.com/yjwen/org-reveal/blob/master/ox-reveal.el#L317-L322

**Comment by yjwen** [comment]
Fixed. Please pull the latest master branch.

**Comment by lvh** [comment]
Thanks!
