### ISSUE TITLE
Applying fragment behavior to each element of a list

### ISSUE THREAD

**Issue by lvh** [yjwen/org-reveal#110]
Previously, `#+ATTR_REVEAL :frag roll-in` before a list would apply it to each of the elements of the list. Recently, this behavior changed so that it applies to the list as a whole, so you have to specify the frag types separately, e.g.:

```org
    #+ATTR_REVEAL: :frag (roll-in roll-in roll-in roll-in)
    1. Install it
    2. Play with it
    3. Learn something
    4. Repeat
```

Is there a shortcut for the old behavior (e.g. just apply roll-in to everything)? The problem is that if I change the number of elements in the list, but don't change the frag list, the list "breaks".

**Comment by yjwen** [comment]
No shortcut yet. Let me add something like :frag roll-in*

2015-04-07 23:52 GMT+08:00 lvh (Laurens Van Houtven) <
notifications@github.com>:

**Comment by psifertex** [comment]
I'd like this very much -- much more annoying to have to manually specify the style for each item. 

Also related: `appear` is missing in the list of sample fragment types in the readme.

**Comment by yjwen** [comment]
Just committed to the master branch.
Now insufficient frag style list will be automatically extended by its last element. So `:frag (appear)` assigns each item of a list the `appear` fragment style. And `:frag (appear none)` assigns `appear` to the first item, and no fragment style for the rest.

**Comment by lvh** [comment]
Awesome, thanks!
