### ISSUE TITLE
fragmented images need two clicks

### ISSUE THREAD

**Issue by psifertex** [yjwen/org-reveal#111]
Sample:

```
#+Title: test slides

** slide title
#+ATTR_REVEAL: :frag appear
https://farm8.staticflickr.com/7342/11900448743_f2589a052b_o.png
```

The image requires two clicks to appear, whereas:

```
#+Title: test slides

** slide title
#+ATTR_REVEAL: :frag appear
any normal text
```

Will properly appear after one click.

Possibly related to #70?

**Comment by yjwen** [comment]
Just looked into the code, I think it is a bug in org-reveal in dealing with paragraph's fragment. Let me work out a fix.

**Comment by yjwen** [comment]
Fixed in stable branch. Please wait for MELPA's update.
