### ISSUE TITLE
support for reveal.js-title-footer

### ISSUE THREAD

**Issue by trenkert** [yjwen/org-reveal#112]
could you include support for reveal.js-title-footer?

cf.: https://github.com/e-gor/Reveal.js-Title-Footer

Thanks!

**Comment by yjwen** [comment]
Hi,

  Sorry for such a later reply.

  You can use `#+REVEAL_EXTRA_CSS` and `#+REVEAL_EXTRA_JS` to include reveal.js-title-footer. For example:
```
#+REVEAL_EXTRA_CSS: file:///path/to/plugin/title-footer/title-footer.css
#+REVEAL_EXTRA_JS: { src: 'file:///path/toplugin/title-footer/title-footer.js', async: true, callback: function() { title_footer.initialize(); } }
```

Regards,
Yujie
