### ISSUE TITLE
fragments dont appear

### ISSUE THREAD

**Issue by trenkert** [yjwen/org-reveal#113]
I am using org-reveal version 20150408.831, orgmode 8.2.10  and reveal.js 3.0.0. 

The exported html file does not contain a class "fragment" or a section id "fragments" at all and - subsequently - fragments do not work.

EDIT: I found out that the Reveal.initialize part at the end of the html file does not contain "fragments: true"

Sample Org:

```
#+TITLE: Test
#+DESCRIPTION: v0.3
#+OPTIONS: pri:t todo:t
#+OPTIONS: num:nil
#+OPTIONS: reveal_mathjax:t
#+REVEAL_ROOT: ./reveal.js
#+REVEAL_THEME: white
#+REVEAL_SLIDE_NUMBER: t
#+REVEAL_MARGIN: 0.2
#+REVEAL_MAX_SCALE: 2.5


* Headline One

** Test Fragments
#+ATTR_REVEAL: :frag grow :fragidx (5 3 2 1 4)

- These
- Do
- Not
- Appear
- As
- Fragments
```

**Comment by yjwen** [comment]
Hi,

  Could you please provide a sample .org file to reproduce the issue?

Regards,
Yujie

**Comment by emanjavacas** [comment]
same issue here. The "fragments: true," hack didn't work thought.
I did some trial and error and found out that now fragments are being exported as:

    <span class="fragment role-in"><p>blabla</p></span>

And whenever I change it to 

    <p class="fragment role-in">blabla</p>

it works again.
