### ISSUE TITLE
org-reveal-title-slide-template compatible with typical #+options settings?

### ISSUE THREAD

**Issue by jwhendy** [yjwen/org-reveal#115]
I looked at the help for `org-reveal-title-slide-template` after being quite confused as to why `username@hostname` was appearing on my title slide. I see this:

```
org-reveal-title-slide-template is a variable defined in `ox-reveal.el'.
Its value is "<h1>%t</h1>
<h2>%a</h2>
<h2>%e</h2>
<h2>%d</h2>"

Documentation:
Format template to specify title page slide.
See `org-html-postamble-format' for the valid elements which
can be include.
```

The reference to `org-html-postamble-format` would lead me to think that typical `#+options` settings which affect the contents of the regular `html` postamble contents would work with `org-reveal`. For example, I have this test file:

```
#+REVEAL_HLEVEL: 1
#+options: email:nil
#+author: John Henderson
#+title: Test

* Test
```

I still get `username@hostname` on the title slide. If I export using `ox-html`, the `email:t/nil` setting, indeed, adds/removes that from the postamble. Should this be translating to `org-reveal`? Alternatively, how _should_ I be removing this from the `reveal.js` title slide?

**Comment by yjwen** [comment]
OK. The document string is confusing. I've add clear introduction on escaping characters to it.

The title slide template don't read `#+OPTIONS` settings. To remove the email address, please give a new title slide template string like `<h1>%t</h1><h2>%a</h2>` to either the variable `org-reveal-title-slide-template` or the document option `#+REVEAL_TITLE_SLIDE_TEMPLATE`.
