### ISSUE TITLE
ATTR_REVEAL :frag roll-in doesnt' do item by item an more. 

### ISSUE THREAD

**Issue by fkchang** [yjwen/org-reveal#118]
Using the most current version of ox-reveal (downloaded from melpa, see it's the same as head)
```
* Header
#+ATTR_REVEAL: :frag roll-in
  - item 1
  - item 2
  - item 3
```
used to create it so each <li> had the classes "fragment rolled in" which allowed them to be rolled in. Now the <ul> gets those classes instead and the whole list rolls in.

So my old presentations are broken, unless there is some other way to indicate the item by item roll in?

**Comment by yjwen** [comment]
Hi,

  The code was updated recently to support different fragment style on items of the same list. Accordingly, `:frag frag-style` is changed to do fragment on list as a whole. To specify item-wise fragment, please use `:frag (frag-style)`.

  Detail description can be found at https://github.com/yjwen/org-reveal#list-fragments

Regards,
Yujie
