### ISSUE TITLE
Change margin for specific page

### ISSUE THREAD

**Issue by Balooga** [yjwen/org-reveal#126]
I have a wide table with several columns. Is there the capability to set the margin for an individual slide?  Or does margin only apply to the whole presentation?

Thanks,.

**Comment by yjwen** [comment]
Hi,

  Org-reveal sets margin for the whole presentation, by the method illustrated at https://github.com/hakimel/reveal.js/#presentation-size

  I don't know how to control the margin of a single Reveal.js slide. Maybe you can file an issue at [Reveal.js home page](https://github.com/hakimel/reveal.js/). Once there is such method for Reveal.js, let me find a way to achieve it in Org-reveal. :)

Regards,
Yujie

**Comment by Balooga** [comment]
Asked :)  Thanks.

https://github.com/hakimel/reveal.js/issues/1317
