### ISSUE TITLE
missing org-export-solidify-link-text function

### ISSUE THREAD

**Issue by ericsfraga** [yjwen/org-reveal#127]
The org-export-solidify-link-text function was removed from org a while ago.  It is no longer needed as the definition of possible link targets has been firmed up to avoid problems.

The following removes the need for this in ox-reveal:

```
diff --git a/ox-reveal.el b/ox-reveal.el
index 086459c..052e28b 100755
--- a/ox-reveal.el
+++ b/ox-reveal.el
@@ -846,8 +846,7 @@ contextual information."
            (frag (org-export-read-attribute :attr_reveal src-block :frag))
            (label (let ((lbl (org-element-property :name src-block)))
                     (if (not lbl) ""
-                      (format " id=\"%s\""
-                              (org-export-solidify-link-text lbl))))))
+                      (format " id=\"%s\"" lbl)))))
       (if (not lang)
           (format "<pre %s%s>\n%s</pre>"
                   (or (frag-class frag info) " class=\"example\"")
```

Thanks.

**Comment by yjwen** [comment]
Fixed as you suggested and many thanks for the notes. :)

**Comment by ericsfraga** [comment]
On Monday,  3 Aug 2015 at 00:19, Yujie Wen wrote:
> Fixed as you suggested and many thanks for the notes. :)

You're very welcome and thanks for fixing this.  Very useful package.

-- 
: Eric S Fraga (0xFFFCF67D), Emacs 25.0.50.2, Org release_8.3beta-1303-g3f0398

**Comment by grettke** [comment]
@punchagan My box is running Org-Mode 8.3.1 from Git and I just ran into this exact same line of code. I fixed it the same way. FYI.
