### ISSUE TITLE
Export error: unknow backend

### ISSUE THREAD

**Issue by gongzhitaao** [yjwen/org-reveal#128]
I use `org-reveal-publish-to-reveal` as `publishing-function` in project list, It gives me the following errors:

```
Debugger entered--Lisp error: (error "Unknown \"nil\" back-end: Aborting export")
```

When tracing back, It seems that in

``` emacs-lisp
(defun org-export-as
    (backend &optional subtreep visible-only body-only ext-plist)
```

The `backend` is `nil`.

However it works fine if I simply export the current file with `C-c C-e R R`.

Org-mode Version: `8.3.1 (8.3.1-elpaplus)`.
Emacs Version: `GNU Emacs 24.4.1`.

**Comment by yjwen** [comment]
Fixed in master branch.
