### ISSUE TITLE
org-reveal from MELPA doesn't work with Org 8.3

### ISSUE THREAD

**Issue by snosov1** [yjwen/org-reveal#132]
Hi!

Consider the simplest org file

```
#+TITLE: TEST
```

It is exported fine by `ox-reveal` version `20150816.2222` with Org 8.2, but with Org-mode version 8.3.1 (8.3.1-56-g17a225-elpa @ /home/sergei/.emacs.d/elpa/org-20150817/) it gives the following message:

```
apply: Wrong type argument: listp, #("TEST" 0 4 (:parent (#0)))
```

If you remove the TITLE annotation - it will work just fine (after you add some content, that doesn't have lines, like #+TITLE, #+AUTHOR, #+EMAIL, etc.).

**Comment by gongzhitaao** [comment]
I have the same issue.  I just reload the org (<kbd>C-u C-c C-s !</kbd>), everything works.  It seems that it is not the problem of org-reveal.

**Comment by snosov1** [comment]
This doesn't seem to help me.

Same error after `org-reload`.

**Comment by gongzhitaao** [comment]
Another thing that comes to my mind is do you have the builtin version of org exist on your system?  I removed the builtin version from the Emacs.  They seem to conflict with the recent version of Org.  But still it seems to me a bug of orgmode :)

**Comment by snosov1** [comment]
Yes, I do have the built-in version installed. And I agree that the 2 versions can potentially conflict. But at the moment, I don't really see any pointers that this is the case.

**Comment by yjwen** [comment]
It is due to Org 8.2 and Org 8.3 has different API definition. The MELPA org-reveal was designed for using Org 8.2 APIs. But since recently Org-mode in ELPA has been upgraded to 8.3 series, I've also just updated MELPA org-reveal to using Org 8.3 APIs.

Please update your org-reveal from MELPA and try again to see if the issue still exists.

**Comment by snosov1** [comment]
Same error, still. 

Both the recent org-reveal from MELPA and master branch show the same error.

**Comment by gongzhitaao** [comment]
I just updated org and it works. :smiley:

**Comment by snosov1** [comment]
Ok, seems to work after update to org ELPA version 20150824. Didn't work with previous one (20150817). Thanks!

**Comment by yjwen** [comment]
Glad to know the issue was gone with my updates. :)

2015-08-27 17:37 GMT+08:00 Sergei Nosov <notifications@github.com>:

**Comment by snosov1** [comment]
:+1:

**Comment by danielsz** [comment]
Sorry to spoil the mood, but I still need to remove the lines that start with #+TITLE, #+AUTHOR, #+EMAIL to make org-reveal work. 

```
Org-mode version 8.3.1 (8.3.1-87-g4ef2c0-elpa @ /home/daniel/.emacs.d/.cask/24.5.1/elpa/org-20150824/)
```

And ox-reveal: 

```
.cask/24.5.1/elpa/ox-reveal-20150824.214
```

**Comment by yjwen** [comment]
Don't need to sorry. :)

What is the error message saying?

2015-08-31 8:28 GMT+08:00 Daniel Szmulewicz <notifications@github.com>:

**Comment by danielsz** [comment]
The error message is:
``` 
org-babel-exp process emacs-lisp at line 57...
apply: Wrong type argument: listp, #("Daniel Szmulewicz" 0 17 (:parent (#0)))
```
It seems it can't process the header with tags such as  `#+TITLE`, `#+AUTHOR`, `#+EMAIL` 
```
#+AUTHOR: Daniel Szmulewicz
#+TITLE: Interactive programming, from first principles to system
```

**Comment by yjwen** [comment]
Possibly the same issue as reported in #135 . Please trace the issue there.
