### ISSUE TITLE
Image attributes are ignored when reveal_single_file is set

### ISSUE THREAD

**Issue by snosov1** [yjwen/org-reveal#133]
Consider the simplest case:

```
* Test

#+ATTR_HTML: :width 50%
[[file:test.jpg]]
```

After exporting, the image tag looks like

```
<img src="test.jpg" alt="test.jpg" width="50%" />
```

If you add `#+OPTIONS: reveal_single_file:t` on top, it becomes

```
<img src="data:image/jpg;base64,/9j/4AAQSkZJ......//9k=" />
```

i.e. the width attribute is lost.

**Comment by yjwen** [comment]
Just fixed. Please pull the master branch.

**Comment by snosov1** [comment]
Thanks! Seems to work fine! :+1:
