### ISSUE TITLE
can't export when use fragment 

### ISSUE THREAD

**Issue by nzw0301** [yjwen/org-reveal#134]
I use `ox-reveal` version `20150816.2222`, `org` version `20150817`.
When I don't use fragment, I can export reveal.js slide.
But I use fragment in code, it displays the following error message

```
Wrong number of arguments: #[(checkbox info) "^HÃ       Ä\"
\236A\236A\207" [checkbox info org-html-checkbox-types plist-get :html-checkbox-type] 4 ("/Users/nzw/.emacs.d/elpa/org-plus-co\
ntrib-20150817/ox-html.elc" . 86020)], 1
```

My org file is 
```
#+REVEAL_ROOT: http://cdn.jsdelivr.net/reveal.js/latest/
#+REVEAL_MATHJAX_URL: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#+OPTIONS: reveal_mathjax:t
#+TITLE: sample
#+AUTHOR: nzw

* hoge
  - hoge
  - hgoe

* hgoe
```

**Comment by gongzhitaao** [comment]
Reload org and try again <kbd>C-u C-c C-x</kbd>.  It is likely that your new org is conflicting with the builtin org in Emacs.  You may remove the builtin org.

**Comment by nzw0301** [comment]
I reload org, but  I can't soved this error.
next, I remove builtin Org(/usr/local/Cellar/emacs/24.5/share/emacs/24.5/lisp/org), but same error appear.

**Comment by yjwen** [comment]
It is due to ELPA org has been upgrade to version 8.3, which has some different API definition from version 8.2.

Just merged the MELPA ox-reveal with org-reveal's master branch. The wring API issue should be solved. Please wait for MELPA's update and then upgrade ox-reveal.

**Comment by nzw0301** [comment]
I can export reveal's slide.
Thank you so much.
