### ISSUE TITLE
Error message on C-c C-e RR

### ISSUE THREAD

**Issue by deadlytackler5** [yjwen/org-reveal#135]
I am using GNU Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570 . After opening readme.org and pressing C-c C-e RR am getting this error:-
 ```
(wrong-type-argument listp #("Yujie Wen" 0 9 (:parent (#1))))
```
Where is the issue ?
As suggested:-
1. Downloaded Reveal.js.
2. Extracted Reveal.js folders from the downloaded zip file.
3. My default org-mode version 8.3.1
4. a) Initially cloned the org-reveal github repository and extracted ox-reveal.el and put inside org folder.
4. b) when 4(a) didn't work, downloaded through M-x list-packages.
5. added ```(require 'ox-reveal)``` to my emacs config.
6.added ```(setq org-reveal-root "file:///c:/emacs/reveal.js")``` that's where my reveal.js file is.

**Comment by gongzhitaao** [comment]
Probably similar to #132 or conflict of different version of `org` (Just guess)?

**Comment by deadlytackler5** [comment]
yes its similar to #132. However checked my org-version it's 8.3.1(24/8/2015). Do I have to delete default org? If yes How to do that ?

**Comment by danielsz** [comment]
I'm seeing the same thing. 

Running latest versions of everything.
```
Org-mode version 8.3.1 (8.3.1-87-g4ef2c0-elpa @ /home/daniel/.emacs.d/.cask/24.5.1/elpa/org-20150824/)
```

And ox-reveal: 

```
.cask/24.5.1/elpa/ox-reveal-20150824.214
```

**Comment by danielsz** [comment]
The error message is:
``` 
org-babel-exp process emacs-lisp at line 57...
apply: Wrong type argument: listp, #("Daniel Szmulewicz" 0 17 (:parent (#0)))
```
It seems it can't process the header with tags such as  `#+TITLE`, `#+AUTHOR`, `#+EMAIL` 
```
#+AUTHOR: Daniel Szmulewicz
#+TITLE: Interactive programming, from first principles to system
```
When removed, it exports fine.

**Comment by yjwen** [comment]
I reproduced the issue with org-mode 20150824. It was an issue of org-mode itself. Exporting plain HTML failed with the same error message.

The issue was gone when I updated org-mode to 20150831. So please also try to update your org-mode to see if the issue is gone.

**Comment by danielsz** [comment]
`org-mode`upgraded, problem gone. 
Thank you, @yjwen

**Comment by canweriotnow** [comment]
I'm seeing the same problem with org-20150921... it's back?

**Comment by Altmic** [comment]
I have started to use org-mode and emacs and I want to try org-reveal for presentations. But I have an error in my .emacs (require 'ox-reveal) from the very beginning:
ox-reveal not found. 
I have downloaded the file and put in the directory where all the org files are located.
This is for me: /users/privat/.emacs.d/elpa/org-20151005/ox-reveal.el
I get the org-reveal from github
org 8.3.2
Any help?
Thank you

Michael

**Comment by yjwen** [comment]
Not sure the exact reason why ox-reveal is not found.

But can you please try to put ox-reveal.el to your .emacs.d
(/users/privat/.emacs.d/) and add .emacs.d to the load path?
(add-to-list 'load-path "/users/privat/.emacs.d")

You can also use the MELPA package of org-reveal.


2015-11-24 22:54 GMT+08:00 Altmic <notifications@github.com>:

**Comment by tamouse** [comment]
I'm seeing this error today, using org-version 9.0.5 (org-20170210), ox-reveal-20161027.226, and emacs 25.1.1 from homebrew. Trying to set `#+AUTHOR` gives `Wrong type of argument: listp, #("Tamara Temple" 0 13 (:parent (#0)))` and setting `#+TITLE` gives the same sort of error.

**Comment by sjsrey** [comment]
I'm hitting the same error as @tamouse but on ubuntu mate 17.04

- org version 20170703
- ox-reveal version 20161027.226
