### ISSUE TITLE
Problem with internal links

### ISSUE THREAD

**Issue by edwinhu** [yjwen/org-reveal#138]
Setting the `:CUSTOM_ID:` property does not work as intended. For instance if I create a header

```
* Foo
  :PROPERTIES:
  :CUSTOM_ID: bar
  :END:
```
The generated HTML will be:
```html
<section id="slide-bar">
<h3 id="bar"><a id="sec-31-1" name="sec-31-1"></a>Foo</h3>
```

If I try to link to `"bar"` using `[[#bar][Link]]` it will take me to the title slide because there is no `section id="bar"` instead it is `section id="slide-bar"`. Using `[[#slide-bar][Link]]` does not work either.

**Comment by yjwen** [comment]
Fixed. Now `[[#bar][link]]` works.
