### ISSUE TITLE
single file cannot find reveal.css

### ISSUE THREAD

**Issue by buster** [yjwen/org-reveal#139]
Hi,

i am trying to use the single file option, but emacs only shows the following error on export:

```
org-reveal-stylesheets: Cannot read http://cdn.jsdelivr.net/reveal.js/3.0.0/css/reveal.css, http://cdn.jsdelivr.net/reveal.js/3.0.0/css/theme/moon.css
```

**Comment by yjwen** [comment]
It is because org-reveal is trying to copy the content of reveal.css and moon.css into the exported single HTML file but failed.

Could you please use a Reveal.js in your local machine?

**Comment by buster** [comment]
Ok, i didn't know that..thanks!

**Comment by yxsongbo** [comment]
can not read in my local machine

**Comment by grokkingStuff** [comment]
Can we reopen this issue, it's a weird bug that could be fixed.
