### ISSUE TITLE
JS dependencies not being put into non- single-file

### ISSUE THREAD

**Issue by markjfisher** [yjwen/org-reveal#140]
I'm running ox-reveal from elpa (ox-reveal-20150824.214), on emacs 24.5.1 on Mac OS-X, installed from homebrew and with prelude base emacs.d configuration.

I was having an issue that highlighting and notes were not working when included in non- single-file situation. I have hightlight.js installed in emacs (I can execute it on buffers for instance) and noticed that highlighting was only working when I removed it from the list of plugins.

Notes wasn't popping up when I pressed 's' but I could see my notes in the generated file.

It wasn't clear to me, until I went through the source, that including plugins is supposed to include the relevant javascript library in the generated html, and thus highlight is used at runtime if you include it as a plugin, and is used at compile time if you don't include it (bloating the html).

I tracked the issue down to the dependencies block in https://github.com/yjwen/org-reveal/blob/master/ox-reveal.el#L606

When I compile this, I get an error:

    Warning: value returned from (concat "
    // Optional libraries used to extend on reveal.js
    dependencies: [
    " (let* ((builtins ... 
    ") is unused

My elisp foo is minimal, but I worked out that the "/n" on https://github.com/yjwen/org-reveal/blob/master/ox-reveal.el#L641 is causing the entire block to simply return a CR to the concat block under all circumstances.

Removing it and compiling both fixes the warning, and includes the JS libs in the output, which fixes the notes issue.

I haven't worked out why highlight.js isn't actually working yet, but this is a step forward.

If I have time I'll put this into a patch, but there are a couple of other issues around 'file:///' removal that I want to prove first - they should only be "file://" removal and honouring the final slash as part of the path, otherwise I get "could not find file Users/xxx/path/to/file".

**Comment by malcolmsparks** [comment]
Independently, I've hit the same problem and have diagnosed the error to the same line. I've raised a PR #141 to fix this in case you don't have time to create one.

**Comment by markjfisher** [comment]
Addendum. The fix makes highlight.js external library work now, but there isn't a CSS file referenced that includes any of the hljs-* class styles, so the output is plain.

What is the recommended way of using the highlight plugin and getting it to use a CSS file that is relevant to the current theme?

**Comment by cpbotha** [comment]
@markjfisher I downloaded one of the highlight.js CSS themes, put it in the same directory as my org file, and then added the following option:

```
#+REVEAL_EXTRA_CSS: github.css
```
