### ISSUE TITLE
Error on export

### ISSUE THREAD

**Issue by BubblesToTheLimit** [yjwen/org-reveal#146]
Hey,

i just installed everything according to the manual and "grunt serve" starts up the default presentation without any errors.
On export i get only the following line and no export-file is generated:
apply: Wrong type argument: listp, #("Kevin Robbins" 0 13 (:parent (#0)))

![screenshot org-reveal](https://cloud.githubusercontent.com/assets/11775168/10043995/60752740-61f7-11e5-911f-e785dfe3fcaf.png)

Do you know of any steps i might take to solve this issue?

**Comment by yjwen** [comment]
Hi,

  It should be the same problem of #135. It was a problem of Org-mode itself. Please update Org-mode to the version newer than Org-mode 20150824 to see if the error is gone.

Regards,
Yujie

**Comment by BubblesToTheLimit** [comment]
Thank you so much! It works :)

**Comment by otesuji** [comment]
error is F..... back
