### ISSUE TITLE
org-export-get-reference:  Symbol's function definition is void (fixed by commenting out)

### ISSUE THREAD

**Issue by dctoedt** [yjwen/org-reveal#152]
When I installed org-reveal and tried it, the export process threw an error:  "Symbol’s function definition is void: org-export-get-reference"

I searched for that function in ox-reveal.el and found it at line 381 --- commenting out that line seemed to solve the problem.

 (preferred-id (or (org-element-property :CUSTOM_ID headline)
			      ;;  (org-export-get-reference headline info)  ;; I COMMENTED OUT THIS LINE
			       (org-element-property :ID headline)))

I'll leave it to others more skilled than I to determine whether this is truly a fix or just dumb luck.

**Comment by pallix** [comment]
I had the same problem and updating `org-mode` solved it

**Comment by yjwen** [comment]
Yes, please update Org-mode to 8.3.

**Comment by psachin** [comment]
I'm using org-version 8.3.5(Emacs version 25.0.95.1) Still have this problem.

**Comment by erdmenger** [comment]
Thank you for me Org-mode 9.0 fixed the issue.

**Comment by thomasluquet** [comment]
i got this problem also :-( 
(And i am on org-mode 9.0.3 / elpa)

**Comment by erdmenger** [comment]
Now I have the same issue on my Macbook Pro. Trying to solve it with installing the latest version of org-mode (20170210) from elpa at the end I get an error:
Symbol’s function definition is void: org-link-set-parameters
Even though I tried the org-reload , uninstall, install loop several times, as described here:
https://lists.gnu.org/archive/html/emacs-orgmode/2015-08/msg00321.html

Any hints welcome.

**Comment by stasvlasov** [comment]
Dear all, I had the same problem (on mac with emacs 25.1.1 and org-2017-05-15). I guess it is something with [org installation](http://orgmode.org/manual/Installation.html): 

> Important: you need to do this in a session where no .org file has been visited, i.e., where no Org built-in function have been loaded. Otherwise autoload Org functions will mess up the installation.

This steps worked for me:

- delete all packages from ~/.emacs.d/elpa
- start vanilla emacs (i.e., like with empty init.el and do NOT call `package-initialize`)
- add `http://elpa.gnu.org/packages/` to `package-archives` variable (with `M-: (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)`
- call `M-x package-list-packages`
- install newest `org` (in my case it was `org-2017-05-15`)
- restart emacs as usual (all packages will be reinstalled automatically if you require it with `use-package`)

After this work around the error was gone. But I would still consider it a bug to fix.
