### ISSUE TITLE
REVEAL_TRANS variable is ignored when specifying REVEAL_ROOT

### ISSUE THREAD

**Issue by pallix** [yjwen/org-reveal#153]
When specifying `REVEAL_ROOT` in a presentation, the variable `REVEAL_TRANS` is ignored and the presentation is exported with the cube transition. 

Example:
```
#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:nil reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+OPTIONS: toc:1
#+REVEAL_ROOT: http://cdn.jsdelivr.net/reveal.js/2.5.0/
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: slide
#+REVEAL_THEME: moon
#+REVEAL_HLEVEL: 2
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="AB">
#+REVEAL_PLUGINS: (highlight markdown notes)
#+REVEAL_EXTRA_CSS: ./local.css

```

**Comment by yjwen** [comment]
Hi,

  You are using an rather old version of Reveal.js which doesn't have the `slide` transition.

  Please try some newer Reveal.js, for example, `#+REVEAL_ROOT: http://lab.hakim.se/reveal-js/`.

Regards,
Yujie

**Comment by pallix** [comment]
It worked! Thanks for the help. `README.md` should be updated as I got the URL from it.
