### ISSUE TITLE
Option to add SVG as an <img>, rather than <svg>

### ISSUE THREAD

**Issue by lvh** [yjwen/org-reveal#154]
Since [this commit](https://github.com/yjwen/org-reveal/commit/74b9a3c8cb4df9f38ce5ed5222d8550a418d5c6b), it appears that SVGs are never added as `<img>` anymore. This is a problem, because it breaks scaling them.

I've tried disabling `reveal_single_file:f` manually, but this doesn't work; apparently it's unrelated to that feature.

**Comment by yjwen** [comment]
Hi,

  Please use `reveal_single_file:nil` to disable single-file options, or simply remove the `reveal_single_file` option. In both case, the SVG images are exported in the same way the HTML exporter does and scaling works.

Regards,
Yujie

**Comment by lvh** [comment]
Thanks for your reply! Both with `reveal_single_file` missing and manually disabled, this snippet:

```org
** Title

   #+ATTR_HTML: :style width:80%
   [[./media/lvh.svg]]
```

Compiles down to:

```html
<div class="figure">
<p><object type="image/svg+xml" data="./media/lvh.svg" style="width:500%">
Sorry, your browser does not support SVG.</object>
</p>
</div>
```

Because the styling is applied to the object, the scaling does not work. Previously, it compiled down to:

```html
<div class="figure">
<p><img src="./media/lvh.svg" alt="lvh.svg" style="width:80%">
</p>
</div>
```

The `<img>` tag works as expected.

**Comment by lvh** [comment]
I suppose this may be a difference in how the HTML exporter works?

**Comment by yjwen** [comment]
I didn't reproduce the false `style="width:500%"` issue with the latest org-reveal and Org-mode. Either the HTML exporter or the Reveal.js exporter writes the correct `style` tag for SVG pictures.

Could you please provide the version of your Org-mode, org-reveal and a complete sample file to reproduce the issue?

**Comment by lvh** [comment]
When you say the "correct" style tag, do you mean `<img style="..." ...>`? In my case I am seeing the `<object>` tag and it does have a correct style tag; the problem is that style tags on `<object>` (well, at least scaling-related styles) work completely differently between those two tags.

I've found the problem in [org-mode's source code](http://orgmode.org/w/?p=org-mode.git;a=blob_plain;f=lisp/ox-html.el;hb=HEAD):

```elisp
(defun org-html--format-image (source attributes info)
  "Return \"img\" tag with given SOURCE and ATTRIBUTES.
SOURCE is a string specifying the location of the image.
ATTRIBUTES is a plist, as returned by
`org-export-read-attribute'.  INFO is a plist used as
a communication channel."
  (if (string= "svg" (file-name-extension source))
      (org-html--svg-image source attributes info)
    (org-html-close-tag
     "img"
     (org-html--make-attribute-string
      (org-combine-plists
       (list :src source
	     :alt (if (string-match-p "^ltxpng/" source)
		      (org-html-encode-plain-text
		       (org-find-text-property-in-string 'org-latex-src source))
		    (file-name-nondirectory source)))
       attributes))
     info)))

(defun org-html--svg-image (source attributes info)
  "Return \"object\" appropriate for embedding svg file SOURCE
with assoicated ATTRIBUTES. INFO is a plist used as a
communication channel.

The special attribute \"fallback\" can be used to specify a fallback
image file to use if the object embedding is not supported."
  (let ((fallback (plist-get attributes :fallback))
	(attrs (org-html--make-attribute-string
		(plist-put attributes :fallback nil))))
  (format "<object type=\"image/svg+xml\" data=\"%s\" %s>\n%s</object>"
	  source attrs
	  (if fallback
	      (org-html-close-tag
	       "img" (format "src=\"%s\" %s" fallback attrs) info)
	    "Sorry, your browser does not support SVG."))))
```

As you can see, it unconditionally checks if the URL ends in "svg", and then unconditionally produces the `object` tag. This is in org-mode head. I have versions:

```
org-version is a variable defined in `org.el'.
Its value is "8.3.2"
```

org-reveal version is the current one from MELPA.

Since this is an upstream issue, I guess I'm closing this?

For people who find it in the future, the workaround I'm using is a literal HTML block:

```org
** GitHub
   #+BEGIN_HTML
   <img style="width:60%" src="./media/Octocat.svg">
   #+END_HTML
```

**Comment by yjwen** [comment]
Yes, it is ox-html.el that exports svg into `<object>` unconditionally.

Just for interest, what is the difference between scaling `<object>` and `<img>`? :)

**Comment by lvh** [comment]
I have selected the images with Developer Tools to highlight how big the element actually is.

This slide:

```org
** Who am I?

   #+BEGIN_HTML
   <img style="width:70%" src="./media/lvh.svg">
   #+END_HTML
```

... produces `<img>` with 70% width takes the image's base size, and scales it up to 70% width.

<img width="489" alt="screen shot 2015-10-10 at 5 57 05 pm" src="https://cloud.githubusercontent.com/assets/97816/10411990/59122cda-6f78-11e5-815f-7750c09882f3.png">

This slide:

```org
** Who am I?

   #+ATTR_HTML: :style width:70%
   [[./media/lvh.svg]]
```

... produces `<object>` with 70% width makes a 70% wide canvas, but does not scale the actual image:

<img width="583" alt="screen shot 2015-10-10 at 5 56 35 pm" src="https://cloud.githubusercontent.com/assets/97816/10411991/592ea3f6-6f78-11e5-80fe-a3d10ff91709.png">

Previously both slides produced the `<img>` tag.
