### ISSUE TITLE
new to reveal and org-reveal..export to pdf?

### ISSUE THREAD

**Issue by zeltak** [yjwen/org-reveal#157]
Hi
First of all a huge thx for this org exporter, this really is amazing.

one question though (and it may be silly since im a neewb). can one also export to PDF with all the css styles, images etc with org-reveal? if not does reveal allow this? i couldnt find out how to do so

best!

Z

**Comment by yjwen** [comment]
Yes. Of course Org-reveal's slides can be export to PDF as reveal.js does. Please refer to [reveal.js's document](https://github.com/hakimel/reveal.js#pdf-export) for the detail explanation.

Two things need to be noticed:
  1. PDF-export works only in Google Chrome
  2. If you saw background styles are missing, please make sure to select background on "More Options" of the Printing option dialog (Or similar options. Sorry my Chrome is in Chinese and I didn't figure out how to change the UI language to English. So I don't know the exact words of the options.)

Regards,
Yujie

**Comment by zeltak** [comment]
Thank so much again. this seems like a great solution. one thing i dont understand (sorry again im a neewb :)) is this:

"Open your presentation with print-pdf included anywhere in the query string."

do you know what they mean by that?

thanks again for org-reveal! im starting to prepare my lectures for next semester and finally i can do them all in org!

best

Z

**Comment by zeltak** [comment]
ok solved it!

thx again

Z

**Comment by aaronchall** [comment]
Don't be a [denvercoder9](https://xkcd.com/979/) - what solved it?

**Comment by alvaro121** [comment]
Do something like `http://localhost:8000/?print-pdf` for your presentation (i.e., add `?print-pdf` at the end, whether an HTML file or served from somewhere.
