### ISSUE TITLE
link in slide to open the actual org file? (for course in R)

### ISSUE THREAD

**Issue by zeltak** [yjwen/org-reveal#158]
Hi again!
I am building an introduction to R course using org (and now org-reveal!). in some slide i show code blocks and would like to show the students the actual run of the code.
i was wondering if anyone knew if there is a way to press a link in my reveal slide show that would take me to the corresponding org header where i could actually run the code in R+ESS.

thanks so much again

Z

**Comment by yjwen** [comment]
The requirement looks more like dynamic evaluation of codes in org-mode or HTML, a little beyond ox-reveal and maybe reveal.js. I'd close this issue.
