### ISSUE TITLE
Background images don't get embedded

### ISSUE THREAD

**Issue by stefanwouldgo** [yjwen/org-reveal#159]
When I use the reveal_single_file option, only normally inserted images get embedded in the html, but background images are missing.

**Comment by vejeta** [comment]
It works fine for me with something like:

```
* Emacs Presentation
    :PROPERTIES:
    :reveal_background: ./images/logo.png
```

**Comment by yjwen** [comment]
By [Reveal.js document](https://github.com/hakimel/reveal.js#slide-backgrounds), it seems embedded background image is not supported. And I tried to embed image to the `data-background` property of `<section>` tag, but no background image was displayed.

So Reveal.js really doesn't support embedded background images.
