### ISSUE TITLE
some desgin questions

### ISSUE THREAD

**Issue by zeltak** [yjwen/org-reveal#160]
Hi all

excuse me for these questions that may seem trivial but as a new user i havent been able to address them
1) how does one add images not below the text but on the left/right of the text?
2) can i change the fonts size per slide or even better per specific line/region?
3)can slide headers be placed higher up on the slide?

thx so much

z

**Comment by yjwen** [comment]
1) how does one add images not below the text but on the left/right of the text?
Simply embed the image into your paragraph.
```org
* Slide 1
  Some text [[./some_image.jpg]].
```
But for a better control on the layout, table is suggested.
```org
* Slide 1
  | Some text | [[./some_image.jpg]] |
```
2) can i change the fonts size per slide or even better per specific line/region?

You can use CSS to overwrite the style of any Reveal.js element. Org-reveal exports each slide into sections with id tag like `<section id="slide-orgheadline1">`, the tailing number changes for each slide. So you can overwrite one slide's style in a CSS like:
```css
slide-orgheadline1 {
 ...
}
```
3)can slide headers be placed higher up on the slide?
It can be also controlled by CSS. You need to check current theme's CSS first, overwrite some tag, like margin?

Regards,
Yujie

**Comment by zeltak** [comment]
Thx so much, this is really so helpful :)

forgot to ask 1 last question:

how do i (for a specific slide) make all text not centered but rather left aligned?

best and thanks again

Z

**Comment by yjwen** [comment]
Similar to 2). 
```css
slide-orgheadline1 {
  text-align: centered;
}
```

**Comment by fkgruber** [comment]
I'm checking the exported html and it seems to be using randomly generated section ids. Is there a way to give it an id?

**Comment by lechten** [comment]
Yes, you can add a `CUSTOM_ID` property. See Readme.org for an example. Or [over there in my emacs-reveal howto](https://gitlab.com/oer/emacs-reveal-howto/blob/master/howto.org).

**Comment by fkgruber** [comment]
Thanks! that worked out.
