### ISSUE TITLE
Error building readme: Wrong number of arguments

### ISSUE THREAD

**Issue by WorldsEndless** [yjwen/org-reveal#162]
Trying to follow the primary instructions I get: 

'''
concat: Wrong number of arguments: #[(checkbox) "ÁÂ\"	 and a bunch of other gibberish that 
'''
is apparently un-postable here. 
![reveal-error](https://cloud.githubusercontent.com/assets/5042778/10733880/418f32b0-7bc6-11e5-858c-1361118ca80f.jpg)

I'm using, on Linux: 
Org-mode version 8.2.10 (release_8.2.10 @ /usr/local/share/emacs/24.5/lisp/org/)

**Comment by coreysharris** [comment]
Just got this too using OS X (same versions of Emacs/Org-mode).

**Comment by yjwen** [comment]
Please update org-mode to 8.3. Org-mode from ELPA is suggested.

2015-10-27 2:59 GMT+08:00 Corey Harris <notifications@github.com>:

**Comment by WorldsEndless** [comment]
After updating I received another error that had to do with some custom export-to-html settings of mine (Org's export to HTML wasn't working, either). After commenting out my custom settings, all worked well. Thanks for the fantastic plugin!

**Comment by yjwen** [comment]
Thanks. Glad to know org-reveal helps. :)

2015-10-27 22:12 GMT+08:00 Tory S. Anderson <notifications@github.com>:

**Comment by bwo** [comment]
I just got this on a totally fresh install of both org and org-reveal.
