### ISSUE TITLE
Adding data-background-video to section

### ISSUE THREAD

**Issue by coreysharris** [yjwen/org-reveal#165]
Is it possible to add arbitrary properties to a section tag through org-reveal?  Or more specifically, is there already a directive for adding background videos in org-reveal?

An additional property is the data-background-video-loop which can be set to "loop" to cause the background video to repeat indefinitely.

**Comment by yjwen** [comment]
You can add arbitrary HTML attributes to a headline by Org-mode's property named REVEAL_EXTRA_ATTR.
```
* Slide 1
  :PROPERTIES:
  :REVEAL_EXTRA_ATTR: style="background-color:orange;"
  :END:
```

The generated `<section>` tag will be `<section id="slide-orgheadline1" style="background-color:orange;">`.

**Comment by agzam** [comment]
I can confirm this worked for me:

    :PROPERTIES:
    :REVEAL_EXTRA_ATTR: data-background-video="./img/pretend-nothing-happening.mp4"; data-background-video-loop="loop"
    :END:
