### ISSUE TITLE
Permit non-boolean values for org-reveal-slide-number

### ISSUE THREAD

**Issue by titaniumbones** [yjwen/org-reveal#166]
reveal.js accepts string arguments to the "number" argument.  The diff below permits these.

diff --git a/ox-reveal.el b/ox-reveal.el
index b46d5f4..a25e0da 100755
--- a/ox-reveal.el
+++ b/ox-reveal.el
@@ -219,10 +219,10 @@ can contain the following escaping elements:
   :group 'org-export-reveal
   :type 'boolean)
 
-(defcustom org-reveal-slide-number t
+(defcustom org-reveal-slide-number "c / t"
   "Reveal showing slide numbers."
   :group 'org-export-reveal
-  :type 'boolean)
+  :type 'string)
 
 (defcustom org-reveal-keyboard t
   "Reveal use keyboard navigation."

**Comment by yjwen** [comment]
Thanks for the patch. Just updated as your suggestion. :)

**Comment by titaniumbones** [comment]
great, thank you -- and prettier than my patch, too!
