### ISSUE TITLE
export include webm video possible?

### ISSUE THREAD

**Issue by zeltak** [yjwen/org-reveal#169]
Hi all

i wonder if one could include wemb in an org-reveal exported html file

i tried adding this under a header

```
#+BEGIN_HTML
 <video controls> <source src="/home/zeltak/ZH_tmp/big-buck-bunny_trailer.webm
" type="video/webm">
#+END_HTML
```

which resulted in nothing. am i doing it wrong, is it possible at all?

best

Z

**Comment by yjwen** [comment]
Sure you can embed webm videos into org-reveal, as other video format do. Please try to use an URL to your local .webm file.

I guess the proper URL in your example should be:
```org
#+BEGIN_HTML
 <video controls>
   <source src="file:///home/zeltak/ZH_tmp/big-buck-bunny_trailer.webm" type="video/webm">
 </video>
#+END_HTML
