### ISSUE TITLE
export error when add #+TITLE

### ISSUE THREAD

**Issue by shalir** [yjwen/org-reveal#171]
hi, when i C-c-e RR, i get an error like this, and i find the reason is set the `#+TITLE: test`, like picture2,  is anyone know what it is?
![image](https://cloud.githubusercontent.com/assets/3109615/11291126/d6cf096c-8f77-11e5-94fc-ce48fa56517a.png)

![image](https://cloud.githubusercontent.com/assets/3109615/11291121/c830134c-8f77-11e5-95ee-612fd909e34a.png)

**Comment by vejeta** [comment]
It happens to me also, with the latest version, latest commit from (Tue Nov 3) and Org-Mode 8.3.2

**Comment by Balooga** [comment]
I can confirm this as well.

**Comment by yjwen** [comment]
There have been several issues reporting the same thing. The error should be on org-mode side. But what is strange is that I cannot reproduce the error.

I am also using org-mode 8.3.2. So, @shalir @vejeta and @Balooga , could you please provide a minimal sample org file that can reproduce the error?

**Comment by Balooga** [comment]
I'm also using 8.3.2 - Org-mode version 8.3.2 (8.3.2-39-gd537a3-elpa @ .emacs.d/elpa/org-20151214/)

From the following;

````
#+AUTHOR: An Author
#+TITLE: Git Overview

* Introduction
- The latest version of these slides are available in Git at this location - TBD
````

Emacs returns the following error

> apply: Wrong type argument: listp, #("Git Overview" 0 12 (:parent (#0)))

**Comment by vejeta** [comment]
Same org-version that the one Luke's provide.

Just adding the #+TITLE: line produces the error.

**Comment by yjwen** [comment]
I didn't reproduce the error even with org-20151214. So I am wondering whether it is due to some configuration?

Can you please try with a minimum.emacs that load org and ox-reveal only?

**Comment by yveszoundi** [comment]
I was also having similar issues with the latest ```org``` and ```org-reveal``` packages from MELPA.

I managed to work around it with few lines at the end of my ```.emacs```:

```emacs-lisp
(require 'org)
(let ((current-prefix-arg 1))
  (call-interactively 'org-reload))
```

**Comment by vejeta** [comment]
Org-mode version 8.3.2 (8.3.2-51-g713fe8-elpa) and latest commit (017c676a19eb1996552ba6cf04d58e561cb7c7d8) from org-reveal seems to have that issue fixed.

**Comment by aaron-em** [comment]
Org 8.3.4 (ELPA 20160222) has the bug, but the workaround @yveszoundi posted solves it. Thanks!

**Comment by limist** [comment]
I'm seeing this error with Emacs 24.5, Org 8.3.4 and the current/latest org-reveal code (from github). Unfotrunately the workaround from @yveszoundi doesn't work for me.  Any idea how to fix this please?

**Comment by aaron-em** [comment]
What happens after you `C-u M-x org-reload`?

**Comment by limist** [comment]
@aaron-em Thanks for the suggestion; I tried it, no visible effect.  The `*Messages*` buffer shows,

```
apply: Wrong type argument: listp, #("Foo Title" 0 6 (:parent (#0)))
```

**Comment by limist** [comment]
@yjwen Any suggestions on how to debug this please?  Thanks in advance for any help!

**Comment by aaron-em** [comment]
It's an org bug, not an org-reveal bug. You may do better to check the org mode mailing list archive; it's probably been discussed there, and if not you can always ask about it.

**Comment by yjwen** [comment]
As #148 has suggested, [Re-install Org-mode](http://emacs.stackexchange.com/questions/14763/exporting-org-file-breaks-when-upgrading-to-orgmode-8-3)  should work.

**Comment by rzr** [comment]
hum I am unsure it is that fixed , not  on debian jessie with MELPA packages at least

**Comment by aaron-em** [comment]
@rzr Try starting with `-q`, then uninstalling Org via the `package-list-packages` interface, then restarting with `-q` and reinstalling Org.

The impression I have is that, when you already have Org loaded, the new version doesn't compile correctly. In any case, when `C-u M-x org-reload` eventually stopped solving the problem, I found the above incantation somewhere, shrugged, and mumbled it, and it appears to have resolved the issue for good.
