### ISSUE TITLE
Align/justify text to the left (and not centered)

### ISSUE THREAD

**Issue by zeltak** [yjwen/org-reveal#172]
Hi

is it possible to have text justified/aligned to the left (and not centered) for a specific slide (or all slides)

whats the syntax for that?

best

Z

**Comment by shalir** [comment]
you can add 
`#+REVEAL_EXTRA_CSS: local.css`
 to your org file and touch `local.css` file in your orgfile
and the content of local.css like this
```css
.reveal p {
    text-align: left;
}
```
then your slide will aligned to the left

**Comment by zeltak** [comment]
shalit

Thanks so much for the answer! this is really helpful
To followup: is there a way to have the slideshow by default use the left alignment you kindly showed by default but then have specific lines and/or slides use a centered alignment (for the occasional use)

best

Z

**Comment by yjwen** [comment]
You can use `#+ATTR_HTML` to declare HTML attribute to specific part of your Org document.

To make one paragraph left-aligned, Use `+ATTR_HTML: :style text-align:left`. For example
```org
* Slide 1

  This graph is center-aligned.

  #+ATTR_HTML: :style text-align:left
  This graph is left-aligned.
```

Or, if you have make all text left-aligned by using a CSS, as @shalir has suggested, then use `#+ATTR_HTML: :style text-align:center` to make some text center-aligned.

Regards,
Yujie

**Comment by zeltak** [comment]
thx so much Yujie, this is so helpful.
i guess my last related question will be (since i have all slides and single line covered) is will this work for a specific header? i tried something like this with no success

```
:PROPERTIES:
:#+ATTR_HTML:  :style text-aligns:center
:END:
```
best 

Z

**Comment by yjwen** [comment]
For specific headers, you have to turn to CSS file and CUSTOM_ID property.

For example, if there is a foo.org with the following contents:
```org
#+REVEAL_EXTRA_CSS: local.css

* Slide 1
  :PROPERTIES:
  :CUSTOM_ID: slide_1
  :END:
  
  Some text.
```
The heading `Slide 1` is assigned an ID `slide_1` that will be used in local.css. The local.css has the following contents:
```css
#slide_1 {
    text-align: left;
}
```
that specify left-aligned text for the HTML element whose ID is `slide_1`.

Regards,
Yujie
