### ISSUE TITLE
Beginner question

### ISSUE THREAD

**Issue by Altmic** [yjwen/org-reveal#173]
I have started to use org-mode and emacs and I want to try org-reveal for presentations. But I have an error in my .emacs (require 'ox-reveal) from the very beginning:
ox-reveal not found. 
I have downloaded the file and put in the directory where all the org files are located.
This is for me: /users/privat/.emacs.d/elpa/org-20151005/ox-reveal.el
I get the org-reveal from github
org 8.3.2
Any help?
Thank you

Michael

**Comment by vejeta** [comment]
do M-x package-refresh-contents, M-x package-install [ENTER] ox-reveal [ENTER]
And relaunch emacs. 

It works for me

**Comment by yjwen** [comment]
Yes. If you are using org-mode from ELPA, then MELPA's ox-reveal package is suggested.
@vejeta 's suggestion should work.

**Comment by Altmic** [comment]
vejeta and yjwen thank you very much.
Now I put the ox-reveal from github in .emacs.d and also add this directory o the load-list, this works!!
I could load the ox-reveal library and I could get a  readme.html, but only one html-file and no slides.
What is the mistake, why I could not get the slides. 
Interestingly also after refreshing the contents the ox-reveal.el is not listed in my melpa-packages.
My org-mode comes from elpa.
Thank you very much for help
Michael

**Comment by Altmic** [comment]
Now I get the solution, it was my mistake with js directory, now it works.
Thank you very much!

Michael

**Comment by vejeta** [comment]
@Altmic.
I'm glad you fixed it!

Shall you close the issue if resolved?

**Comment by yjwen** [comment]
Happy to know the issue has been resolved. Let me close it.
