### ISSUE TITLE
Fragment does not work for description list

### ISSUE THREAD

**Issue by joonro** [yjwen/org-reveal#175]
Hi,

It seems the fragment does not work for description list. For example (descirption list from https://emacsclub.github.io/html/org_tutorial.html)

```org
Matlab is a funny language. 

#+ATTR_REVEAL: :frag (appear)
- Scope :: Scope doesn't work as expected, and messes everything up
  when loops mix variables up in recursive functions.
- Namespaces :: You wish. 
- Header Files :: Nope.
```

The fragment does work for the names (`Scope`, `Namespaces`, `Header Files`), but the descriptions (e.g., `You wish.`) are always shown in the slide.

**Comment by yjwen** [comment]
Fixed. Please pull the latest master branch.

**Comment by joonro** [comment]
Thank you!
