### ISSUE TITLE
code expands over <div id="org-src-container">

### ISSUE THREAD

**Issue by cataclysmic** [yjwen/org-reveal#177]
When putting text in the code container it expands right and bottom over the borders of the <div id="org-src-container">.
I don't get scroll bars or anything for the code. It simply expands out of the viewable area.

The same happens to the table of contents when it is too long.
Is there a way to fix that?

Thanks in advance and keep it up. It's a great tool.

**Comment by yjwen** [comment]
You can overwrite the overflow style of org-src-container by a local CSS.

First, use `#+REVEAL_EXTRA_CSS` to give the file name of a local CSS.
Then, overwrite `.org-src-container` with `overflow:auto` and an absolute height, say `height:400px`.

Here is an example
```org
#+REVEAL_EXTRA_CSS: local.css

* Slide 1
  #+BEGIN_SRC c++
    foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();

    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();

    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();

    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
    foo();
  #+END_SRC
```
The `local.css`'s content is as the following:
```css
.org-src-container {
    overflow:auto;
    height:400px;
}
```
According to hakimel/reveal.js#16, relative height is not working. So you have to specify an absolute height for the source container.

Regards,
Yujie
