### ISSUE TITLE
unable to install org-reveal with cask

### ISSUE THREAD

**Issue by bowenli37** [yjwen/org-reveal#179]
~/.emacs.d/Cask:
(depends-on "org-reveal" :git "https://github.com/yjwen/org-reveal.git" :files ("*.el"))

$:cask install
Dependency org-reveal failed to install: Single file ox-reveal.el does not match package name org-reveal
Output:

The issue is resolved by forking this repository and add an blank file org-reveal.el

**Comment by yjwen** [comment]
Sorry there is no plan to support cask yet. Too many package managers to learn. :sleepy: 

It is for sure welcomed if you can help for the supports or fork your own clients.
