### ISSUE TITLE
Bullet list centered after :frag

### ISSUE THREAD

**Issue by keithmantell** [yjwen/org-reveal#180]
Hi,
If I use this
- Proposal
  #+ATTR_REVEAL: :frag (appear)
  - Focus on automation activities

then the bullet points are centered rather than left justified.  How can I avoid this?

Thx

**Comment by yjwen** [comment]
Hi, 

  I didn't see the bullets are centered with the following file (similar with yours, but with proper #+ATTR_REVEAL: position.
```org
* Slide 1
  #+ATTR_REVEAL: :frag (appear)
  * Proposal
    * Focus on automation activities
```

Could you please retry with the above contents?

Regards,
Yujie

**Comment by keithmantell** [comment]
Hi Yujie,

Thanks for this.  So, first, the format I put in this forum did not reflect what I used.

Your example still centres for me so I must have something different in my setup.  Is reveal_center true by default.

**Comment by yjwen** [comment]
Hi, Keith,

  Can you please give me a sample Org file and the generated HTML? If it is not too late...

Regards,
Yujie
