### ISSUE TITLE
blank box current/next slide on speaker notes

### ISSUE THREAD

**Issue by nasa9084** [yjwen/org-reveal#184]
When I opened  speaker notes window with CDN for #+REVEAL_ROOT, current and next slide box is blank.
I set #+REVEAL_ROOT as explained in README: i.e.

```
#+REVEAL_ROOT: http://cdn.jsdelivr.net/reveal.js/3.0.0/
```

Is this a bug or reveal.js' feature?

Thank you for being patient with my English.

**Comment by yjwen** [comment]
Hello, at first, sorry for a late reply.

It seems a bug of Reveal.js of displaying speaker notes by remote Reveal.js server. Can you please try to install a local one and export the HTML to the local Reveal.js root directory?

**Comment by nasa9084** [comment]
Thank you for your reply.

I have tried to install reveal.js to local, but when I made new project, it seems to troublesome to copy reveal.js to project dir or to think path to reveal.js root dir.
It may be attributed just reveal.js, as I thought.
thanks.
