### ISSUE TITLE
Cope with the change in export block syntax

### ISSUE THREAD

**Issue by zeph1e** [yjwen/org-reveal#185]
Since the version 8.3.2 (403) of org-mode changed the syntax to exporting block, :export-block keyword of (org-export-define-derived-backend) is gone.  org-reveal initialization fails because org-reveal still uses it to call (org-export-define-derived-backend)

**Comment by yjwen** [comment]
Oops. It is a strange change. It seems even the HTML exporter is not working well. Let me find out how to cope with the change.

To avoid the runtime error, please comment out the `:export_block` line. As a consequence, speaker notes is disabled.

**Comment by zeph1e** [comment]
Thanks for the fix.

**Comment by kaushalmodi** [comment]
Got [this update][1] from Nicolas Goaziou from the org-mode devel list.

http://orgmode.org/cgit.cgi/org-mode.git/commit/?id=74c46ad0067ebf337f74ece4a86973c83adc7afa

[1]: http://thread.gmane.org/gmane.emacs.orgmode/103736/focus=104051
