### ISSUE TITLE
New org syntax for export blocks

### ISSUE THREAD

**Issue by jwhendy** [yjwen/org-reveal#186]
Greetings,

Just a heads up. The newest changes to the org-mode exporter changed the block syntax. It was [announced on the mailing list](http://permalink.gmane.org/gmane.emacs.orgmode/103736) about a week ago and I now get an error with `org-reveal`.

From Nicholas:
> I just finalized the syntax change for export blocks. As a reminder, the new syntax is:
```
  #+BEGIN_EXPORT backend
  ...
  #+END_EXPORT
```
> instead of
```
  #+BEGIN_backend
  ...
  #+END_backend
```

Minimal config:
```
;; set load paths
;; set load dirs and global config options
(add-to-list 'load-path "~/.elisp/org.git/lisp/")
(add-to-list 'load-path "~/.elisp/org.git/contrib/lisp")
(add-to-list 'load-path "~/.elisp/org-reveal/")

(require 'ox-reveal)
(setq org-reveal-root "file:///home/jwhendy/installed/reveal.js")
```

I start emacs with `emacs -Q`, followed by `M-x load-file RET ~/path/to/min-config` and get this in the minibuffer:
```
org-export-define-derived-backend: Unknown keyword: :export-block
```

To be fair, I haven't tried exporting with it at this point but I'm assuming you might have to change something to match the new syntax. This is on `Org-mode version 8.3.2 (release_8.3.2-454-g4b7b20)`.

**Comment by kaushalmodi** [comment]
Looks like the issue is fixed in the master branch: https://github.com/yjwen/org-reveal/issues/185 but the version on Melpa is not updated with that.

**Comment by jwhendy** [comment]
Confirmed fixed -- thanks!
