### ISSUE TITLE
Change 'table of contents'

### ISSUE THREAD

**Issue by hello-code** [yjwen/org-reveal#188]
Is there a way to change `table of contents` ?
For example: change 'table of contents' to 'Hello world'.
Thanks!

**Comment by shackra** [comment]
put in your org-mode file:

```
#+OPTIONS: toc:nil
```

**Comment by yjwen** [comment]
No you can't, unless you modify Org-mode's source code. Please check the document of the const `org-export-dictionary` (c-h v org-export-dictionary).
