### ISSUE TITLE
Adding inline CSS

### ISSUE THREAD

**Issue by novoid** [yjwen/org-reveal#189]
Hi!

Is is possible to squeeze in single CSS statements?

For example, I love the standard themes but I would like to modify the opacity value for "navigate-down enabled" (only). I don't want to lose the ability to use the CSS classes hosted online (via `(setq org-reveal-root "http://cdn.jsdelivr.net/reveal.js/3.0.0/")`) and therefore I just want to add my modifications to the CSS.

**Comment by arademaker** [comment]
related with that, I would like to be able to change the font-size of a particular code block. I tried with ```#+HTML_ATTR``` but it didn't work.

**Comment by yjwen** [comment]
Please write a local CSS to overwrite any style you like, and include that local CSS by `#+REVEAL_EXTRA_CSS: ./your_local.css`.

**Comment by fkgruber** [comment]
Can you add a local CSS to specific slide only?
