### ISSUE TITLE
source code highlighting does not work in reveal export

### ISSUE THREAD

**Issue by fkchang** [yjwen/org-reveal#190]
plain HTML export has syntax highllighting

**Comment by shackra** [comment]
In my case with a source code block (`#+BEGIN_SRC python`) the results is this:

```
<pre><code class="lang- hljs groovy">
<span class="hljs-keyword">import</span> <span class="hljs-keyword">this</span>
</code></pre>
```

**Comment by yjwen** [comment]
The source code highlighting works fine for me.
Could you please send me a sample org and the generated HTML for a check?

**Comment by fkchang** [comment]
@yjwen I figured it out. I did a simple example and it worked, so I went back to the presentation(s) that it was failing on. It was the reveal highlight plugin that was messing it up i.e. I had done this before

```
#+REVEAL_PLUGINS: (highlight markdown notes)
```
but dropping the highlight plugin made the syntax highlighting work. Should that be documented, current readme says to add it

**Comment by yjwen** [comment]
Yes, there are two ways for highlighting. Either using htmlize.el or highlight.js. There is a section talking about highlighting in Readme.org.
It is great the issue has been solved. :)
