### ISSUE TITLE
Omit table of contents

### ISSUE THREAD

**Issue by novoid** [yjwen/org-reveal#191]
Hi!

The ToC slide is almost every time too high to fit on a 1024x768 projector screen and I don't like to have ToC for every presentation.

So: how can I disable the ToC slide?

Alternatively: how am I able to limit heading levels for the ToC so that it holds only, e.g., the top level headings and no sub-headings?

Thanks!

**Comment by yjwen** [comment]
Hi,

  To disable ToC, please add an option `#+OPTIONS: toc:nil`.

  To control the heading level in ToC, please use `#+OPTIONS: toc:n`, where n is the number of levels of heading to be displaced. `#+OPTIONS: toc:2` will export only two levels of headings in ToC.

Regards,
Yujie

**Comment by novoid** [comment]
Thanks!

Short question: when I do `C-h v org-reveal TAB` I see many variables I can modify. Some of the `#+OPTIONS:` variables I don't get there. Why isn't there a 1:1 mapping so that I can set all defaults in my init.el and overwrite with each heading?

Because `toc` is not part of the `org-reveal`-variables and I *need* to add it to each and every heading I want to export with reveal..
