### ISSUE TITLE
editable/runnable code in presentation?

### ISSUE THREAD

**Issue by titaniumbones** [yjwen/org-reveal#192]
Just wondering if anyone has had any luck using the RevealEditor or reveal-repl plugins with org-reveal. I would like to be able to edit javascript source blocks and show the results of the edited code -- am not quite sure how to do that with an org-generated presentation... 

Thanks guys!
m

**Comment by bhugueney** [comment]
Hi !
I'm having some luck with https://github.com/viebel/klipse ( setting REVEAL_POSTAMBLE to configure & load klipse) but I have to then use #+REVEAL_HTML for the editable source code. Integration with babel SRC block would be wonderful !

**Comment by titaniumbones** [comment]
Klipse looks interesting. I would really like to have this feature available and I'd be willing to contribute my meager skills ot making it happen. Do you have any suggestions where to start? Thank you!
Matt

**Comment by titaniumbones** [comment]
Hi @bhuguerney I am getting closer to a usable klipse thanks to @viebel, see https://github.com/hakimel/reveal.js/issues/1735 

I think the plugin should be refined a little to allow some CSS setting when reveal is initialized; after that, I'd like to get org-reveal to allow expernal plugins to be loaded via the `dependencies` mechanism. Would be nice to set this up through variables rather than fussing directly with the postamble, I think.  What are you thoughts?
