### ISSUE TITLE
Automatically generate slide numbers in url (`#/x/x`)

### ISSUE THREAD

**Issue by joonro** [yjwen/org-reveal#196]
When I open `index.html` included in reveal.js, it automatically appends slide numbers in url:

```
file:///C:/Users/joon/git/reveal.js/index.html#/7/1
```

which makes it easy to go to the specific slide - for example, if I'm working on the slide 8/2, and I can refresh browser with url `file:///C:/Users/joon/git/reveal.js/index.html#/7/1` to directly go to that slide. 

I can do this manually (adding `#/7/1` to the url) with the html file rendered by org-reveal, but it would be great if org-reveal automatically generate this.

**Comment by yjwen** [comment]
Please turn on the history plugin by `#+OPTIONS: reveal_history:t`. Then the address of each slide will be displayed in the browser's address bar.
