### ISSUE TITLE
missing documentation for "extra stylesheets" 

### ISSUE THREAD

**Issue by patrickod** [yjwen/org-reveal#197]
The link in the README to the documentation describing using extra stylesheets in presentations is currently broken and there doesn't appear to be a wiki page or other document in the source tree which describes this functionality.

**Comment by yjwen** [comment]
There is a section "Extra Stylesheets" in Readme.org describing the usage of `REVEAL_EXTRA_CSS`. Do you need any other detailed description about the extra stylesheets?

**Comment by patrickod** [comment]
![facepalm-gif-31](https://cloud.githubusercontent.com/assets/84262/14537010/09b21340-022a-11e6-9acc-a18bc7cefe92.gif)
I subsequently found this documentation later but forgot that I'd opened this issue! Going to close it out :)

**Comment by yjwen** [comment]
:) Nice emoji.

2016-04-15 1:17 GMT+08:00 patrickod <notifications@github.com>:
