### ISSUE TITLE
Correctly export emojis

### ISSUE THREAD

**Issue by ggreif** [yjwen/org-reveal#201]
Whe I mention `:turtle: :dash:` in the `.org` document, then these should be exported as emojis. Github's own `.org`-renderer does this.

**Comment by ggreif** [comment]
Maybe ox-reveals doesn't generate the HTML at all? If so, who is doing it?

**Comment by yjwen** [comment]
I think it is github's feature of rendering emojis.
Org-mode doesn't have such feature. Even if you export .org document into plain HTML by Org-mode's builtin HTML exporter, emojis are left there untouched. So does org-reveal, which is derived from the HTML exporter. :thought_balloon:

**Comment by ggreif** [comment]
@yjwen Thanks for your answer! In the meantime I researched a bit and found http://stackoverflow.com/questions/36233605/how-to-customize-org-mode-html-output-to-replace-emojis
