### ISSUE TITLE
reveal_single_file doesn't respect extra CSS

### ISSUE THREAD

**Issue by gentius** [yjwen/org-reveal#202]
The custom CSS file declared in #+REVEAL_EXTRA_CSS is ignored when producing a single file.

#121

**Comment by yjwen** [comment]
Fixed. Please pull the latest master branch.

**Comment by pokyah** [comment]
Hi all ! New to emacs and .org. Your plugin is a true productivity enhancer. I can make everything works like a charm excepted the single file export. I can't get highlight.js and my custom css file to be handled. I've installed ox-reveal and org-mode both from github. What could be wrong ? What info can I provide you to help identify the problem ?
