### ISSUE TITLE
Failed with source code other than haskell

### ISSUE THREAD

**Issue by cryoguy** [yjwen/org-reveal#203]
I am receiving following error when there is any source code other than haskell:  
cond: Wrong type argument: stringp, x1.    I am using the latest version of org-mode with htmlize and org-reveal.   

Any thoughts and help are appreciated.

**Comment by cryoguy** [comment]
The problem went away if I use highlight.js.

**Comment by yjwen** [comment]
Can you export source code with Org-mode's built-in HTML exporter ? (C-c C-e h h)
