### ISSUE TITLE
Skip TOC

### ISSUE THREAD

**Issue by Dietr1ch** [yjwen/org-reveal#204]
Is there a way to make some slides skip the Table of Contents?

I'd like to add a questions and thanks slides at the end. They appear on the ToC and it's really silly to list them :c

**Comment by yjwen** [comment]
I am afraid there is no way from Org-mode itself.

Just checked org-mode's code, all headlines are put to TOC for the plain HTML export, so the same for org-reveal.
The only thing we can do is to limit the headline depth, which does not look like an elegant answer for your question.

But you can add raw HTML to manually slice out an extra slide for thanks. For example:
```org
* Slide 1
  
  The contents.
#+html:</section></section><section><section>
  Thank you all!
```

**Comment by Dietr1ch** [comment]
Oh, I expected org-mode to have that already. It seems like a nice addition and it should be easy to implement, I'll look up into that.

Thanks for answering, it may help other people now. I think I ended up doing a similar approach (hack).
