### ISSUE TITLE
Cannot seem to set reveal_title_slide to a string

### ISSUE THREAD

**Issue by olberger** [yjwen/org-reveal#205]
Hi.

I cannot seem to be able to set  reveal_title_slide to anything else than auto.

Could you provide an example on how to set it to a custom HTML template, like:

`<h1 class="title">%s</h1><h2>whatever<h2><h2 class="author">%a</h2><h2 class="date">%d</h2>`

Thanks in advance.

Best regards,

**Comment by yjwen** [comment]
Just found there was a bug for formatting custom title slide.

To apply a format string for `reveal_title_slide`, please do the following 2 steps:
  1. Pull the latest master branch and compile.
  2. Set the variable `org-reveal-title-slide` to a string value, **with double quotes properly escaped**.

For example
```emacs-lisp
 (setq org-reveal-title-slide "<h1 class=\"title\">%s</h1><h2>whatever<h2><h2 class=\"author\">%a</h2><h2 class=\"date\">%d</h2>")
```
or `M-x set-variable`, input `org-reveal-title-slide`, and then input `"<h1 class=\"title\">%s</h1><h2>whatever<h2><h2 class=\"author\">%a</h2><h2 class=\"date\">%d</h2>"`

**Comment by olberger** [comment]
Thanks, that improves. However, the %s isn't replaced by the document's title, AFAICS. %a works.

I do have a #+TITLE: though :-/
