### ISSUE TITLE
Allow multi-line value for option REVEAL_HEAD_PREAMBLE

### ISSUE THREAD

**Issue by olberger** [yjwen/org-reveal#206]
It seems that it's not possible to do something like:
```
#+REVEAL_HEAD_PREAMBLE: <style type="text/css">
#+REVEAL_HEAD_PREAMBLE:<!--/*--><![CDATA[/*><!--*/
#+REVEAL_HEAD_PREAMBLE: div.figure { float:right; }
#+REVEAL_HEAD_PREAMBLE: /*]]>*/-->
#+REVEAL_HEAD_PREAMBLE: </style>
```

when this is possible with the classical org-mode HTML export headers, to allow customizing the exported HTML.

Would it be possible to adjust this ?

**Comment by yjwen** [comment]
Fixed. Now REVEAL_HEAD_PREAMBLE can have multiple lines, as you have suggested.
