### ISSUE TITLE
D3.js code in slide

### ISSUE THREAD

**Issue by cataclysmic** [yjwen/org-reveal#210]
Hey guys,

great work. A short question. Is there a way to put in the code for a D3.js chart?
I managed to copy it directly into a slide in the output html which works nicely but it would be much more convenient to place it directly into the org-file. It is javascript mixed with css. I tried around with the  REVEAL_HTML keyword but didn't get it to work. Any recommendations?

**Comment by yjwen** [comment]
Just did a quick check of D3.js manual, but got no idea of how to using it, because I am a layman of JS.

If you can give me an example of manually embedding D3.js into org-reveal generated HTML, maybe I can find out how to do it with org-reveal options.

**Comment by bdixon95** [comment]
Was this ever solved? I'd also like to put d3.js code in directly using org-reveal.

**Comment by yjwen** [comment]
There are 3rd party plugin of d3.js for reveal.js. And org-reveal supports to embedded 3rd-party plugin scripts now. Should have a chance to use d3.js now.
