### ISSUE TITLE
Hlevel problem

### ISSUE THREAD

**Issue by wd** [yjwen/org-reveal#212]
From doc, if I define REVEAL_HLEVEL to 2, then heading level less then 2 should arranged horizontally, but it seems not work.

If I define REVEAL_HLEVEL to 0, the all heading level will arranged horizontally. Is there some problem ? Since I see the code about hlevel
```
         (if (<= level hlevel)
             ;; Add an extra "<section>" to group following slides
             ;; into vertical slide group. Transition override
             ;; attributes are attached at this level, too.
             (let ((attrs
                    (org-html--make-attribute-string
                     `(:data-transition ,(org-element-property :REVEAL_DATA_TRANSITION headline)))))
               (if (string= attrs "")
                   "<section>\n"
                 (format "<section %s>\n" attrs))))
```
If there should be '>=' here ?

**Comment by yjwen** [comment]
Hi,

  The `REVEAL_HLEVEL` is working correctly.

  Please try with the following Org file:
```
#+REVEAL_HLEVEL: 2

* Top-level Slide
  
  The contents.

** Sub-Slide
   
   The contents.

*** Subsub-Slide
    The contents.
```
The "Top-level slide" and "Sub-slide" is assigned horizontally, and the "Subsub-slide" is a vertical one of "Sub-slide".

Regards,
Yujie

**Comment by wd** [comment]
Thank you for your reply, but sorry, I can't reproduce the problem ... I don't know why, it's working now.
