### ISSUE TITLE
still no single-page export with non-local images?

### ISSUE THREAD

**Issue by titaniumbones** [yjwen/org-reveal#213]
Am I right that it's still not possible to export a buffer with `https://` links to images? The following test slide gives me an "unable to embed" error:
```
*** Deep Time
- "Uniformitarianism"
- accretion of tiny changes
- Galapagos: terrestrial change at work
http://upmagazine-tap.com/wp-content/uploads/2011/12/Gal%C3%A1pagos-lava-1-sullivan-bay-700x525.jpg
```
Can I do anything to get around this? Thank you!

**Comment by yjwen** [comment]
Yes. It is not possible to embed online images yet.

Let me think of simply leaving the links to image as it is when exporting to single files, because those images are online. It will be redundant to pack them into the HTML if those images are accessible by anyone.

**Comment by titaniumbones** [comment]
Yes, that seems like a good choice. Right now the export fails if the file or subtree contains an http(s):// link.  It would be nice to be able to complete thee export. I think modifying the test for "want-embed-image" might be the right place to do it but I am not sure.
