### ISSUE TITLE
why i can not set slide background color or image?

### ISSUE THREAD

**Issue by rayjun** [yjwen/org-reveal#215]
`* Set background color   
            :PROPERTIES:   
            :reveal_background: #123456  
            :END:`

**Comment by yjwen** [comment]
Is it the exact file content you are exporting? All in the same line?

If so, could you please try with the proper indention and newlines, like below. It is required by Org-mode syntax.
```
* Set background color       
  :PROPERTIES:
  :reveal_background: #123456
  :END:
```
