### ISSUE TITLE
global frag lists

### ISSUE THREAD

**Issue by mclearc** [yjwen/org-reveal#216]
Apologies if this issue is already addressed somewhere. I would like all lists (ordered and unordered) to be fragmented. I've set `org-reveal-default-frag-style "roll-in"` but I see no way to set fragments as true globally (though this is an option for reveal.js). Am I missing something? If this has to be done with local css could you advise on what this would be? Thanks!

**Comment by yjwen** [comment]
Just found the default fragment style is missed during org-reveal's exports. Fixed it.

To use the default fragment style, you need to add `#+ATTR_REVEAL: :frag t` to any element you want to apply fragment on. The `org-reveal-default-frag-style` is merely a replacement for the `t` in `#+ATTR_REVEAL: :frag t`. There is no way to make all elements to be fragmented in org-reveal.

I didn't find from reveal.js documents the way to make global fragmenting. Could you please point me to the right place about how to do that?

**Comment by mclearc** [comment]
In the [configuration section](https://github.com/hakimel/reveal.js#configuration) there is this entry

`// Turns fragments on and off globally` 
`    fragments: true,`

I took that to be the global switch. Perhaps that is not correct?

**Comment by yjwen** [comment]
No, `fragments: true,` means to allow fragments globally, but not to turn it on for every element.
