### ISSUE TITLE
Org-reveal presentation links open in the same tab

### ISSUE THREAD

**Issue by jgkamat** [yjwen/org-reveal#219]
I think that by default, `org-reveal` hyperlinks should open in a new tab (to preseve the presentation). Would it be possible to either make an option for this, or make it the default, or both?

For example:
`[[https://www.google.com][google]]` opens in the same tab as the presentation when left clicking.

**Comment by yjwen** [comment]
It is determined by the regular HTML exporter, ox-html, from which org-reveal is derived, that links are opened in the same page. To have alternative new-page-links will need to overwrite ox-html's code a lot.

Besides, almost all browsers support to open any links in new tab or page, usually by pressing shift/ctrl and then click the link, or by simply clicking the link by mouse middle button.

So it seems relying on browser is an easy way to control links. I'd prefer not bother to implement the function in org-reveal. :smiley:
