### ISSUE TITLE
Speaker notes doesn't seem to work

### ISSUE THREAD

**Issue by jasonblewis** [yjwen/org-reveal#22]
Hi,

When I press s to bring up speaker notes as per the Readme.org file, chrome opens a new window with two black boxes, i presume one for the speaker notes and one for upcoming slide, however they just remain black, and don't appear to receive any content when i progress through the reaval.js slideshow.

Steps to reproduce. Export this project's Readme.org to a reveal.js presentation

Press S to launch the speaker notes window. Notice how it shows no content.

**Comment by psifertex** [comment]
Should this issue be closed? Speaker notes work fine for me. Well, they did a few weeks ago, assuming #108 is resolved.

**Comment by yjwen** [comment]
Yes, I think this one can be closed. It seems Reveal.js has updated to allow speaker notes outside of its directory.

Thanks for the findings.
