### ISSUE TITLE
Use more than one stylesheet

### ISSUE THREAD

**Issue by Titan-C** [yjwen/org-reveal#221]
I'm preparing a presentation and I would like to use the font-awesome stylesheet from theiry CDN but aside of that I have my own stylesheet for my presentation. 
The `#+REVEAL_EXTRA_CSS: ` option only takes one string and can't be repeated or described with a list
Now I edit the final html by hand but it would be nice to have a solution to this

**Comment by yjwen** [comment]
Fixed. Now you can use multiple `#+REVEAL_EXTRA_CSS` statements. Please pull the latest master branch.
