### ISSUE TITLE
Improve documentation of ATTR_REVEAL :frag for lists

### ISSUE THREAD

**Issue by olberger** [yjwen/org-reveal#224]
Reading the docs and the Readme.org docs, I tried to get fragmented lists with no luck with something like (tested on stable branch as of 6ee0e547ddf1596496e558d1b7ab78f315f980ec):
```
* slide 1

#+ATTR_REVEAL: :frag roll-in
- test
- another list
- and another again

* slide 2
* slide 3
```
It seems that using `#+ATTR_REVEAL: :frag (roll-in)` instead solves the issue.

Is it a bug or documentation understanding issue ?

Thanks in advance.

P.S. thks to @zamansky for the hint in his tutorial: http://cestlaz.github.io/posts/using-emacs-11-reveal/#.V7RKDrPaLRY

**Comment by yjwen** [comment]
If you write `#+ATTR_REVEAL: :frag frag-style` without parenthesis enclosing `frag-style`, that means to fragment all list items *as a whole*.

If `frag-style` is enclosed with parenthesis, like `#+ATTR_REVEAL: :frag (frag-style)`, that means to apply the fragment style to each item of the list. With parenthesis enclosing, you can even assign different fragment style to different list items.

Section [List fragments](https://github.com/yjwen/org-reveal#list-fragments) of Readme.org has the details.
