### ISSUE TITLE
color and align a sentence?

### ISSUE THREAD

**Issue by zeltak** [yjwen/org-reveal#229]
Hi

i have been using aligment and coloring via html attributes the last few months. today i was wondering if its possible to have a sentence both aligned and colored. i tried this

`#+ATTR_HTML: :style  text-align:left color:red `

yet this seems to break both color and alignment.

any clue?

**Comment by yjwen** [comment]
A semicolon is necessary to separate styles. Please use:
```
  #+ATTR_HTML: :style text-align:left; color:red
```
