### ISSUE TITLE
Option for Roll in line highlight in source code

### ISSUE THREAD

**Issue by nasseralkmim** [yjwen/org-reveal#230]
Hi

It would be great to have an option to highlight each code line in a source block, like "reveal code focus".

What you guys think?

**Comment by yjwen** [comment]
It looks necessary to include the reveal code focus plugin, and add extra tags after the code block.

It will require complicated changes for the specific plugin. I am sorry I don't have enough time to implement such a feature.

**Comment by mboes** [comment]
This would be very useful for me too. Any chance this issue could be left open in case someone else might try implementing it?

Meanwhile, is there any workaround one could use?

**Comment by nasseralkmim** [comment]
@mboes My alternative approach was to use org-tree-slide for live coding when presenting.
