### ISSUE TITLE
html attributes for figure divs & captions?

### ISSUE THREAD

**Issue by titaniumbones** [yjwen/org-reveal#231]
Is it possible to assign an html attribute - -especially a class -- to the caption on an image? I have a class "paired" that floats an image left and sets max-width to 45%. This works with an image, but if I add a caption using
#+ATTR_HTML: :class paired
#+CAPTION: Mongol Empire 
[[file:../Images/Silk_route.jpg]]

the caption (and the enclosing "figure" div) do not get the "paired" class -- only the image. Can I change this? Thanks!

**Comment by yjwen** [comment]
The HTML attributes are determined by the ox-html exporter. It looks ox-html doesn't support such requirements. So neither can ox-reveal.

**Comment by titaniumbones** [comment]
A workaround is to surround the image with:

```
#+BEGIN_classname

#+END_classname
```
This will create an enclosing div with class="classname" around the figure.  It's not aesthetically pleasing, but it allows the figure as a whole to be addressed by CSS.
