### ISSUE TITLE
Multiple ATTR_REVEAL: : frag  style

### ISSUE THREAD

**Issue by idd79** [yjwen/org-reveal#232]
Hi,

I'm wondering if it is possible to apply more than one style to a list at the same time. For example, something like:

```org
#+ATTR_REVEAL: :frag (roll-in highlight-red)
- Both roll-in and highlight-red
```

So the bullet point will roll-in and be highlighted red at the same time.

I tried to achieve this without luck.

Thanks in advance for any suggestions.

**Comment by yjwen** [comment]
Reveal.js doesn't support multiple fragments at the same time. Multiple fragments are illustrated serially, one by each click. Please see https://github.com/hakimel/reveal.js#fragments.

So neither can org-reveal.

**Comment by idd79** [comment]
Thanks for your reply. I understand that reveal.js does not support multiple fragments but only sequentially or serially (get one effect in the first step, and another effect in second step). This is good enough for me, however I haven't been able to get this sequential effects, for example, if I add:

```
#+ATTR_REVEAL: :frag (roll-in)
#+ATTR_REVEAL: :frag (highlight-red)
- List item
```

I only get the last effect, not the first one.
