### ISSUE TITLE
How to ensure images fit on screen?

### ISSUE THREAD

**Issue by arvchi** [yjwen/org-reveal#235]
I am preparing a presentation with a couple of images, and want to make sure that they will fit on the screen, regardless of type of screen or projector. Last time I presented, some of my images were cut (I don't understand why), even though they looked perfect when tested at home.

Currently I am using #+ATTR_HTML: :height x%, :width y% to scale manually, but as I said, the images looked great on my screen but were cut on the projector.

**Comment by blueberry** [comment]
I would also like to know that.

**Comment by logc** [comment]
I have been struggling with this for a couple of hours, until I finally found [this doc](https://github.com/hakimel/reveal.js/tree/dev#stretching-elements)

As far as I understand org-reveal, you can use that `class` by inserting raw HTML in your org file:

```
#+REVEAL_HTML: <img class="stretch" src="img/whatever.jpg">
```
