### ISSUE TITLE
Problem when updating tags in an org file

### ISSUE THREAD

**Issue by renatocan** [yjwen/org-reveal#236]
When org-reveal is installed, everytime the list of tags is updated in an org section, it disappears from the screen, although it is preserved in the file. It is possible to recover the list of tags folding and unfolding the section's parent section, thought. I could not observe the issue when org-reveal was uninstalled.

I've noticed this issue after the last update of org-mode and org-reveal I've received, using el-get, on oct 14, 2016.

**Comment by yjwen** [comment]
Closint the issue for now for no tag folding or property folding is observed by the latest org-reveal.

Please feel free to reopen it if the issue still exists.
