### ISSUE TITLE
open browser to the slide currently being edited

### ISSUE THREAD

**Issue by jasonblewis** [yjwen/org-reveal#24]
Hi Yujie,

This is a feature request. I'm not sure if its even possible.

When you export, would there be some way to open the browser to the currently edited slide? using the anchor maybe?

**Comment by yjwen** [comment]
Hi,

  At first, sorry for such a late update. I had no idea how to implement the feature then. But as my experience on Emacs lisp grows while I maintain the project, I came to sort of the solution for the feature request.

  I presume the feature request is for a quick preview of what is been edited currently, so I add another menu entry "C-c C-e R S" to export only current sub-tree. Please pull the latest master branch to have a try. I wish it could meet your requirement :)

**Comment by joonro** [comment]
A manual way to do this is putting `#/horizontal section number/vertical slide number' like the following:

```
file:///C:/Users/joon/git/reveal.js/index.html#/10/2
```

That will open the specific slide in your browser.

**Comment by joonro** [comment]
Related to this, I find that the `index.html` from `reveal.js` shows and automatically updates those slide numbers (`#/10/2`) in the browser's address bar, but the slides generated from org reveal does not. Is there an option for this or it is not implemented?

**Comment by fleimgruber** [comment]
I was wondering about the same thing. It would be great to have those `/#/x/y` updated when navigating / jumping through the slideshow. Any updates on this? Did you manage to find a way?

**Comment by fleimgruber** [comment]
@joonro the relevant option is `reveal_history`.
