### ISSUE TITLE
Feature Request: [ ] to checkboxes

### ISSUE THREAD

**Issue by cataclysmic** [yjwen/org-reveal#241]
This would be a neat little feature.
When there is a list with checkboxes in the org-file that they'd be converted to `<input type="checkbox">`.

I use these currently when I want to structure a class and the necessary Steps from A to B.

**Comment by yjwen** [comment]
There is support to export checkboxes to HTML `<input type="checkbox">`. Please set variable `org-html-checkbox-type` to `html`. It will enable the Orgmode's HTML export to use the HTML checkbox, so will org-reveal.

However, the checkbox's selection status cannot be rendered properly in Reveal.js, unless the whole list is wrapped with `<form>` and `</form>`.

The patch is to wrap the list with `<form>` when necessary.

**Comment by cataclysmic** [comment]
Ah, thank you.
I wasn't aware of this feature. Thank you.
No form-patch needed. I only need it for a todo list.

Great work. Thank you again.




Felix Albrecht
Bonn University
Institute for Applied Microeconomics
Postal Address: Adenauerallee 24-42
53113 Bonn
Tel. 0228-73 3918
Fax. 0228-73 9239

You think he can pull off those tight pants?
