### ISSUE TITLE
cant change aliment to whole header

### ISSUE THREAD

**Issue by zeltak** [yjwen/org-reveal#242]
Hi all. so i have been using org-reveal for several months and its amazing!. 
i have been able to successfully left align a whole org file and also can can left align specific lines with `#+ATTR_HTML: :style text-align:center`

one think i cant get to work is change change aliment to whole header. i have followed the example of this (https://github.com/yjwen/org-reveal/issues/172#issuecomment-164233626) but with no success.

my current css file looks like this 

```
.reveal p {
    text-align: left;
}

#slide_1 {
    text-align: center;
}

```

and an example header looks like this

```
** * admin
:PROPERTIES:
:CUSTOM_ID: slide_1
:END:   
#+ATTR_HTML: :style text-align:center 
ADMIN stuff

1.

2.
```

i have all my slides left aligned yet cant get specific slides to center align

any idea?

best

Z

**Comment by rafael-nalin** [comment]
zeltak, I'm also having trouble with alignments...

I add the following in my reveal.css in order to justify all the slides:

```
.reveal p {
	margin-bottom: 10px;
	line-height: 1.2em;
	text-align: justify;
}
```

But sometimes I would like to center some Latex formula, but when I do this, the text below the formula also gets centered, even if I use `#+ATTR_HTML: :style text-align:justify` before the paragraph.

How can I fix this? I will be very thankful if someone can help.
Thank you in advance guys!
Rafael

**Comment by yjwen** [comment]
@zeltak 
To align all headers, please change the alignment for `<h2>` element. For example
```css
.reveal h2 {text-align: right;}
```

**Comment by zeltak** [comment]
thx yjwen

im actually looking into aligning not a specific level but a specific header, so that all headers are centered but header "example 1" is left aligned. from what i understand from the example above all h2 headers will be right aligned?

best

Z

**Comment by yjwen** [comment]
For aligning specific header, then #172's solution should work.
```
#+REVEAL_EXTRA_CSS: ./tmp.css
* slide 1
  :PROPERTIES:
  :CUSTOM_ID: slide_1
  :END:

  Slide 1
* slide 2
  Some words.
```
with
```css
#slide_1 {text-align:right;}
```

The files above works for me.

**Comment by zeltak** [comment]
thx i did try that initially but couldnt get it to work. to clarify: slide 1 is the headers name? and then if so i add another section to my local.css so it looks like this:

```
.reveal p {
    margin-bottom: 1px;
    margin-top: 1px;
    margin-left: 1px;
    margin-right: 1px;
    line-height: 1.2em;
    text-align: center;
}

#slide_1 {text-align:left;}
```

**Comment by yjwen** [comment]
@rafael-nalin `#+ATTR_HTML: :style text-align:center` works for me. For example:
```
#+REVEAL_EXTRA_CSS: ./tmp.css

* slide 1
  
  Justified

  #+ATTR_HTML: :style text-align:center
  Center aligned.
  #+ATTR_HTML: :style text-align:center
  ${n! \over k!(n-k)!} = {n \choose k}$

  Justified again.
```
with
```css
.reveal p {
    margin-bottom: 10px;
    line-height: 1.2em;
    text-align: justify;
}
```

**Comment by yjwen** [comment]
@zeltak Your css works for my local test. Could you please show me both your .org and .css?

**Comment by zeltak** [comment]
sure , here is an example org file, a css file and a org template file i source (that sources the css file)


[ctest.zip](https://github.com/yjwen/org-reveal/files/561227/ctest.zip)


so if this work for *each* header i need to define a separate css entry? there is no way to use the headers properties for this?

**Comment by rafael-nalin** [comment]
@yjwen 

Thank you for your reply.
Yes, it works, but not if I write as a new topic in the same slide. As follow:

  **
  #+ATTR_HTML: :style text-align:center
  ${n! \over k!(n-k)!} = {n \choose k}$

 - New topic... **

Any idea? 
Thank you very much.

**Comment by rafael-nalin** [comment]
@yjwen 

Thank you for your reply.
Yes, it works, but not if I write as a new topic in the same slide. As follow:
```

#+ATTR_HTML: :style text-align:center
${n! \over k!(n-k)!} = {n \choose k}$

- New topic...
```

Any idea? 
Thank you very much.

**Comment by yjwen** [comment]
@zeltak 

By reading your ctest.org and justify.css, I suppose you want the heading "data types" to be left-aligned. To do so, you will need to:
1. Add justify.css as the extra style sheet to your ctest.org,
2. Give the heading "data types" the specific ID "data_types",
3. In justify.css, align `#data_types` to left.

You've done 3, but missed 1 and 2.

```
#+REVEAL_EXTRA_CSS: ./justify.css
* GIS Refresh
   ...
** What is [are] data?
   ...
** data types
   :PROPERTIES:
   :CUSTOM_ID: data_types
   :END:
   ...
```

**Comment by yjwen** [comment]
@rafael-nalin It is because `- New topic` is rendered into an unordered list `<ul>`. To make `<ul>` left-aligned, could you please try to add the following into your .css file.
```css
.reveal ul {
    text-align: justify;
    display: block;
}
```

**Comment by zeltak** [comment]
hmmm thx @yjwen .

im still at loss. i followed exactly what you instructed and i still dont get the slide left aligned, but maybe im missing something. attached is an screenshot of the current data_types slide

![odlk](https://cloud.githubusercontent.com/assets/498410/19996224/c24a5e94-a266-11e6-8cb4-6f5da6732f7a.png)

im also attaching again my ctest.org file and local css file (note i added the  the specific ID "data_types" as you requested)

Finally, do you really have to define in the css file a separate entry  for *each* header? i have slides with 300 headers where i want some to be left aligned and some to be centered. is it OK with you to open a Request ticket for a better way to define alignment per header within org (org-reveal)?

thx so much for all your help (and work!), this totally changed my whole academic workflow :)

Z
[ctest2.zip](https://github.com/yjwen/org-reveal/files/570733/ctest2.zip)

**Comment by rafael-nalin** [comment]
@yjwen ,
It worked perfectly! Really thank you for your help.
Regards,
Rafael

**Comment by yjwen** [comment]
@zeltak In the screenshot you attached, the heading has been left-aligned. 

Do you mean to left-align all the content of a specific slide? I am afraid there is no easy way to do so.

You don't need to define separate entry for each header. Using regular expression selector can do so for you. 

An example org file is:
```org
#+REVEAL_EXTRA_CSS: ./tmp.css
* slide 1
  :PROPERTIES:
  :CUSTOM_ID: right_slide_1
  :END:

  This is slide 1

* slide 2

  This is slide 2

* slide 3
  :PROPERTIES:
  :CUSTOM_ID: right_slide_3
  :END:

  This is slide 3
```
Slide 1 and 3 are given `custom id` that starts from "right_slide". Then you can select slide 1 and 3 in css by:
```css
.reveal h2[id^="right_slide"] {
    text-align: right;
}

```

**Comment by zeltak** [comment]
thx for the answer @yjwen 

yes i meant left align the entire text of the body, but i understand there is no way to do so?

thx for the regex tip, thats very helpful

thx again!

Z
