### ISSUE TITLE
Support of Org is 9.0? e.g. #TITLE missing?

### ISSUE THREAD

**Issue by sebhahn** [yjwen/org-reveal#245]
Any chance to see if org-reveal fully supports Org 9.0?

I'm just testing it but e.g. I don't see `#TITLE`, `#AUTHOR` or `#EMAIL` on my presentation?

**Comment by yjwen** [comment]
It should be `#+TITLE`, `#+AUTHOR` and `#+EMAIL`.
org-reveal works well with those tokens in Org-mode 9.0.

**Comment by sebhahn** [comment]
Yes, sorry. The problem was related to these issues here #209 and #115.
