### ISSUE TITLE
PSA :) for org-reveal users..easy colors everywhere :D

### ISSUE THREAD

**Issue by zeltak** [yjwen/org-reveal#247]
Hi all!

i just wanted to share this:

http://kitchingroup.cheme.cmu.edu/blog/2016/11/08/New-color-link-in-org-9-0-using-font-lock-to-color-the-text/

in short using the new org 9.0 features one can easily add colors to headers, lines ,words etc with the new color: link types (the code is at the site to add the color: link type)

it works fantastically when exporting files and provides a great and easy way to add colors to you org-reveal slides!

thx

Z

**Comment by pseudomyne** [comment]
See also (appeared simplier to me)  : 
https://stackoverflow.com/questions/45580169/changing-color-of-text-in-html-export-from-org-mode

**Comment by zeltak** [comment]
awesome thx so much for the tip :)
