### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by lbrayner** [yjwen/org-reveal#248]
Thank you for org-reveal -- it changed my life.

Not implemented in the Reveal.js backend are footnotes. There is, however, ongoing discussion in the asciidoctor-reveal.js community about how to implement them: whether to put them at the bottom of the slide or in a separate slide.  org-reveal seems to generate <sup> tags for them, which look good enough, but the actual notes get lost.

**Comment by yjwen** [comment]
Actually org-reveal doesn't recognize footnotes. The footnotes are simply ignored. I don't have a plan to implement footnotes yet.

**Comment by doolio** [comment]
Add the following to your local.css file or whatever you call it:

```
.reveal .slides .slide-footer {
    font-size: 16px;
    position: fixed;
    bottom: 0;
    left:0;
}
```
Then include the following somewhere in your org file:

```
#+REVEAL_EXTRA_CSS: ./local.css
#+REVEAL_SLIDE_FOOTER: Copyright (C) 2018 lbrayner
```
