### ISSUE TITLE
Consistent slide IDs

### ISSUE THREAD

**Issue by skomanduri** [yjwen/org-reveal#249]
Every time I export to HTML, slide anchors like `#/slide-org44641d4` are generated.  These are regenerated on every export.  When I change something on a slide and rebuild, I start over at the beginning of the presentation.

Is there a way to have these IDs be simple autoincrement IDs or a slide number so I don't keep losing my place in the presentation?

**Comment by geeklhem** [comment]
I agree that it would be nice, but it is not very robust to slide shuffling. The way I do it is to give each slide I need to refer to a custom ID. 

You can use the[ CUSTOM_ID property](https://github.com/yjwen/org-reveal/blob/8f7cf6c3086c82cb9331397abb7c7417949225c9/ox-reveal.el#L400) to overwrite the the anchor.

Example: 

```
* My Slide
:PROPERTIES:
:CUSTOM_ID: my_custom_id
:END:
    
Hello World
 ```

It will give `id="slide-my_custom_id"`

**Comment by yjwen** [comment]
If you want to review the display of the current slide you are working on, you can export the sub-tree by `C-c C-e R S`.

**Comment by skomanduri** [comment]
> If you want to review the display of the current slide you are working on, you can export the sub-tree by C-c C-e R S.

This and the fact that you can use `C-u C-c C-e` to reexport with the last set of settings makes things fairly easy.  I'll try that out and see how it goes.

**Comment by yjwen** [comment]
Fixed by https://github.com/yjwen/org-reveal/commit/6052357f26d8e8fff09da17bd6f998ab71c41b64
