### ISSUE TITLE
Multiple #+REVEAL_EXTRA_CSS files

### ISSUE THREAD

**Issue by fleimgruber** [yjwen/org-reveal#250]
I installed `fontawesome` and would like to be able to specify e.g.
```
#+REVEAL_EXTRA_CSS: ../../reveal.js/css/font-awesome.css
#+REVEAL_EXTRA_CSS: ./mystyle.css
```
to have multiple css files included (i.e. one for fonts and one for alignment).  Maybe even
```
#+REVEAL_EXTRA_CSS: ../../reveal.js/css/font-awesome.css ./mystyle.css
```
What do you think?

**Comment by yjwen** [comment]
The master branch has supported multiple CSS files. I just merged master into stable, so the MELPA ox-reveal can support it too. Please wait for MELPA's update, or you can use the master branch's code directly.

**Comment by fleimgruber** [comment]
Well, this is embarrassing.  A basic research would have revealed(!) #221 - even the motivation was the same... thanks for the pointer, will wait for MELPA propagation.
