### ISSUE TITLE
similar "reveal_single_file:t" way to export to html file (not a reveal slide)  ?

### ISSUE THREAD

**Issue by zeltak** [yjwen/org-reveal#252]
Hi

this is only a bit related to org-reveal :) i use the option reveal_single_file:t alot since its an easy way for me to pass along the slides to my students. i also in the same org buffer which i create the slide have homework assignment for the students which i export to simple html. the thing is that i cant find a way to create a simple self contained html file for the html HW file as the nice `reveal_single_file:t` options does for an reveal html slideshow

anyone knows how this can be done for non slides html?

best

Z

**Comment by yjwen** [comment]
It seems ox-html doesn't support to export into single file.

One trick is to set `#+REVEAL_ROOT` to a non-existing location and export to reveal slides.

Then, since no revea.js is found, the page is displayed as plain HTML, if you don't mind...

**Comment by zeltak** [comment]
thx

that didnt work for me for some reason

i have this in my init

```
(setq org-reveal-root  "file:///home/zeltak/apps/reveal.js") 
```

i tried adding the something like this in a specific org buffer

```
#+REVEAL_ROOT /home/zeltak/ZH_tmp/
```

where its a temp location yet every time i export it seems it creates a reveal slideshow html. am i doing it wrong?

thx

Z

**Comment by yjwen** [comment]
`#+REVEAL_ROOT: /home/zeltak/ZH_tmp/`
Missed a colon after `REVEAL_ROOT`?

**Comment by zeltak** [comment]
thx! yeah that was indeed missing :) now it does export to plain html yet the images are not there 

this is a example file and im also attaching the output html file
[example.html.zip](https://github.com/yjwen/org-reveal/files/638523/example.html.zip)



```
#+REVEAL_ROOT: /home/zeltak/ZH_tmp/
#+OPTIONS: reveal_single_file:t


#+DOWNLOADED: /tmp/screenshot.png @ 2016-09-16 16:26:44
#+attr_html: :width 1000px
 [[~/org/attach/bgu/courses/BGUC001.R.Base/images/screenshot_2016-09-16_16:26:44.png]]


* test 1
[[/home/zeltak/ZH_tmp/tools.GIF]]
* t4 
* 4
* 3
```

i assume the images should also appear in the vanilla html output?

thx

Z

**Comment by yjwen** [comment]
OK, I tested exporting with a fake reveal.js root. ox-reveal simply failed because it cannot find the necessary .css and .js to read. Giving a correct reveal.js root will let all the reveal.js files to be included into the .html, so the .html is displayed in slides.

Fake reveal.js is not a good idea.
