### ISSUE TITLE
List of external plugins?

### ISSUE THREAD

**Issue by titaniumbones** [yjwen/org-reveal#254]
Can we add a new defcustom to allow loading of third-party reveal.js plugins? say `:reveal-external-plugins`, and then load them if requested? The variable could be an alist or plist of the form:
```emacs-lisp
(klipse .  (format " { src: %splugin/klipse/klipse-reveal.js}" root-path")
```
or something similar, and the code for loading it could be added to `org-reveal-scripts`

I can try to implement if you think it's a good idea.  Seems cleaner than using the POSTAMBLE variable.

**Comment by titaniumbones** [comment]
I've submitted a patch in #256 that adds preliminary support for this feature.  If you like it, I'll add documentation and try to figure out how to support single-file output.

**Comment by yjwen** [comment]
`#+REVEAL_EXTERNAL_PLUGINS:` is added.  Specify only the code for enabling plugins by that opional line. No plugin name is necessary.

**Comment by ertwro** [comment]
@yjwen I take it this should be quite straight forward but I can't make it work. This is what I'm doing:

my root
```
#+REVEAL_ROOT: https://cdn.jsdelivr.net/gh/ertwro/githubppt@3861b9f1d832431bf3fda4e85daaa8c158efbcb9/reveal.js
```
What I've tried unsuccessfully:
```
#+REVEAL_EXTERNAL_PLUGINS: "{src: '%splugin'}"
#+REVEAL_PLUGINS: (markdown notes zoom menu)
```

```
#+REVEAL_EXTERNAL_PLUGINS: "{src: '%splugin/menu/menu.js'}"
#+REVEAL_PLUGINS: (markdown notes zoom)
```

```
#+REVEAL_EXTERNAL_PLUGINS: "{src: '%splugin/menu/menu.js'}"
#+REVEAL_PLUGINS: (markdown notes zoom menu)
```

```
#+REVEAL_EXTERNAL_PLUGINS: '%splugin/menu/menu.js'
#+REVEAL_PLUGINS: (markdown notes zoom)
```

With a local reveal.js folder equally unsuccessful. What am I doing wrong?

**Comment by yjwen** [comment]
Here is my org file using menu.js.
```
#+REVEAL_EXTERNAL_PLUGINS: {src: '%splugin/menu/menu.js'}
* Heading 1
```
The menu showed up successfully.

**Comment by cataclysmic** [comment]
I have the same issue. Trying to add the anything plugins.

Adding them via `#+REVEAL_EXTERNAL_PLUGINS:` does not work.

It produces this:  
`dependencies: [
{src: "file:///relative_path/reveal.js/plugin/animate/plugin.js"},
{src: "file:///relative_path/reveal.js/plugin/anything/plugin.js"},
{src: "file:///relative_path/reveal.js/plugin/chalkboard/plugin.js"},
{src: "file:///relative_path/reveal.js/plugin/chart/plugin.js"},
{src: "file:///relative_path/reveal.js/plugin/customcontrols/plugin.js"}]
});
`

However they need to be loaded like:

`
<script src="file:///relative_path/reveal.js/plugin/animate/plugin.js"></script>
<script src="file:///relative_path/reveal.js/plugin/anything/plugin.js"></script>
<script src="file:///relative_path/reveal.js/plugin/chalkboard/plugin.js"></script>
<script src="file:///relative_path/reveal.js/plugin/chart/plugin.js"></script>
<script src="file:///relative_path/reveal.js/plugin/customcontrols/plugin.js"></script>


<script>
// Full list of configuration options available here:
// https://github.com/hakimel/reveal.js#configuration
Reveal.initialize({
plugins: [RevealMarkdown,RevealZoom,RevealNotes,RevealAnimate,RevealAnything,RevealChalkboard,RevealChart,RevealCustomcontrols],
`
