### ISSUE TITLE
face-attribute: Invalid face: font-lock-warning

### ISSUE THREAD

**Issue by jasonblewis** [yjwen/org-reveal#26]
When I try and export the following fragment with org-reveal i get this error:

face-attribute: Invalid face: font-lock-warning

https://gist.github.com/jasonblewis/7017451

it seems to be the double \ at the end of line 4 causing the problem

**Comment by vonpupp** [comment]
I had a similar problem: Invalid face: font-lock-keyword.

I was testing with the `readme.org` file form the repo itself. I am using spacemacs and I installed via the git repo.

For the sake of completion of this answer, I solved by replacing `#+BEGIN_SRC org` blocks with `#+BEGIN_SRC` blocks (removing `org`).

I hope it helps in case someone else stumbles with this.
