### ISSUE TITLE
Can't export with Emacs 25.1

### ISSUE THREAD

**Issue by lturpinat** [yjwen/org-reveal#260]
Hi,
I cannot export to reveal.js HTML presentation with emacs 25.1, here is the error message : 

> concat: Wrong number of arguments: #[(checkbox) "ÁÂ\"	ÃÁÄ\"ÅÁÆ\"ÇÈ" [checkbox eql on "<code>[X]</code>" off "<code>[&#xa0;]</code>" trans "<code>[-]</code>" ""] 3 ("/usr/share/emacs/25.1/lisp/org/ox-html.elc" . 80513)], 2

Some characters aren't displayed, here is a version on pastebin : http://pastebin.com/cKwYJAbr

**Comment by joonro** [comment]
I'm not sure if this would be relevant, but if the problem started after updating, you might want to try reinstalling orgmode cleanly following http://emacs.stackexchange.com/questions/14763/exporting-org-file-breaks-when-upgrading-to-orgmode-8-3/16616#16616.

**Comment by lturpinat** [comment]
It exports correctly with other formats (like LaTeX), it only fails with reveal.js...

**Comment by tallmtt** [comment]
Are there any updates on this?

I have the same issue and really want to use this project.

Emacs version: GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-11-15
Windows: 10

**Comment by lturpinat** [comment]
@tallmtt  Personnally, I still got the same issue...

**Comment by whatacold** [comment]
Hi,
I have the exact problem with emacs 25.3.1 and built-in org mode 8.2.10, and it disappeared after I upgrading org mode to the recent stable version 9.1.4. I just downloaded the release archive and set it properly in `load-path`, as mentioned in [org mode manual](http://orgmode.org/manual/Installation.html).
HTH.

**Comment by yjwen** [comment]
That was due to API change between different versions of org-mode. Should have gone with the latest org-mode and org-reveal.
