### ISSUE TITLE
Automatic scale of the TOC?

### ISSUE THREAD

**Issue by vmalloc** [yjwen/org-reveal#261]
Even for relatively small trees, the TOC ends up overflowing the first slide... Is there an option to make it auto-scale?

**Comment by yjwen** [comment]
Automatic scaling can be done by specifying font size by view port width in a local CSS. For the text of TOC, specify the font size to id `text-table-of-contents`. Please try the following org file and CSS.

The org file:
```
#+TITLE: TMP
#+REVEAL_EXTRA_CSS: ./local.css

* Heading 1
* Heading 2
* Heading 3
* Heading 4
* Heading 5
* Heading 6
* Heading 7
* Heading 8
* Heading 9
* Heading 10
* Heading 11
* Heading 12
* Heading 13
```

And the _local.css_
```css
#text-table-of-contents {font-size: 1.5vw;}
```
