### ISSUE TITLE
Consistent slide IDs (2)

### ISSUE THREAD

**Issue by joonro** [yjwen/org-reveal#262]
Hi,

Following up to #249, I think it would be great if we can have consistent slide ids (ids reflecting slide numbers (3/4, for example) would be ideal).

Currently whenever I export to HTML, random slide anchors are generated, so if I refresh my browser to see my new slides, it moves back to the first page and I have to navigate back to the slide I was working on.

Putting `CUSTOM_ID` property to every slide is not practical since I have 50+ slides, and exporting current subtree only does not work well - for example, I get broken overlays when I export a subtree with `#+REVEAL: split`

I think this will make things much easier - hopefully this is not too much trouble.

Thanks!

**Comment by kellpossible** [comment]
agreed, this would definitely make the workflow a little smoother

**Comment by phillord** [comment]
Also, agree with this.

**Comment by phillord** [comment]
Checked the code and this is pretty easy to fix. Will you accept a PR?

**Comment by ivanperez-keera** [comment]
Yeah, it would be great it this could be accepted. Funny enough, I was using an older version of org-reveal and I think there they were the same after re-exporting.

**Comment by yjwen** [comment]
Fixed by https://github.com/yjwen/org-reveal/commit/6052357f26d8e8fff09da17bd6f998ab71c41b64
