### ISSUE TITLE
Split in the middle of a list 

### ISSUE THREAD

**Issue by joonro** [yjwen/org-reveal#264]
Hi,

Would it be possible to split a long list into multiple slides? 

Currently using `#+REVEAL: split` does not work:

```org
1. test

#+REVEAL: split

2. test
```

resets the list numbering, and 

```org
1. test

   #+REVEAL: split

2. test
```

breaks the list.

I'm sorry for so many issue openings!

**Comment by dingesista** [comment]
Here is how I would do this:

1. test

   #+REVEAL: split

2. [@2]test

The [@2] forces the number.

**Comment by joonro** [comment]
Thank you so much for this. It works well - but I had to unindent (like the example below) `#+REVEAL: split`, because otherwise it breaks the list. 

```org
1. test

#+REVEAL: split

2. [@2]test
```
