### ISSUE TITLE
Angle brackets not quoted in src environments

### ISSUE THREAD

**Issue by bcc32** [yjwen/org-reveal#265]
Given the following org text:
```
#+BEGIN_SRC java
  List<String> favoriteWords = new ArrayList<String>();

  favoriteWords.add("teacup");
  favoriteWords.add("pasta");
  favoriteWords.add("java");

  System.out.println(favoriteWords); // [teacup, pasta, java]

  System.out.println(favoriteWords.size()); // 3

  System.out.println(favoriteWords.get(1)); // pasta

  favoriteWords.set(2, "Java");

  System.out.println(favoriteWords); // [teacup, pasta, Java]
#+END_SRC
```

I get the following output:

![screen shot 2017-01-20 at 01 14 10](https://cloud.githubusercontent.com/assets/1239097/22138274/c9bb2a18-dead-11e6-87cb-a4ab90908fb2.png)

As you can see, the text inside the angle brackets has been interpreted as a tag name, and is lowercased; there are also automatically-inserted closing tags (by the browser, perhaps?).

The HTML code produced by org-reveal contains:

```html
<pre><code class="java" >List<String> favoriteWords = new ArrayList<String>();

favoriteWords.add("teacup");
favoriteWords.add("pasta");
...
</code></pre>
```

As you can see, the angle brackets around `<String>` are not escaped on the first line.  They should be `&lt;` and `&gt;`, respectively.

This does not happen for me with normal export to HTML.

**Comment by yjwen** [comment]
The same issue of #304 and #314. Already fixed.
