### ISSUE TITLE
Image Background for All Slides

### ISSUE THREAD

**Issue by sunitjoshi** [yjwen/org-reveal#267]
Is there a way to specify a "Property" for image backgound for the entire file?

I tried this, but didn't work:
`#+PROPERTY: REVEAL_BACKGROUND: ./images/Background.gif`

**Comment by rafadc** [comment]
This reply comes "a bit" late but I'll leave it here in case somebody falls here ;)

You can use:

```
#+REVEAL_DEFAULT_SLIDE_BACKGROUND
#+REVEAL_DEFAULT_SLIDE_BACKGROUND_SIZE
#+REVEAL_DEFAULT_SLIDE_BACKGROUND_POSITION
#+REVEAL_DEFAULT_SLIDE_BACKGROUND_REPEAT
#+REVEAL_DEFAULT_SLIDE_BACKGROUND_TRANSITION
```

**Comment by yjwen** [comment]
Thanks for helping answer the question and adding the missing documents @rafadc
