### ISSUE TITLE
Readme.md does not mention which function needed to export

### ISSUE THREAD

**Issue by alexanderkjeldaas** [yjwen/org-reveal#269]
"Now you can export this manual into Reveal.js presentation by typing “C-c C-e R R”.

The above sentence does not help users using Spacemacs.  If the function was mentioned, it would be easier.

**Comment by mhaffner** [comment]
@alexanderkjeldaas This works for me in Spacemacs, but I had to set some other configurations first. I followed the guide here: http://beatpanic.berlin/how-to-render-slides-from-spacemacs-org-mode-to-reveal-js.html

Spacemacs' org-mode layer includes ox-reveal by default, so in `dotspacemacs-configuration-layers` you should add 

```
(org :variables
     org-enable-reveal-js-support t)
```

Then you can use `C-c C-e RR`

**Comment by whatacold** [comment]
I believe it's `org-reveal-export-to-html`, as there are only 4 interactive defuns when I type `M-x org-reveal`:

    4 candidates:
        org-reveal-export-to-html-and-browse
        org-reveal-export-to-html
        org-reveal
        org-reveal-export-current-subtree

**Comment by yjwen** [comment]
Yes, exactly. The main entry function is `org-reveal-export-to-html`.
