### ISSUE TITLE
blank box current/next slide on speaker notes

### ISSUE THREAD

**Issue by termlen0** [yjwen/org-reveal#270]
I ran into [this](https://github.com/yjwen/org-reveal/issues/184) as well. However, when using a local reveal.js, the font changes I made via a custom "local.css" gets removed. Also, In both cases, I cannot see speaker notes. I am on Debian Jessie (XFCE) running firefox

**Comment by yjwen** [comment]
Sorry for no reply for such a long time. But could you please check if the issue still exists with the latest reveal.js and org-reveal? It seems the issue has gone because no new such issue was reported.

Closing this one for now. If the issue still exists, please feel free to re-open it.
