### ISSUE TITLE
Can't suppress Created: text

### ISSUE THREAD

**Issue by stsquad** [yjwen/org-reveal#271]
Whenever I generate my presentation I get a "Created: timestamp" on the front page which I can't suppress. Is it because the  :time-stamp-file property is always there for any org-file?

**Comment by neymarsabin** [comment]
I am also having the same problem.

**Comment by nickjmeyer** [comment]
#226 solved the issue for me

**Comment by neymarsabin** [comment]
Thank you @nickjmeyer ,worked for me too.

**Comment by ivanperez-keera** [comment]
Isn't this solved then?

**Comment by stsquad** [comment]
timestamp:nil works thanks.
