### ISSUE TITLE
Recognize commented lines as speaker notes?

### ISSUE THREAD

**Issue by alphapapa** [yjwen/org-reveal#273]
Hi, just a quick suggestion: it would be nice if plain Org comments (lines that start with `#`) could be recognized as speaker notes, instead of having to use `#BEGIN_NOTES...#END_NOTES`.  :)

**Comment by chrissound** [comment]
Probably could be done with a regex on save hook?

**Comment by yjwen** [comment]
I am afraid it can't, because the comment lines are filtered by the org parser. org-reveal sees only things that are not comments.
