### ISSUE TITLE
slides notes don't show up/render

### ISSUE THREAD

**Issue by maxandersen** [yjwen/org-reveal#274]
I have the same problem as this comment on http://irreal.org/blog/?p=5889:

"They show up in the exported html, but in firefox I get a popup window with a timer that doesn't work and no notes, and in chrome the timer works but the notes don't show up either...."

the notes are in the generated html but neither notes nor slides shows up when pressing 's'.

If I use this demo for reveal.js it works just fine. 

Any idea why it does not work for org-reveal ?

**Comment by lechten** [comment]
In my case (Firefox, GNU/Linux), the popup is always empty except for a stopped timer after my first press of 's'. If I switch back to the presentation and press 's' again, everything works.

**Comment by yjwen** [comment]
Did you try to put the HTML into reveal.js root directory. It is a known issue, and that method is a workaround.

Closing the issue for now. Please feel free to re-open it if the workaround doesn't help.
