### ISSUE TITLE
Blank slide with only background image

### ISSUE THREAD

**Issue by mankoff** [yjwen/org-reveal#275]
Is there a way to tell org-reveal to ignore the heading? This would allow blank slides with only a background image. I can do this with

```
** 
    :PROPERTIES:
    :reveal_background: ./img.png
    :END:
```

But it would be nice to be able to have a descriptive header like `** Foo`

**Comment by zeltak** [comment]
i love that idea +1!

**Comment by yjwen** [comment]
This can be done with custom id for the heading and CSS to hide the heading. Please try the following org and css.

The org file
```
#+TITLE: TMP
#+REVEAL_EXTRA_CSS: ./local.css

* Heading 1
  :PROPERTIES:
  :CUSTOM_ID: invisible
  :END:

* Heading 2
```
And the local.css
```css
#invisible {
    visibility: hidden
}
```
