### ISSUE TITLE
Fragments not shown when frag_idx is used

### ISSUE THREAD

**Issue by lechten** [yjwen/org-reveal#278]
This pattern from Readme.org does not work (any more?):
> #+ATTR_REVEAL: :frag (grow shrink roll-in fade-out none) :frag_idx (4 3 2 1 -)
>   * I will grow.
>   * I will shrink.
>   * I rolled in.
>   * I will fade out.
>   * I don't fragment.

This is fixed in PR #277.

**Comment by yjwen** [comment]
It is working now.
