### ISSUE TITLE
Line break in lists

### ISSUE THREAD

**Issue by TammoR** [yjwen/org-reveal#279]
Is there an easy way to have line break inside a list? Obviously <br> are not being preserved when org is converted to html.

**Comment by lechten** [comment]
In Org mode, you can use `@@html` to export raw HTML, see here: http://orgmode.org/manual/Quoting-HTML-tags.html#Quoting-HTML-tags
In your case, try this: `@@html:<br>@@`

**Comment by yjwen** [comment]
Break the line by `\\`. Please try this:
```
 - Line 1 \\
   Line 2.
 - Line 3.
```
