### ISSUE TITLE
auto fit/scale reveal_background_size?

### ISSUE THREAD

**Issue by zeltak** [yjwen/org-reveal#281]
Hi

i know that with `reveal_background_size` one can use px and % to define size bit was wondering if one can also define a auto fir/auto scale option so it nicely auto fits the image?

best

Z

**Comment by yjwen** [comment]
Yes, any legal [background-size](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size) property can be set to `reveal_background_size`. For your question, I guess it is to stretch the background image to fix with the slide page. If so, `:reveal_background_size: 100% 100%` will do.
