### ISSUE TITLE
reveal_title_slide doesn't accept whitespace

### ISSUE THREAD

**Issue by emanjavacas** [yjwen/org-reveal#283]
I am trying to get the link to the slides on the title page by passing:

```
#+OPTIONS: reveal_title_slide:"<h1>%t</h1><h2>%a</h2><h4>%d</h4><a href='#'>https://...</a>"
```

But the link fails to show up throwing a "End of file during parsing" Error.
(I am using the stable MELPA version). 

Is there a way to achieve this?

**Comment by tariqk** [comment]
I'm having the same problem with the following `OPTIONS` value, which is similar:

`#+OPTIONS: reveal_title_slide:"<h1>%t</h1><h2><a href="mailto:%e">%a</a></h2>"`

Any inclusion of spaces in this variable triggers this error:

`"org-export--parse-option-keyword: End of file during parsing"`

I'm using version 20161027.226 of org-reveal, available on MELPA.

**Comment by lechten** [comment]
What happens if both of you remove the outer "?

**Comment by tariqk** [comment]
@lechten Well, then the HTML *does* export… but the title slide is completely blank.

Interestingly, replacing the outer double quotes and replacing them with single quotes causes the same problem: it'll export, but the title slides are blank. 

I think org-export just sees the option, doesn't understand it, and assumes that the title slide ought to be `nil`.

That being said, replacing the *inner* quotes with single quote, i.e. it's now:

`#+OPTIONS: reveal_title_slide:"<h1>%t</h1><h2><a href='mailto:%e'>%a</a></h2>"` 

...gives me the same error I've experienced previously:

`org-export--parse-option-keyword: End of file during parsing`

**Comment by lechten** [comment]
I see. Apparently, options are not meant to contain spaces. In your case, spaces are not necessary, though, as `%e` automatically creates a hyperlink. Try this: 
`#+OPTIONS: reveal_title_slide:"<h1>%t</h1><h2>%a</h2><h2>%e</h2>"`

Alternatively, you might set the corresponding Emacs variable with this in the first line (you must reload the file to update the variable whenever you change that line):
`# -*- org-reveal-title-slide: "<h1>%t</h1><h2>subtitle with spaces and <a href='http://example.com'>example domain</a></h2>" -*-`

**Comment by tariqk** [comment]
That's fascinating! I'll do that, because I do want to put in instructions in the first title slide, to help people who aren't used to react.js figure out what to do next.

**Comment by yjwen** [comment]
Now the title slides can be given by multiple `#+REVEAL_TITLE_SLIDE` option lines. Please check #358 for the detail.
