### ISSUE TITLE
footer really in bottom

### ISSUE THREAD

**Issue by phineas0fog** [yjwen/org-reveal#288]
Hello,
In first, thanks for your work cause its very cool and practical :)
But i want to put the footer really on the bottom-right of the screen, with a smaller font-size and the header at the top-left, with the same font-size, but i do not master enough the css... /
Thanks for help :D

**Comment by amca01** [comment]
Did you ever get this worked out?  I fund that this worked:

```
.reveal .slides .slide-footer {
  font-size: 16px;
  color: Gray;
  position: fixed;
  bottom: 0;
  left: 0;
}
```
Put that in your `local.css` file and it will give you a footer in the bottom right.  You can adjust the text color and size of course to your own liking.
