### ISSUE TITLE
Allow TOC to split into multiple slides

### ISSUE THREAD

**Issue by javazquez** [yjwen/org-reveal#289]
Hello,
I would like to propose the ability to have a long Table of Contents split into multiple vertical slides. I am using org-reveal for a workshop and have many slides. Having a TOC for that many slides would help students navigate to points of interest after the workshop is complete. 

Thanks,
Juan

**Comment by yjwen** [comment]
It is hard to split the automatically generated Table of Contents. However, I prepared a function to insert TOC manually to org buffer, so that you can split it when it is too long. Please check  [the document](https://github.com/yjwen/org-reveal#mananging-table-of-contents) for how to.
