### ISSUE TITLE
KaTeX support ?

### ISSUE THREAD

**Issue by mashu** [yjwen/org-reveal#292]
Hi,

It would be nice to have KaTeX as faster alternative to MathJax
https://github.com/j13z/reveal.js-math-katex-plugin

How can org-reveal be configured to use KaTeX instead ?

Thanks,

**Comment by yjwen** [comment]
Yes, org-reveal can be configured to use KaTeX. To do so, the following steps are necessary:

1. Install the KaTex plugin by that plugin's instruction
2. Costumize `org-reveal-external-plugins` to add a new key/value pair, whose key is "katex" and whose value is `"{src:'%splugin/math-katex/math-katex.js', async: true}"`, **including the double quotes**
3. Add an option line `#+OPTIONS: tex:verbatim` to the org file

Then export and check if the equations are displayed.
