### ISSUE TITLE
List item style not respected when using a fragment 

### ISSUE THREAD

**Issue by mhaffner** [yjwen/org-reveal#296]
I've included an extra .css for a few items including
```
.reveal ul {
    text-align: left;
}
```

which works as expected when I do something like 
```
- some stuff
  - other stuff
  - other stuff
      - last stuff
```

However, when I use 
``` 
- some stuff
#+ATTR_REVEAL: :frag appear
  - other stuff
  - other stuff
      - last stuff
```
the second, third, and fourth items ("other stuff", "other stuff", and "last stuff") are shifted far to the right. It seems as though the org-reveal sample presentation suffers from this effect too (see slide 31 of the sample presentation). Can I achieve what I want by editing my extra .css file? Or is this a problem with org-reveal? Or reveal.js?

**Comment by lechten** [comment]
Is that issue really related to color in the css?
Your indentation is wrong.  Try this:
```
- some stuff
  #+ATTR_REVEAL: :frag appear
  - other stuff
  - other stuff
    - last stuff
```
At least this works in my fork (PR #277).

**Comment by mhaffner** [comment]
@lechten Color is irrelevant. You're right. I had just copy/pasted what I had. I don't think it's an indentation issue. I'm using Emacs `M-l` to indent; the indented items I had typed in manually. Poorly explained on my part. Sorry. I updated the issue.

**Comment by lechten** [comment]
Can you please try again with spaces in front of `#+ATTR_REVEAL:` as in my example above?

**Comment by mhaffner** [comment]
@lechten Wow. That did it! Thanks. I would have never guessed that. It seems a little obscure.
