### ISSUE TITLE
Not compatible with later versions of reveal.js

### ISSUE THREAD

**Issue by pmilosev** [yjwen/org-reveal#297]
Hi,

I had an issue where theme and transition worked fine when REVEAL_ROOT is set to http://cdn.jsdelivr.net/reveal.js/3.0.0/, but could not get theme to work with a local copy of reveal.js (both the theme and transition switched to default values).

Then I realized I have downloaded the latest version of reveal.js, which is 3.5.0. I tried pointing to a remote distribution of version 3.5.0 and got the same problem. I downloaded 3.0.0 locally and everything works fine now.

This setup works for me, but I guess it would be nice to have latest version supported as it fixes some bugs (e.g. PDF export, etc.)

**Comment by myrjola** [comment]
For me the latest reveal.js version 3.5.0 works after adding

```
#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js@3.5.0
```
to my org file.

**Comment by yjwen** [comment]
My local test with reveal.js 3.5.0 cannot display properly either. However, 3.8.0 worked fine. Please try the latest reveal.js.
