### ISSUE TITLE
Freezing on reveal_single_file

### ISSUE THREAD

**Issue by ntnsndr** [yjwen/org-reveal#298]
I've just started running org-reveal on Ubuntu 10.04, with the latest emacs and the rest in the Terminal. First of all, thank you to all contributors. It's a fantastic tool.

I'm using a reveal.js directory located in my home directory (~/.revealjs/reveal.js). Is specify that both in my .emacs file ("setq org-reveal-root") and in my org file options ("#+REVEAL_ROOT:").

All works fine on the default settings. But when I use " #+OPTIONS: reveal_single_file:t", the export-to-file process stalls indefinitely. Emacs hangs and I have to use Control-G to end it. No new file is created in the directory. I don't see any relevant output in \*Messages\* in emacs.

Please let me know if you can identify anything I'm doing wrong, or if there's more information I should be providing. Thank you in advance for considering this.

**Comment by yjwen** [comment]
Sorry for such a late rely. I guess org-reveal was fetching online contents to local. Could you please provide a minimum sample org-file that can reproduce the issue. My local tests didn't freeze.

**Comment by yjwen** [comment]
Closing the issue for now. If it still exists, please feel free to open it.
