### ISSUE TITLE
Add in-line fragment

### ISSUE THREAD

**Issue by ivanperez-keera** [yjwen/org-reveal#301]
Is it possible to add an in-line fragment so that it gets shown without a line-break before it?
```
Text 1, 
#+ATTR_REVEAL: :frag roll-in
text 2, 
#+ATTR_REVEAL: :frag roll-in
text 3
```
What I'm looking for is a way so that, after showing all the fragments, the text on the screen is:
```
Text 1, text 2, text 3
```

I tried a few possibilities (moving the `#+ATTR_REVEAL` line together with the text, trying to add block comments), but nothing worked so far.

**Comment by joonro** [comment]
I'm not sure org-reveal supports this. I use the following macro:

```
#+MACRO: FRAG @@html:<span class="fragment">$1</span>@@
```

And use ```{{{FRAG(Text 1)}}}` when I want in-line fragments.

**Comment by ivanperez-keera** [comment]
Thanks!
