### ISSUE TITLE
Affiliation on title slide, and mathjax?

### ISSUE THREAD

**Issue by amca01** [yjwen/org-reveal#303]
I have two simple issues:

First, I'm preparing a couple of conference talks, and experimenting with reveal.js/org-reveal as an alternative to beamer.  How can I include my affiliation (university, department, etc) on my title slide?    I could do this as part of "author" but in which case how do I force line breaks?

 Second, I need a fair bit of mathematics, and as far as I know MathJax should work automatically: at least that's what the Readme.org file seems to indicate; there's no specific instructions about MathJax in that file itself.  But in my own file, the latex equation is not rendered: it is just shown on the slide as latex code.  I've tried including the link to my local MathJax installation with

#+REVEAL_MATHJAX_URL: file:///usr/share/mathjax/MathJax.js

but that doesn't make any difference.  So the Readme.org file is rendered perfectly, but my own file (which is in a different directory), is not.  What extra information does my file need to include so that MathJax renders the latex code?

Thank you very much.

**Comment by lechten** [comment]
First, in [my fork](https://github.com/lechten/org-reveal) you can set `#+REVEAL_TITLE_SLIDE: title.html`, where `title.html` needs to be an HTML template file, see [there](https://gitlab.com/oer/OS/blob/master/OS02-Interrupts.org) for an example.
Second, you probably need a config parameter. I don't use MathJax right now, but in the past I had this:
`(setq org-reveal-mathjax-url "./MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML")`

**Comment by amca01** [comment]
Well, according to the MathJax page, and using the options of org-reveal, I should be able to set

`#+REVEAL_MATHJAX_URL:"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"`

except that this has no effect: the LaTeX is not rendered.   I'll try with dvipng and see if that works, as a fallback.  But MathJax _should_ work automatically....

As to multiline author, all I want is something that looks like this:

MY NAME
DEPARTMENT OF STUFF
UNIVERSITY OF PLACE
TOWN, COUNTRY

but I can't find how to force line-breaks in the output.  I've tried inserting `<p>`, or `\\` to indicate newlines, but all that happens is that those symbols are copied verbatim into the output.  I will check out your fork - but surely there's a way of doing this in plain org-reveal?  I can't be the first person who's wanted to put some affiliation information on a title slide.

**Comment by amca01** [comment]
I worked it out!  The URL I had for MathJax was in fact wrong; I have set the correct one in my `.emacs` (not as an option in my org file).  As for line breaks, the trick, as is in fact given in the documentation, is to escape the html codes in such a way that they are actually used in the markup; thus `@@html:<br>@@`.   This is a slight fiddle, but at least it works,
