### ISSUE TITLE
Example of adding a third party plugin?

### ISSUE THREAD

**Issue by amca01** [yjwen/org-reveal#306]
Being a bit of a thickie, I don't fully understand the instructions given for adding a third party plugin.  For example, I'd like to add the menu plugin as given at https://github.com/denehyg/reveal.js-menu  Is there an example somewhere of somebody successfully importing and using such a plugin? (There are tons more plugins given on the reveal.js github page https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware which would be fun to explore using org-reveal.)

Thanks!

**Comment by lechten** [comment]
[My configuration for emacs-reveal](https://gitlab.com/oer/emacs-reveal/blob/master/reveal-config.el) activates several plugins. Your case should be similar to the jump plugin in that file. Hope that helps.

**Comment by amca01** [comment]
Thank you very much: I'm still experimenting with one but I can't get it to work.  I'll keep fiddling...

**Comment by yjwen** [comment]
There is an example at #320, for your reference.
