### ISSUE TITLE
Fragments: reveal two at a time; grow current?

### ISSUE THREAD

**Issue by amca01** [yjwen/org-reveal#307]
So this is two questions:

1. I have a list of which I want to reveal in groups of two: first items 1 and 2, then items 3 and 4, etc.  Can this be done?

2.  There are various "highlight-current" fragment options, such as "highlight-current-blue".  But what I'd like is to have something like "highlight-current-grow" or "highlight-current-bold".  In fact these are not supported by reveal.js, so I'm wondering if there's some way I can build this into my local.css  file?

Thanks!

**Comment by amca01** [comment]
Ooh I've disovered how to do 2, at least:

- In the local.css file:

   ```
  .reveal .slides section .fragment.highlight-current-blue.current-fragment {
        color: #105799;
        font-weight: bold;  
     }
   ```

- in my presentation.org file:

    ` #+ATTR_REVEAL: :frag (highlight-current-blue)`

**Comment by lechten** [comment]
Ad 1. You can do this (at least in my PR #277):

    *** Fragments with Custom Order
    #+ATTR_REVEAL: :frag (appear) :frag_idx (1 4 3 2 1)
    * I’m first.
    * Fourth.
    * Third
    * Second
    * I’m also first.
