### ISSUE TITLE
Images side by side?

### ISSUE THREAD

**Issue by amca01** [yjwen/org-reveal#308]
I want to display several images; in my `.emacs` file I have set 

    (setq org-image-actual-width nil)

which means in my org file I can have, for example:

    #+ATTR_HTML: :width 200 
    [[./img/image1.jpg]]
    #+ATTR_HTML: :width 300 
    [[./img/image2.jpg]]
    #+ATTR_HTML: :width 250 
    [[./img/image3.jpg]]

The trouble with this is that the images are displayed in a column, which means only the first (and the top of the second) is shown.  How can I display them side by side?

The other issue I have is that something in my emacs configuration is causing the double brackets not to be displayed, so what I actually see in the image lines is

    ./img/image2.jpg

I've no idea of what part of what (minor) mode is causing this - but any advice would be welcome!

Thanks very much.

**Comment by jmhammond** [comment]
I know this is really late, but I had this issue today. I did a workaround at html code: 
`#+BEGIN_EXPORT html`
`<img src="first.jpg" width="45%"> <img src="second.jpg" width="45%">`
`#+END_EXPORT`
I wanted to share to anyone who comes to this later.

**Comment by rzr** [comment]
Well you could use align attributes it worked for me too

```org
#+ATTR_HTML: :width 45% :align left
https://files.mastodon.social/media_attachments/files/024/464/695/original/affef1e1810b17eb.jpg#./file/sg90.jpg
#+ATTR_REVEAL: :frag (fade-in)
#+ATTR_HTML: :width 45% :align right
https://files.mastodon.social/media_attachments/files/024/464/758/original/dfc1496f27cc831f.png#./file/pwm-sg90.png
```

I will share a rendered html if you want to view, it will be somewhere at:

https://rzr.github.io/rzr-presentations/
