### ISSUE TITLE
Two column layout?

### ISSUE THREAD

**Issue by amca01** [yjwen/org-reveal#309]
Sorry to keep asking so many questions.... current issue is: how do I get a two column layout?  In particular with text in one half, and an image in the other half?

I think this can be done with tables, but I can't get the effect I want... I'm hoping somebody might have an example?

Thanks!

**Comment by lechten** [comment]
For two columns I'm using

    #+BEGIN_leftcol
    ...
    #+END_leftcol

followed by a corresponding `rightcol` block with CSS. See [emacs-reveal-howto](https://gitlab.com/oer/emacs-reveal-howto/blob/master/howto.org) for an example.

**Comment by amca01** [comment]
Thank you; also I discovered that

    #+REVEAL_HTML: <div class="column" style="float:left; width:50%">
    ...
    #+REVEAL_HTML: </div>

works.

**Comment by yjwen** [comment]
Great explanations!

**Comment by xeruf** [comment]
My findings should apply here just as well :) https://gitlab.com/oer/org-re-reveal/-/issues/88
