### ISSUE TITLE
Exporting MathJax?

### ISSUE THREAD

**Issue by amca01** [yjwen/org-reveal#310]
In order to be able to use my presentation externally, I'm exporting to one large file.  Everything works fine except for MathJax.  I have MathJax on my local machine, and the local file picks it up.  But exporting doesn't - in place of nice rendered equations I just see the unrendered LaTeX code.

I _can_ export to PDF - that works fine - but I'd much rather export to html.  That is, after all, the whole point of reveal.js, org-reveal, and their helpers.

Does anybody know the trick for making html export include MathJax?

Thanks!

**Comment by yjwen** [comment]
MathJax is too huge to be embedded with reveal.js presentations. But there is an option to use MathJax third party CDN, which is the default URL used by org-reveal.
