### ISSUE TITLE
Readme: which settings can be in PROPERTIES

### ISSUE THREAD

**Issue by novoid** [yjwen/org-reveal#311]
Hi,

Thanks for this awesome tool!

Personally, I don't use separate Org-mode files for any **single** thing related to Org-mode. Which means that I also do not use a separate Org-mode file for a reveal presentation. Instead, I am putting everything in large files like `business.org` and use headings as starting points for presentations or any other export function.

This is why I would love to see more information in the Readme.org how to use (sub-)heading-related properties instead of file-level options. For example, I would like to see how I am able to define `#+Title: `, `#+Author:`, and `#+Email:` using properties.

That way, I am able to set-up multiple presentations within one single org-mode file with different settings for title, authorship or email addresses.

In my wildest dreams, it would be possible to use any setting either in file-based options or sub-heading-based properties.

**Comment by joonro** [comment]
This is already possible (maybe README.org does not have the information). This actually comes from  org-mode export settings. See https://orgmode.org/manual/Export-settings.html. If you scroll below, it says

> When exporting sub-trees, special node properties in them can override the above keywords. They are special because they have an ‘EXPORT_’ prefix. For example, ‘DATE’ and ‘EXPORT_FILE_NAME’ keywords become, respectively, ‘EXPORT_DATE’ and ‘EXPORT_FILE_NAME’. Except for ‘SETUPFILE’, all other keywords listed above have an ‘EXPORT_’ equivalent.

So basically you can add `EXPORT_` prefix to any options you want to use and use that as the property name. For example:

```
* Test
:PROPERTIES:
:EXPORT_OPTIONS: d:nil email:nil num:1 tags:nil timestamp:nil toc:nil todo:nil
:EXPORT_AUTHOR: Your Name
:EXPORT_DATE: 2018-01-01
:END:
```

These settings will be heading-specific.

**Comment by novoid** [comment]
Thanks!

Works like charm:

```
** test of org-reveal
:PROPERTIES:
:reveal_overview: t
:EXPORT_AUTHOR: Testauthor
:EXPORT_DATE: 2018-01-01
:EXPORT_TITLE: Testtitle
:EXPORT_EMAIL: Test@example.com
:EXPORT_OPTIONS: num:nil toc:nil reveal_keyboard:t reveal_overview:t
:EXPORT_REVEAL_HLEVEL: 3
:EXPORT_REVEAL_MARGIN: 200
:END:
```

I'd mention this in the readme since it is not too obvious how this works on a heading-basis.

**Comment by novoid** [comment]
I created https://github.com/yjwen/org-reveal/pull/317 as an example patch and close this issue here.

**Comment by joonro** [comment]
Thanks a lot! I'm not sure it will get accepted though given @yjwen has not been around for a while.
