### ISSUE TITLE
Deploying to github-pages?

### ISSUE THREAD

**Issue by amca01** [yjwen/org-reveal#313]
Does anybody have a step-by-step guide for this?  I've tried following 

http://jr0cket.co.uk/2014/01/share-your-revealjs-slides-on-github-pages.html

and also 

www.tikalk.com/devops/deploy-revealjs-slideshow-github-pages/

but my lack of knowledge of git is not helping.  In following the first set of instructions, I've ended up with a repository which is empty other than the initial "README.md" file.  Basically I want my presentations to be available via the web, rather than just on my computer.

Thanks!

**Comment by lechten** [comment]
The first guide does not mention how to generate the HTML files out of the Org files, the second one does not consider Org at all. You need to generate the HTML files into the directory containing reveal.js and push all of it. Also, one does not need the gh-pages branch (any longer?) but can activate GitHub Pages under the project's Settings (Options -> GitHub Pages).
An alternative is to have the generation of HTML happen upon commit in the Git infrastructure. This is what I'm doing on GitLab (free/libre and open source software) with my fork of org-reveal. See [there for a howto](https://gitlab.com/oer/emacs-reveal-howto/blob/master/howto.org). I'd be happy to extend the howto if you ran into problems.

**Comment by amca01** [comment]
Thank you again!  In fact, after several hours fiddling and swearing, I pieced it together.  It's not however entirely straightforward, as you have to:

- ensure all files (such as .js and .css files, as well as image files) can be addressed relative to your html file; this may also need changes in emacs variables such as `org-reveal-root`

- you then have to set up a git repository from the file containing your html file, add all files beneath it to that repository, and then push it to git-hub pages

- I changed my mathjax URL from my local installation to the new CDN available at cloudflare

In the end it worked fine: I was able to access all my presentations on the web just by going to the github pages I'd set up.  The only thing I couldn't do was get my source code highlighted: I'd been using highlight.js, which doesn't travel, and I could never get htmlize to work.  

I think the whole thing would be a bit easier if there was a CDN for reveal.js: then you could just point your html file (or your org file to it).  (Well, in fact reveal.js _is_ hosted at cdnjs.cloudflare.org - as mathjax is - but I'm not sure what URL would pull all the necessary files together.  That should work for highlight.js as well.)

**Comment by yjwen** [comment]
There is a CDN for reveal.js. Please add `#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js` to your org file. Then no local reveal.js installation is necessary.

For htmlize, just a confirmation. Has htmlize.el been installed?

**Comment by rzr** [comment]
I've been using to ghpages easily using makefiles tricks I've upstreamed check:

See:

https://crossstream.github.io/org-reveal/Readme

May it be also used for

https://yjwen.github.io/org-reveal/Readme
