### ISSUE TITLE
Exporting C++ code need manual HTML escape.

### ISSUE THREAD

**Issue by jiegec** [yjwen/org-reveal#314]
I have this code:
```c++
     #include <stdio.h>
     #include <string.h>
```

In the result html, it shows something like this:
```
#include <stdio.h>
#include <string.h>
</string.h></stdio.h>
```

I have to replace the code with:
```c++
     #include &lt;stdio.h>
     #include &lt;string.h>
```

**Comment by jiegec** [comment]
The same problem in PR https://github.com/yjwen/org-reveal/pull/302.

**Comment by jiegec** [comment]
I even forgot that I put the same issue myself https://github.com/yjwen/org-reveal/issues/304. Damn

**Comment by sleepynate** [comment]
I am also experiencing this problem when trying to include code blocks from an external file, such as:

`#+INCLUDE: "hello.c" src c`
