### ISSUE TITLE
recent org has introduced some breakage

### ISSUE THREAD

**Issue by rusimody** [yjwen/org-reveal#315]
org has recently moved out functionality to org-tempo
This (new code/types) was being broken by org-reveal

This patch seems to solve the problem:
[patch.txt](https://github.com/yjwen/org-reveal/files/1584808/patch.txt)

**Comment by CestDiego** [comment]
@rusimody could you make a PR with this patch?

**Comment by rusimody** [comment]
Hey Diego!
I can of course do that...
Are you collaborating on developing org-reveal with Yujie Wen?
Else I dont get the point… 
[Note 1: The patch is really trivial — 2 lines changed
 Note 2: Ive not stress tested it to know its correct; ie its good for the developer to check it out
]

**Comment by jaccarmac** [comment]
Apologies for stealing your thunder, didn't see this ticket when I created my PR #327 . Can even do one better though and have a one line diff ;)

**Comment by yjwen** [comment]
Already merged.
