### ISSUE TITLE
Trouble creating a basic layout

### ISSUE THREAD

**Issue by hmw42** [yjwen/org-reveal#318]
Hello,

I spent a couple of days playing with org-reveal. I tried to mimicry a beamer based slide set. Some of the features I use, text and image side by side for instance, I could implement. But I stranded with a thing that seems to be very simple: a slide with header at the top, a footer at the bottom and some content centered -horizontally and vertically- between header and footer (see [0] for the beamer equivalent). I tried the stretch class, various display styles like flex, various other things to position elements. But nothing came out of it. Either the content wasn't centered, or the box used for the content was way smaller than the available space, etc. ppp. I used colored borders around the different elements of the slide and the tools provided by the browser to figure out what happens. I have to say that I'm not an CSS or web expert, so it's completely my fault ;).

So, if anybody has pity, I wouldn't mind a hint or even a solution to my problem ;).

Regards
hmw

[0] https://www.c0t0d0s0.de/tmp/vm2.png

**Comment by kepi** [comment]
You can use https://github.com/e-gor/Reveal.js-Title-Footer plugin for footer, there may be something similar for footer.

Anyway, I think reveal.js just takes different approach to presentations, so there may be better alternatives if you want mimic beamer behaviour in html presentation.

**Comment by yjwen** [comment]
Slide header and footer can be specified by `#+REVEAL_SLIDE_HEADER:` and `#+REVEAL_SLIDE_FOOTER:`. The raw HTML texts will be placed the beginning and the ending of each slide section, enclosed by `<div>` of class `slide-header` and `slide-footer` respectively. So the header and footer's style must be defined in a stylesheet.

However, as @kepi has commented, there is no native support for header/footer in reveal.js. So it is difficult to make reveal.js slides the same as beamers.
