### ISSUE TITLE
Can't center an image

### ISSUE THREAD

**Issue by rbarzic** [yjwen/org-reveal#319]
I'm using:
#+ATTR_HTML: :width 60% :height 60% :align middle 

before the link to the image

The image is correctly resized but still aligned to the left, like the text

**Comment by doolio** [comment]
Have a look at the discussion around closed issue #172.

**Comment by yjwen** [comment]
Could not reproduce the issue.  The image by my local export has the expected alignment. Please try the latest version of org-reveal to see if the issue still exists. If so, please re-open this.

**Comment by Ossifragus** [comment]
I still have the same issue. For example, the following code still put the figure on the left. I used your local.css.

```
	#+ATTR_HTML: :width 40% :align middle
	[[cat.jpg]]
```

**Comment by Ossifragus** [comment]
I figured out a solution. I add the following to the .css file. 

```css
img.middle {
    display: block;
    margin-left: auto;
    margin-right: auto
}
```
Then the following works.
```org
#+ATTR_HTML: :width 40% :class middle
[[cat.jpg]]
```
