### ISSUE TITLE
Did anyone make chalk plugin work with org reveal?

### ISSUE THREAD

**Issue by cryoguy** [yjwen/org-reveal#320]
Did anyone make chalk plugin work with org reveal?
I got a blank html with following code:
`#+REVEAL_PLUGINS: (chalk) 
#+REVEAL_EXTRA_JS: ./revealjs_chalk.js`

**Comment by yjwen** [comment]
I guess you were referring to the [chalkboard plugin](https://github.com/rajgoel/reveal.js-plugins/tree/master/chalkboard). That plugin can be enabled by adding [extra style sheet](https://github.com/yjwen/org-reveal#extra-stylesheets) and [third-party plugin](https://github.com/yjwen/org-reveal#third-party-plugins).

Here are the necessary steps:

1. Download chalkboard.js and the "img" folder to the reveal.js plugin folders, like ~/reveal.js/plugin.
2. Enable the plugin to org-reveal by customizing variable `org-reveal-external-plugins`. Add a new key `chalkboard` and a new value `"{ src: '%splugin/chalkboard.js' }"`. Don't miss the double quotes and the  `%s` in the value string and don't forget to apply the change.
3. Add the extra style sheet to your org file by adding a line `#+REVEAL_EXTRA_CSS: https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css`
4. Enable the plugin by adding another line  `#+REVEAL_PLUGINS: (chalkboard)` to your org file.

**Comment by juanerasmoe** [comment]
Still no luck with this.
I added the following lines to my org file

    #+REVEAL_EXTRA_CSS: https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css
    #+REVEAL_EXTERNAL_PLUGINS: { src: '%splugin/chalkboard/chalkboard.js' }
    #+REVEAL_PLUGINS: (chalkboard)

But I still don't see the plugin activated in the presentation. The chalkboard.js file was added to the local copy of reveal.js and the path has been double checked.
