### ISSUE TITLE
May I modify preferred-id format?

### ISSUE THREAD

**Issue by niku** [yjwen/org-reveal#328]
I want to modify a url of revealjs with using history flag following like:

`http://example.com/slide.html#/slide-A78E6FB4-7551-4BBC-841C-472844524F17` ->
`http://example.com/slide.html#/A78E6FB4-7551-4BBC-841C-472844524F17`

To make change above, I think it needs change formatting string to given from external.
https://github.com/yjwen/org-reveal/blob/55e273ac9f28ded8a13b20428a8fc518a326c1e6/ox-reveal.el#L440

It was OK to change this format?

**Comment by yjwen** [comment]
Done by 02bcbcd. Added a custom variable `org-reveal-slide-id-head` for heading the preferred IDs. Please set that variable to an empty string to remove "slide-" from the links.
