### ISSUE TITLE
HLevel is limited to 3

### ISSUE THREAD

**Issue by vinodhmj** [yjwen/org-reveal#329]
Even after setting #+REVEAL_HLEVEL: 5, the presentation is not creating horizontal slides for a heading at level 4.
org mode version 9.1.4.
ox-reveal version 20161027.226

**Comment by vinodhmj** [comment]
It worked. Thankyou.

**Comment by nikclayton** [comment]
This should probably be re-opened, with a note that the documentation should be updated to mention this.
