### ISSUE TITLE
List handling code out of sync with ox-html

### ISSUE THREAD

**Issue by alastairdb** [yjwen/org-reveal#333]
The current revision of ox-reveal (d583a26dd0582f06f1679cbd5af576a768a4f724) calls  `org-html-checkbox` with one argument. The current revision of ox-html defines `org-html-checkbox` with two arguments. This causes exports with list to fail.

**Comment by yjwen** [comment]
This issue has been fixed. Please check with https://github.com/yjwen/org-reveal/commit/6052357f26d8e8fff09da17bd6f998ab71c41b64

**Comment by alastairdb** [comment]
I didn't see the changes related to checkbox. I think something like the following should fix it:
``` diff
@@ -816,7 +816,10 @@
   (let ((attr-html (cond (attributes (format " %s" (org-html--make-attribute-string attributes)))
                          (checkbox (format " class=\"%s\"" (symbol-name checkbox)))
                          (t "")))
-	(checkbox (concat (org-html-checkbox checkbox)
+	(checkbox (concat 
+		   (condition-case err
+		       (org-html-checkbox checkbox)
+		     (wrong-number-of-arguments (org-html-checkbox checkbox info)))
 			  (and checkbox " ")))
 	(br (org-html-close-tag "br" nil info)))
     (concat
```

**Comment by yjwen** [comment]
My fault. It seemed I was using an org-mode out of date. Fixed just now. Please sync to the latest.

**Comment by alastairdb** [comment]
谢谢

**Comment by yjwen** [comment]
不客气 :)
