### ISSUE TITLE
Use master on melpa and stable on melpa-stable

### ISSUE THREAD

**Issue by Compro-Prasad** [yjwen/org-reveal#335]

**Comment by jmhammond** [comment]
Is there any way that someone can help with this help? I'd be happy to contribute.

Melpa being two years old is certainly inconvenient.

**Comment by jmhammond** [comment]
Actually, could we propose a pull request on https://github.com/melpa/melpa/blob/master/recipes/ox-reveal to change from stable to master?

**Comment by ulloa** [comment]
I believe that would fix this issue #342 . I haven't been able to use org-reveal with use-package.

**Comment by yjwen** [comment]
Code has been updated. Master on MELPA now.

**Comment by Compro-Prasad** [comment]
There is a fork of this repo https://gitlab.com/oer/org-re-reveal
Why still keep this?
