### ISSUE TITLE
Suggestion: Include bibliography from org-ref at the end of the slideshow

### ISSUE THREAD

**Issue by jmhammond** [yjwen/org-reveal#336]
This suggestion is different than #248. I would like my org-ref bibliography to be included at the end of my slideshow. 

I've forked and made a solution that works for me.  https://github.com/jmhammond/org-reveal/commit/03594e02b361a170934dc224ae88f0630e8d8d7b

Perhaps someone if better elisp-hackery (I'm a fairly new emacs user) could make it work for org-ref vs reftex vs whatever.

**Comment by yjwen** [comment]
Already merged.
