### ISSUE TITLE
Broken slide id for 3rd level headings if num:2

### ISSUE THREAD

**Issue by joonro** [yjwen/org-reveal#339]
Hi -

I love the new stable numbering system. However, I found that if I have `num:2` option, then the 3rd level headings have broken slide ids. For example, with the following `Testing.org`:

```org
#+REVEAL_ROOT: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.6.0/

#+OPTIONS: num:2 reveal_history:t 

* Heading 1
** Heading 2
*** Heading 3
```

When I export this file, the `Heading 3` has id `Testing.html#/slide-sec-`, which breaks slide navigation. But with `num:3` option, it correctly has `Testing.html#/slide-sec-1-1-1`.

**Comment by vonpupp** [comment]
@joonro I am not totally sure how `num` works, but I have used `num:t` and it seems to work. However now I have ugly numbered titles. I just wanted history to work, but it is the only workaround so far I have found.

**Comment by yjwen** [comment]
The slide id has been changed to be the same as HTML exports, using a hash value, regardless whether headings are numbered or not, so that the TOC links won't be broken. Slides' consistent links are in the form of `#/1/1`.
