### ISSUE TITLE
Commit 6052357 breaks links

### ISSUE THREAD

**Issue by lechten** [yjwen/org-reveal#341]
Commit 6052357 breaks links for me. Function `org-reveal-link` (as well as `org-reveal-toc`) uses the hard-coded string `#/slide-` to generate links for slides with custom IDs. I guess that should be `#/slide-sec-` now?

In general, this seems to break links to slides of other (older, pre-existing) presentations.

Maybe the string "slide-sec-" should go into a customizable variable? 

BTW, the commit is entitled "Fix TOC links." Previously, links from the TOC were working fine for me.

**Comment by lechten** [comment]
Oh, and my TOC is now broken. It points to targets of the form `#/slide-org9c6db0e`. However, the corresponding section now has `id="slide-sec-1"` instead of `id="slide-org9c6db0e"`. That was probably introduced in 3b02186a81f7d9c96b4be712b7cec97fe04a4bfe. Should I open this as separate issue?

**Comment by yjwen** [comment]
Should have been fixed by 6d6e4b5. The slide ID is now using the org reference string, consistent wit ox-html.
