### ISSUE TITLE
Failed to install ox-reveal: Need package ‘org-20150330’, but only 9.1.13 is available

### ISSUE THREAD

**Issue by mrbig033** [yjwen/org-reveal#342]
+ GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.31) of 2018-08-16
+ Org mode version 9.1.9 (release_9.1.9-65-g5e4542 @ /usr/local/share/emacs/27.0.50/lisp/org/)

It seems I can't install `ox-reveal` because my version is too new.

**Comment by phye** [comment]
Same issue here. The package just cannot be required.

**Comment by yeldiRium** [comment]
Same issue here with emacs 26.1 and org-mode 9.1.9.
Ox-reveal has version 20161027.926 in my package list.

**Comment by ulloa** [comment]
I have this issue trying to use ox-reveal with 
```
 (use-package ox-reveal
    :ensure t)
    (setq org-reveal-root "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.6.0/js/reveal.min.js")
```
Emacs 27.0.5. Org-version 9.1.9.

I get `Error (use-package): Failed to install ox-reveal: Need package ‘org-20150330’, but only 9.1.14 is available`

I noticed there was this similar open issue: https://github.com/yjwen/org-reveal/issues/324. The only thing I gathered was that the latest version should work.

**Comment by yeldiRium** [comment]
> The only thing I gathered was that the latest version should work.
It does. I installed the current version of `org-reveal` by increasing the required `org` version to 9.1 and using `package-install-file`.

**Comment by ulloa** [comment]
Can you test if works with changing it to 8.3? If that's the case maybe one of the maintainers could just resubmit a pull request to MELPA. Because I think at some point the date version for package requirement was uploaded to MELPA instead of "8.3", but it looks right now. And that may not work as expected?

**Comment by yeldiRium** [comment]
> Can you test if works with changing it to 8.3?
Indeed it does!

**Comment by avocadoras** [comment]
@yeldiRium could you provide steps to get org-reveal working? I had to clone the repo and then load the path but would rather installing via melpa

**Comment by avocadoras** [comment]
@yeldiRium no problem. thanks for your answer

**Comment by seokbeomKim** [comment]
I guess there might be someone who is looking for a solution for this.
I add a comment for convenience with a download link:

1. Download org-20150330: https://elpa.gnu.org/packages/org-20150330.tar
2. tar -xf org-20150330.tar -C $HOME/.emacs.d/elpa (one of load-path)

**Comment by edmwagner** [comment]
I do not recall the reference now, but I was Informed to install org-mode from orgmode.org/elpa/  I thought reference was on https://github.com/yjwen/org-reveal/ but do not see it now.

Adding from directions at https://orgmode.org/elpa then refresh package and I was prompted to upgrade org to 20190311.

ox-reveal installed fine after and is working fine thus far.


Hope that helps.

**Comment by yjwen** [comment]
Already fixed. MELPA version is now requiring org-8.3
