### ISSUE TITLE
Export subtree filename

### ISSUE THREAD

**Issue by tarjeiba** [yjwen/org-reveal#343]
Exporting a subtree does not export to filename set by
```
    * Presentation
    :PROPERTIES:
    :EXPORT_FILE_NAME: test.html
    :END:
    ** Slide title
```

Is there an easy fix to this problem?

**Comment by joonro** [comment]
Are you exporting `* Presentation` subtree? `:EXPORT_FILE_NAME:` should be `test`, without the extension. The extension gets decided depending on the backend.

**Comment by yjwen** [comment]
Yes. To utilize the `EXPORT_FILE_NAME` property, first, the file name cannot have an extension; Second, the export should be done with "Export scope" switched to "Subtree", by "C-c C-e C-s R R".
The "Current subtree to file" entry isn't aware of the parent heading's `EXPORT_FILE_NAME` property. It merely narrows the current buffer and exports. `EXPORT_FILE_NAME` is processed by the org-mode's exportation backend.

Maybe "Current subtree to file" should obsolete. Let me add some hint message first.
