### ISSUE TITLE
[Request] Keep slide title when "#+REVEAL: split" is used

### ISSUE THREAD

**Issue by helasraizam** [yjwen/org-reveal#346]
There is no title for slides appearing after a #+REVEAL: split, I think it would be useful to add the option for splits to carry the title over to the next slide, since they are describing the same content (in the org hierarchy) after all.

**Comment by yjwen** [comment]
Done. See the updated document ([Here](https://github.com/yjwen/org-reveal#force-split)) for how to repeat the title for split slide.
