### ISSUE TITLE
[Request] Hide content from plain html export (and vice versa)

### ISSUE THREAD

**Issue by helasraizam** [yjwen/org-reveal#347]
I'm exporting contents of an org file to both org-reveal slides and html notes, and there is some information I would like on the slides and not the notes and vice versa.  I think it would be useful to have a "comment block" that would show in plain html export but not org-reveal export, and vice versa.

**Comment by joonro** [comment]
Hi - 

I have an code snippet at https://joonro.github.io/Org-Coursepack/Lectures/04%20Creating%20Content%20for%20Slides%20and%20Handouts.html#speaker-notes which you can use. It basically removes speaker notes from LaTeX and html output. You can modify it to achieve other effects as well. Hope this is helpful.

**Comment by yjwen** [comment]
You can use hooks to do what your are requestin. A hook `org-export-parsing-hook` is called before org-mode parsing the buffer. Adding a function to filter unwanted contents from the buffer should be sufficient. The following code is such an example.
```elisp
(add-hook 'org-export-before-parsing-hook
	  (lambda (backend)
	    (case backend
	      ;; For reveal, remove anything between # reveal_off and
	      ;; # reveal_on
	      ('reveal (replace-regexp "# reveal_off
.*
# reveal_on
" ""))
	      ;; For html, remove anything between # html_off and #
	      ;; html_on
	      ('html (replace-regexp "# html_off
.*
# html_on
" "")))))
```
After adding the hook, try to export the following org file:
```
* Heading

Both reveal and HTML can see this paragraph.

# reveal_off
Reveal won't see this.
# reveal_on

# html_off
HTML wont't see this.
# html_on

Both reveal and HTML see this paragraph again.
```
