### ISSUE TITLE
Using reveal.js-d3 plugin with org-reveal

### ISSUE THREAD

**Issue by bdixon95** [yjwen/org-reveal#348]
I'm running into some trouble adding the external plugin [reveal.js-d3](https://github.com/gcalmettes/reveal.js-d3) to org-reveal.

I can't find the org-reveal-external-plugins variable.

Any help would be great.

Thanks.

**Comment by yjwen** [comment]
You can customize that variable by the following steps:

1. Enter `M-x customize-variable`
2. Enter `org-reveal-external-plugins` in the minibuffer, to launch the customization buffer for that variable.
3. Move cursor to `INS` and press <ENTER>. 2 text fileds will show up. Enter name "reveald3" in the "Key" field, and enter "{src: '%splugin/reveald3.js'}" (WITH DOUBLE QUOTES) in the "Value" field.
4. Move cursor up to "Apply" or "Apply and Save", to apply the change temporarily or persistently.

Now the plugin is enabled. Please try to export an org-file and find if the generated plugin line in the HTML is satisfying.

This is my setting for including reveald3, for your reference.
![Screenshot_2019-06-29_23-16-35](https://user-images.githubusercontent.com/4273142/60386278-814c3200-9ac5-11e9-8f2b-5d34c94bed29.png)
