### ISSUE TITLE
Merge developments of @lechten

### ISSUE THREAD

**Issue by andersjohansson** [yjwen/org-reveal#349]
@lechten has done much work on a fork of org-reveal (https://github.com/lechten/org-reveal), as the development and maintenance here seemed to stall for a time. Perhaps they could put in an effort to integrate these changes? Or take share in the maintainership?

This is merely a suggestion.

See also #277

**Comment by lechten** [comment]
I tried to rebase my fork, but things did not work for me as can be seen in issue #341.

**Comment by lechten** [comment]
@yjwen What do you think about joining our efforts?  What do you think about issue #341?

**Comment by podiki** [comment]
I see @yjwen is active again; are there any plans to unite or somehow combine the now separate org reveal packages?

**Comment by yjwen** [comment]
I saw @lechten 's pull request. Unfortunately, there are too many conflicts to resolve, becase too many things changed since I was absent. :) I might need somewhile to clean the conflicts.

**Comment by podiki** [comment]
Understandable that you and @lechten's packages have diverged a bit so it is not a simple merge, but as a user I hope they might be reunited in the near future as it doesn't seem to fundamentally need a new fork. And with two maintainers there is less chance of big gaps in development. Anyway, thanks to both of you for your hard work!

**Comment by yjwen** [comment]
Most of other pending issues fixed or cleared. I guess ox-reveal is up-to-date. Please forgive me for closing this merging request because of that too many confilcts. 

By the way, any joint development is welcome. Just let me know how.
