### ISSUE TITLE
Use data-noescape by default

### ISSUE THREAD

**Issue by ivanperez-keera** [yjwen/org-reveal#351]
I use `mark`s a lot, so I always need to add, before every `BEGIN_SRC`:

```
#+ATTR_REVEAL: :code_attribs data-noescape
```

Is there any way of making this the default?

**Comment by yjwen** [comment]
No way yet. But, if you are using org mode with version < 9.2, I'd like to suggest create a short-cut key for that case. Evaluate the following expression in emacs first.
`(add-to-list 'org-structure-template-alist
	     '("S" "#+ATTR_REVEAL: :code_attribs data-noescape\n#+BEGIN_SRC\n\?\n#+END_SRC"))`
Then in an org buffer, type `<S` and press tab, the attribute and the source block should have been expanded.

Add the above expression to your .emacs to make it default for you.
