### ISSUE TITLE
Line numbering on SRC blocks doesn't work with highlightjs

### ISSUE THREAD

**Issue by nikclayton** [yjwen/org-reveal#352]
If you use highlightjs by:

```
#+REVEAL_PLUGINS (highlight ...)
```

and export a SRC block with line numbering,

```
#+BEGIN_SRC javascript -n
alert("foo");
#+END_SRC
```
the span for the line number shows up in the output as literal text. I.e., on the slide it renders as:

```
<span class="linenr">1: </span>alert("foo");
```

instead of the expected

```
1: alert("foo");
```

The generated HTML is:

```
<div class="org-src-container">

<pre><code class="javascript" ><span class="linenr">1: </span>alert("foo");
</code></pre>
</div>
```

If I hand edit the HTML and move the span to before the code block, like so:

```
<div class="org-src-container">

  <pre><span class="linenr">1: </span><code class="javascript" >alert("foo");
</code></pre>
</div>
```

this almost works, except the line number appears on a line by itself because the style for ".reveal pre code" has display:block

**Comment by yjwen** [comment]
Done. Code updated to avoid the unnecessary HTML tag for highlight.js
