### ISSUE TITLE
MathJax CDN Shutdown Transition 

### ISSUE THREAD

**Issue by jarvisschultz** [yjwen/org-reveal#353]
The `org-reveal-mathjax-url` should likely use an updated URL. The [current value](https://github.com/yjwen/org-reveal/blob/1cdd088ec5fab631c564dca7f9f74fd3e9b7d4d4/ox-reveal.el#L275-L279) throws warnings in Chrome's debugger about the MathJax CDN being shut down. You can [read more here](https://www.mathjax.org/cdn-shutting-down/). Following that migration guide, I've updated my value to be:

    https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

**Comment by yjwen** [comment]
MathJax CDN URL updated by your suggestion by 8550aaa . Thanks for the information.
