### ISSUE TITLE
Fragmentation with source code blocks

### ISSUE THREAD

**Issue by dscole** [yjwen/org-reveal#354]
I would like to be able to have incrementally revealed source code blocks. I was hoping I could do something like that:

```
* Some Slide
#+ATTR_REVEAL: :frag (appear)
#BEGIN_SRC c++
void foo1();
#END_SRC
#BEGIN_SRC c++
void foo2();
#END_SRC
```

But for some reason when I do this, `foo2()` actually shows up first. To get around it I currently do:
```
* Some Slide
#+ATTR_REVEAL: :frag (appear)
#BEGIN_SRC c++
void foo1();
#END_SRC
#+ATTR_REVEAL: :frag (appear)
#BEGIN_SRC c++
void foo2();
#END_SRC
```

**Comment by yjwen** [comment]
That is defined by the org mode syntax. One attribute is effective only for one syntax item, either a paragraph, a table or a source block. In order to make two source blocks to be fragmented, two `#+ATTR_REVEAL:` lines are necessary. I am sorry org-reveal cannot break the syntax limitation.
