### ISSUE TITLE
proposed keyword #+REVEAL_TITLE_SLIDE

### ISSUE THREAD

**Issue by VladimirAlexiev** [yjwen/org-reveal#358]
Many people want to typeset their title slide using some complex HTML.
Ideally, with some newlines so it can be readable, eg:
```org
#+REVEAL_TITLE_SLIDE: <p class='center'><img src='../ontotext.png' style='width:506px'/></p>
#+REVEAL_TITLE_SLIDE: <h2>%t</h2><h4>%a</h4><h3>SWIB'16, Bonn, Germany, %d</h3>
#+REVEAL_TITLE_SLIDE: <p class='center'><a href='http://rawgit2.com/VladimirAlexiev/my/master/pres/20161128-rdfpuml-rdf2rml/index.html'>2D presentation</a>: 
#+REVEAL_TITLE_SLIDE: <a href='javascript:Reveal.toggleOverview()'>O for overview</a>,
#+REVEAL_TITLE_SLIDE: <a href='../reveal-help.html' target='_blank'>H for help</a>.</p>
#+REVEAL_TITLE_SLIDE: <p class='center'><a href='http://rawgit2.com/VladimirAlexiev/my/master/pres/20161128-rdfpuml-rdf2rml/index-full.html'>Continuous HTML</a></p>
```
Issues #283, #280, #272, #209, #205 talk about this problem and get advise not to use spaces (!?!) or to set a local variable inside the file (which is unsafe).

```elisp
(describe-variable 'org-export-options-alist)
```
describes the difference between a KEYWORD (as above) and an OPTION (as "reveal_title_slide").
There used to be a keyword `#+REVEAL_TITLE_SLIDE_TEMPLATE` 
but unfortunately @yjwen has decided to go with an OPTION, which is **not appropriate** for long strings: [ox-reveal.el#L66](https://github.com/yjwen/org-reveal/blob/master/ox-reveal.el#L66)
```elisp
    (:reveal-title-slide nil "reveal_title_slide" org-reveal-title-slide t)
```
I propose to change this to:
```elisp
    (:reveal-title-slide "REVEAL_TITLE_SLIDE" "reveal_title_slide" org-reveal-title-slide 'newline)
```
So that one can use repeating KEYWORDs to write multiple lines.

I gather from some comments here that @yjwen is not very active?
@lechten, could you implement this in your fork? Then I'll switch to your fork. Cheers!

**Comment by lechten** [comment]
My fork allows you to specify a file name after `#+REVEAL_TITLE_SLIDE:`. That file should contain HTML code with the usual escape sequences. I just documented this for `org-reveal-title-slide` (was only mentioned in my version of the Readme).

Is that good enough for you?

**Comment by VladimirAlexiev** [comment]
What's the benefit of using a separate file for this one slide?

I've hacked it using the existing variable (option) like this.
It computes the title slide using up to 3 buffer variables:
- place (of giving the presentation)
- filename (default index.html)
- filename for HTML export as continuous html (default index-full.html)

```elisp

(setq
 my-rawgit-base          "http://rawgit2.com/VladimirAlexiev/my/master/"
 my-rawgit-pres-base     (concat my-rawgit-base "pres/")
 my-org-filename-reveal  "index.html"
 my-org-filename-full    "index-full.html"
 )

(put 'my-org-place           'safe-local-variable 'stringp)
(put 'my-org-filename-reveal 'safe-local-variable 'stringp)
(put 'my-org-filename-full   'safe-local-variable 'stringp)

;; https://github.com/yjwen/org-reveal/issues/358: no #+REVEAL_TITLE_SLIDE so we hack it
(defadvice org-reveal-export-to-html (before title-slide activate)
  "Set org-reveal-title-slide from to a piece of HTML, including:
ontotext.png, TITLE, AUTHOR, my-org-place, DATE, 
links to Overview and Help,
link to my-org-filename-reveal (default index.html), my-org-filename-full (default index-full.html),
link to my publications"
  (let ((place (if (boundp 'my-org-place)
                   (concat my-org-place ", ") ""))
        (folder-base (concat my-rawgit-pres-base (file-name-nondirectory (directory-file-name (file-name-directory (buffer-file-name)))) "/")))
    (setq org-reveal-title-slide
          (concat
           "<p class='center'><img src='../ontotext.png' style='width:506px'/></p><p/><p/>"
           "<h2>%t</h2><h3>%a</h3><h4>" place "%d</h4>"
           "<p class='center'>"
           "<a href='" folder-base my-org-filename-reveal "'>2D presentation</a>: "
           "<a href='javascript:Reveal.toggleOverview()'>O for overview</a>, "
           ;;"<a href='../../reveal-help/reveal-help.html' target='_blank'>H for help</a>.</p>"
           "? for help.</p>"            ; builtin
           ;; "Proudly made in plain text with "
           ;; "<a href='https://github.com/hakimel/reveal.js/'>reveal.js</a>, "
           ;; "<a href='https://github.com/yjwen/org-reveal'>org-reveal</a>, "
           ;; "<a href='http://orgmode.org'>org-mode</a> and "
           ;; "<a href='http://www.gnu.org/s/emacs/'>emacs</a>.</p>"
           "<p class='center'>"
           "<a href='" folder-base my-org-filename-full "'>Continuous HTML</a>. "
           "<a href='" my-rawgit-base "index.html'>Publications</a></p>"
           ))))
```

And then in org:
```org
# -*- my-org-place: "SWIB'16, Bonn, Germany" -*-
#+TITLE: RDF by Example: rdfpuml for True RDF Diagrams, rdf2rml for R2RML Generation
#+DATE: 2016-11-29
```

**Comment by VladimirAlexiev** [comment]
#59 asks a similar thing for `#+REVEAL_EXTRA_JS`

**Comment by lechten** [comment]
Concerning the benefit: I wanted to keep HTML code in HTML files, [like this one](https://gitlab.com/oer/emacs-reveal/blob/master/title-slide/csos.html).

Concerning your request: My fork contains the following line.
```
(:reveal-title-slide "REVEAL_TITLE_SLIDE" nil org-reveal-title-slide t)
```

Personally, I don't need the `t` and could replace that with `'newline`. How likely is it that others rely on `t`? Shall we just try?

So far, I did not need `REVEAL_EXTRA_JS`. However, `org-reveal-external-plugins` also accepts a filename in my case...

**Comment by lechten** [comment]
I just changed my fork.

#59 is different because that proposes a change from string to list, which I find dangerous.
