### ISSUE TITLE
Headings with UNNUMBERED property gets broken slide id (slide-sec-)

### ISSUE THREAD

**Issue by joonro** [yjwen/org-reveal#360]
This issue is related to #339 and #345. I think it is stemming from this part: https://github.com/yjwen/org-reveal/blob/1cdd088ec5fab631c564dca7f9f74fd3e9b7d4d4/ox-reveal.el#L441-L443

It seems whenever a property does not have a number (via `UNNUMBERED` property set to `t`, for example), `ID`, or `CUSTOM_ID`, then the the id default to `slide-sec-` without a number at the end.

I think in such a case, it should grab the headline itself and use it to construct the slide id.

**Comment by vonpupp** [comment]
Same problem here. I even have `ID` properties and I am having the same issue.

I have also noticed that after a `#+REVEAL: split` I get back to the main page instead of continuing with the rest of the slides.

I didn't understand the `UNNUMBERED`

**Comment by lechten** [comment]
The package [org-re-reveal](https://gitlab.com/oer/org-re-reveal) contains a variant for slide IDs which might work for you.

Splitting also works differently with `org-re-reveal`.

**Comment by yjwen** [comment]
Use the org-export-get-reference for slide id, instead of section numbers, so as to be consistent with ox-html.

**Comment by joonro** [comment]
@yjwen Thank you so much! I'm very glad that you are back. :)

**Comment by joonro** [comment]
Hi @yjwen, I think the recent change by 6d6e4b5 actually broke the persistent slide id by removing `section_number` and `(org-element-property :ID headline)` in lines 442 and 443. I guess that `(org-export-get-reference headline info)` does not return a persistent ID. Would it be possible to add `section_number` and `(org-element-property :ID headline)`?

**Comment by yjwen** [comment]
Yes. Using `(org-export-get-reference ...)` is to be consistent with ox-html's TOC, otherwise, the TOC links will be broken. Reveal.js has provided a consistent links like `#/1/1` for sections numbers [here](https://github.com/hakimel/reveal.js/#internal-links). Cusmized ID can be specified by the `:CUSTOM_ID:` property.

**Comment by joonro** [comment]
Thanks a lot for the quick reply. I understand --- so I think it needs to be fixed at the `(org-export-get-reference ...)` level then. I found an [attempt](https://github.com/alphapapa/unpackaged.el#export-to-html-with-useful-anchors) to have more useful and persistent anchors with `(org-export-get-reference ...)` so I will try it.

**Comment by yjwen** [comment]
You are welcome. Cheers :)

**Comment by joonro** [comment]
:) and I'm happy to report that [export-to-html-with-useful-anchors](https://github.com/alphapapa/unpackaged.el#export-to-html-with-useful-anchors) seems to be working well.

**Comment by yjwen** [comment]
What amazing and informative code there!
