### ISSUE TITLE
reveal_width and reveal_height type is integer only

### ISSUE THREAD

**Issue by kspurgin** [yjwen/org-reveal#371]
There should be some mechanism for passing percentage-based width and height from org-mode through to Reveal.initialize:

width: "95%",
height: "95%"

The following fails on export with a wrong-type-argument
#+OPTIONS: reveal_width:"95%" reveal_height:"95%"

**Comment by lechten** [comment]
You can do that in org-re-reveal: https://gitlab.com/oer/org-re-reveal/blob/master/CHANGELOG.org

**Comment by kspurgin** [comment]
Thanks. Didn't know about org-re-reveal. Will check it out.

**Comment by yjwen** [comment]
Also enabled in ox-reveal.
