### ISSUE TITLE
Add "reveal_hash" option to #+OPTIONS for anchor navigation

### ISSUE THREAD

**Issue by sigistardust** [yjwen/org-reveal#376]
I would like to activate the navigation with anchors between slides. For that, I need the reveal.js configuration `hash` set to `true`, so that the slide numbers are added to the URL hash. See here for more information: [https://github.com/hakimel/reveal.js#configuration](https://github.com/hakimel/reveal.js#configuration)
Would it be possible to add that option for the Reveal.js function to org-reveal?
In case I am missing some easier configuration for that, please let me know. Thank you!

**Comment by yjwen** [comment]
I am working on it. Since reveal.js has added much more options, I'd like to change the way org-reveal specify those options to be a direct options string, so that one can freely embed new options.

**Comment by sigistardust** [comment]
That sounds great, thank you!

**Comment by yjwen** [comment]
Done. Use `#+REVEAL_INIT_OPTIONS: hash: true` to enable the URL hash.

**Comment by sigistardust** [comment]
Great, thank you very much!
