### ISSUE TITLE
Two bibliography slides

### ISSUE THREAD

**Issue by johbra** [yjwen/org-reveal#378]
The last line of my org file is something like that:
`* bibliography:referenzen.bib`
Since I am using reveal.js-3.8.0 I get two bibliography slides instead of one at the end of the slide deck.
Any hints what's going wrong?

Johannes

**Comment by yjwen** [comment]
I cannot reproduce locally. Could you please give me a minimum exported org file and the exported HTML file that shows up with two bibliography slides?

**Comment by johbra** [comment]
I’m not sure what you mean by „exported org file“.

**Comment by yjwen** [comment]
I mean the org file and the exported HTML.发自我的华为手机-------- 原始邮件 --------主题：Re: [yjwen/org-reveal] Two bibliography slides (#378)发件人：johbra 收件人：yjwen/org-reveal 抄送：Yujie Wen ,Comment I’m not sure what you mean by „exported org file“.











—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/yjwen/org-reveal/issues/378?email_source=notifications\u0026email_token=ABATH5TUMIZA6VDKUZYTHL3QBM5SVA5CNFSM4IGSODM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD25LA4Y#issuecomment-515551347",

"url": "https://github.com/yjwen/org-reveal/issues/378?email_source=notifications\u0026email_token=ABATH5TUMIZA6VDKUZYTHL3QBM5SVA5CNFSM4IGSODM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD25LA4Y#issuecomment-515551347",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by johbra** [comment]
Okay, that’s exactly what I sent to you with my previous mail

Am 27.07.2019 um 08:26 schrieb Yujie Wen <notifications@github.com<mailto:notifications@github.com>>:

I mean the org file and the exported HTML.发自我的华为手机-------- 原始邮件 --------主题：Re: [yjwen/org-reveal] Two bibliography slides (#378)发件人：johbra 收件人：yjwen/org-reveal 抄送：Yujie Wen ,Comment I’m not sure what you mean by „exported org file“.





—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/yjwen/org-reveal/issues/378?email_source=notifications\u0026email_token=ABATH5TUMIZA6VDKUZYTHL3QBM5SVA5CNFSM4IGSODM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD25LA4Y#issuecomment-515551347",
"url": "https://github.com/yjwen/org-reveal/issues/378?email_source=notifications\u0026email_token=ABATH5TUMIZA6VDKUZYTHL3QBM5SVA5CNFSM4IGSODM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD25LA4Y#issuecomment-515551347",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yjwen** [comment]
I didn't find any attachment from the mail. Could you please attach or paste the files here?

**Comment by johbra** [comment]
Title


.underline { text-decoration: underline; }








    if( window.location.search.match( /print-pdf/gi ) ) {
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = './reveal.js/css/print/pdf.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    }






TitleJohannes BrauerCreated: 2019-07-26 Fri 20:06



Slide

cite: Wali2016)





Literaturverzeichnis
[Wali2016] Wali, Mastering Clojure : understand the philosophy of the Clojure  language and dive into its inner workings to unlock  its advanced features, methodologies, and  constructs, Packt Publishing (2016).



Literaturverzeichnis
[Wali2016] Wali, Mastering Clojure : understand the philosophy of the Clojure  language and dive into its inner workings to unlock  its advanced features, methodologies, and  constructs, Packt Publishing (2016).





// Full list of configuration options available here:
// https://github.com/hakimel/reveal.js#configuration
Reveal.initialize({

controls: true,
progress: true,
history: false,
center: true,
slideNumber: 'c',
rollingLinks: false,
keyboard: true,
overview: true,

theme: Reveal.getQueryHash().theme, // available themes are in /css/theme
transition: Reveal.getQueryHash().transition || 'slide', // default/cube/page/concave/zoom/linear/fade/none
transitionSpeed: 'default',
multiplex: {
    secret: '', // null if client
    id: '', // id, obtained from socket.io server
    url: '' // Location of socket.io server
},

// Optional libraries used to extend on reveal.js
dependencies: [
,
 { src: './reveal.js/lib/js/classList.js', condition: function() { return !document.body.classList; } },
 { src: './reveal.js/plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
 { src: './reveal.js/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
 { src: './reveal.js/plugin/zoom-js/zoom.js', async: true, condition: function() { return !!document.body.classList; } },
 { src: './reveal.js/plugin/notes/notes.js', async: true, condition: function() { return !!document.body.classList; } }]
});


Am 27.07.2019 um 17:47 schrieb Yujie Wen <notifications@github.com>:I didn't find any attachment from the mail. Could you please attach or paste the files here?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yjwen** [comment]
OK. I have reproduced the issue. I need sometime to figure out what is wrong.

**Comment by yjwen** [comment]
It looks like bibliography is created by org-ref automatically, if it is enabled, before exporting to HTML or reveal.js, in which case the `org-reveal--insert-bibliography` introduced by #338 creates a redundant bibliography slide.

I am going th remove that function. Bibliography should be taken care at the pre-export stage, not by ox-reveal.

**Comment by johbra** [comment]
Great, it works

Joh.

Am 28.07.2019 um 18:01 schrieb Yujie Wen <notifications@github.com<mailto:notifications@github.com>>:


Closed #378<https://github.com/yjwen/org-reveal/issues/378> via 8f38746<https://github.com/yjwen/org-reveal/commit/8f3874688e70dcb02663260855d691458a93dc81>.
