### ISSUE TITLE
Feature request: Line spacing

### ISSUE THREAD

**Issue by phaebz** [yjwen/org-reveal#38]
I could not find anything about it in the docs.

It would be nice to be able to adjust the line spacing for lines in listings.

**Comment by drscotthawley** [comment]
Found this issue after noting that nothing I tried had any effect, e.g. using a custom CSS file to sett padding and margin as in [this SE answer](https://stackoverflow.com/questions/1263074/how-do-i-reduce-the-vertical-space-between-list-items-in-an-unordered-list) had no effect:


`li { margin: 0; padding: 0em; }`

The correct usage is instead

`.reveal li { margin: 0; padding: 0em}`
