### ISSUE TITLE
Customing `navigationMode`

### ISSUE THREAD

**Issue by matthew-piziak** [yjwen/org-reveal#380]
How can one set `navigationMode` to `linear`? 

Or in general, can one pass arbitrary arguments to `Reveal.initialize` through this package? Should this be done through `org-reveal-extra-js`?

**Comment by yjwen** [comment]
Please add the following option line
```
#+REVEAL_INIT_OPTIONS: navigationMode: 'linear'
```

**Comment by matthew-piziak** [comment]
@yjwen brilliant, thank you!
