### ISSUE TITLE
Speaker notes with lowercase begin_notes does not get recognized

### ISSUE THREAD

**Issue by joonro** [yjwen/org-reveal#381]
Hi,

It seems recent versions of org-mode use lower case characters for special notes. That is, 

```org
#+begin_notes

#+end_notes
```

instead of 

```org
#+BEGIN_NOTES

#+END_NOTES
```

and it seems org-reveal only correctly processes uppercase ones as speaker notes (exported as  `<aside class="notes">`, but not lowercase ones (exported as `<div class="notes">`).

I'm using org `9.2.6` with Emacs `GNU Emacs 26.2 (build 1, x86_64-w64-mingw32)`

As always, thank you for the great package!

**Comment by yjwen** [comment]
Done. Should be working with lower case notes.

**Comment by joonro** [comment]
Thank you very much!
