### ISSUE TITLE
speaker notes shows up as raw html 

### ISSUE THREAD

**Issue by maxandersen** [yjwen/org-reveal#382]
using the Readme.org from this repo I do the export to html and open browser presses 's' and this is what I get:

![2019-09-21_00-47-56](https://user-images.githubusercontent.com/54129/65362894-7c50d780-dc09-11e9-9287-0bf529034a54.png)

Any idea what is going wrong here ?

**Comment by yjwen** [comment]
Cannot reproduce the issue by my local setttings. What is the version of reveal.js?

**Comment by maxandersen** [comment]
using https://cdn.jsdelivr.net/npm/reveal.js directly. so Latest ?

**Comment by yjwen** [comment]
I see. Using an online reveal.js does show a raw HTML note page. I don't know the reason. But I would suggest to use a local installation of reveal.js instead. That should work.

**Comment by yjwen** [comment]
I see. Using an online reveal.js does show a raw HTML note page. I don't know the reason. But I would suggest to use a local installation of reveal.js instead. That should work.

**Comment by vincentbernat** [comment]
Using http://cdn.rawgit.com/hakimel/reveal.js/3.8.0/ works around this issue.
