### ISSUE TITLE
Slides merged into the background

### ISSUE THREAD

**Issue by treymerkley** [yjwen/org-reveal#386]
Hey thanks for this! It's a great, modern replacement for Beamer. 

However, I'm running into a problem, which may well be user error: When I export, my sides become images embedded in the background, and the only functional slides are the title slide and the TOC. 

I'm running spacemacs-develop, using standard melpa as my install base, so it should be up to date with master.

Everything is here:
https://github.com/treymerkley/presentations/tree/master/Techlahoma%20Python%20GUI%20Talk

**Comment by treymerkley** [comment]
So the offending line in the HTML file is `<section:t>`. Once this is removed, the slides function as expected. 

However, I just realized that the issue I need to file is *most likely* with oer's package, so I'll close this and open there, thanks.

**Comment by yjwen** [comment]
No problem. Glad to know you are happy with org-mode + reveal.js, no matter it is about this repository. :)
