### ISSUE TITLE
Section 4.9 Slide Number :: Does not work

### ISSUE THREAD

**Issue by alhassy** [yjwen/org-reveal#387]
The README says there should be page numbers by default, which is not the case.

I've added to the README.org

```
#+OPTIONS: reveal_slide_number:h/v
```

But reloading my setup still does not yield page numbers.

For a while, my current work around is to add the following to my Org file:

```
* Extra CSS :ignore:
#+BEGIN_EXPORT html
<style>

.reveal .slide-number {
  font-size: 34pt;
  color: #ff2D00; }

</style>
#+END_EXPORT
```

But now even this does not work.

**Comment by yjwen** [comment]
That method is out-of-date. Readme.org has been updated with the current proper way for slde numbering. Please check it out at [here](https://github.com/yjwen/org-reveal#slide-numbering).
