### ISSUE TITLE
Info on including images is missing

### ISSUE THREAD

**Issue by m-cat** [yjwen/org-reveal#390]
Is it just me or does the readme not mention the common use case of adding a regular image?

I eventually found instructions on a [third-party website](https://nwidger.github.io/blog/post/making-a-reveal.js-presentation-with-org-reveal/)... this seems like basic information to me.

**Comment by yjwen** [comment]
Please check [The Org Manual section](https://orgmode.org/manual/Images-and-tables.html) on inserting images.
