### ISSUE TITLE
Replacement for obsolete keywords and variables?

### ISSUE THREAD

**Issue by gugutz** [yjwen/org-reveal#392]
My presentation started opening a "ox-reveal hints" buffer informing that some options i use are now obsolete, like REVEAL_TRANS and REVEAL_MARGIN

But i cant find the new keywords to replace those options

How am i supposed, for instance, to select the global transition effect if i cant use REVEAL_TRANS anylonger?

Where do i find the new options so i can stop using the deprecated ones?

**Comment by yjwen** [comment]
All the obsolete options and variables are replaced by `#+REVEAL_INIT_OPTIONS:` following by options recognized by reveal.js, which can be found at [here](https://github.com/hakimel/reveal.js/#configuration).
For specifying transition, please refer to the following line:
```
#+REVEAL_INIT_OPTIONS: transition:'zoom'
```
