### ISSUE TITLE
Update documentation for correct variable name for reveal.js root directory

### ISSUE THREAD

**Issue by thecountoftuscany** [yjwen/org-reveal#399]
The `Readme.org` for this project shows the variable for reveal.js directory to be `org-reveal-root`. However, setting this variable has no effect. On looking at the variables list in emacs's `M-x describe-variable RET org-reveal-root`, I found the variable `org-re-reveal-root`, which, upon setting up, works as expected.

**Comment by lechten** [comment]
The packages `org-reveal` and `org-re-reveal` do both exist. It seems that you are reading `Readme.org` from the former but using the latter. 

[Org readme](https://gitlab.com/oer/org-re-reveal/blob/master/Readme.org) of `org-re-reveal`, [generated HTML](https://oer.gitlab.io/org-re-reveal/Readme.html)

**Comment by thecountoftuscany** [comment]
Sorry for the confusion and thanks for clearing that up!
