### ISSUE TITLE
Trace org-html-checkbox

### ISSUE THREAD

**Issue by yjwen** [yjwen/org-reveal#40]
Now, the argument definition of ```org-html-checkbox``` in the master branch and the latest release (8.2.5h) differ from each other. So Org-reveal's codes are now trying both type of arguments so as to work for both Org-mode versions.

This issue is filed to trace the ```org-html-checkbox``` inconsistency. Once it become consistent, Org-reveal should call ```org-html-checkbox``` with the correct arguments only, instead of trying some other arguments.

**Comment by xor3** [comment]
Mark.
With org-mode version 8.2.10,  org-html-checkbox should be called with one argument.

**Comment by yjwen** [comment]
Closed since Org-mode in MELPA has been upgraded to 8.3 versions. The arguments of `org-html-checkbox` is consistent.
