### ISSUE TITLE
External Link to org files

### ISSUE THREAD

**Issue by rzr** [yjwen/org-reveal#402]
How to link to actual org file ?

I noticed that: 
```org
- Sources: [[./index.org]]
```

Is exported as:
```html
<li> Sources: <a href="index.html">...
```

**Comment by yjwen** [comment]
Set variable `org-html-link-org-files-as-html` to `nil` to disable the conversion when exporting to HTML, as noted in orgmode's document [here](https://orgmode.org/manual/Links-in-HTML-export.html#Links-in-HTML-export).
