### ISSUE TITLE
Exporting to single file does not work

### ISSUE THREAD

**Issue by tamasgal** [yjwen/org-reveal#403]
I am not sure if this is related to https://github.com/yjwen/org-reveal/issues/395 but although my header of the `org` file has this:

```
#+OPTIONS: num:nil toc:nil reveal_width:1400 reveal_height=1000 reveal_single_file:t
```

It does not turn the images into base64 encoded strings, but keeps the links as they are.

I am using the `org-re-reveal-export-to-html-and-browse` function but honestly I am a bit confused which one's the right package. Is this even using `org-reveal`?

(I am using Doom Emacs)

**Comment by yjwen** [comment]
It looks like your are using org-re-reveal, a package forked from org-reveal but now an independent one. Please refer to org-re-reveal's [project page](https://gitlab.com/oer/org-re-reveal) for helps.

Regards,
Yujie
