### ISSUE TITLE
Cache fonts

### ISSUE THREAD

**Issue by rzr** [yjwen/org-reveal#405]
Hi, 

I made a makefile to cache online resources and noticed that some fonts (google) are still downloaded from internet, is there any way to cache them? (may this issue forwarded to reveal.js?)

If not I will try to patch on the fly reveal.js using this base makefile:

https://github.com/yjwen/org-reveal/pull/404

**Comment by yjwen** [comment]
Yes, I think it should be reveal.js (or even the browser?)'s matter about managing fonts, but not this exporter. Maybe you can find an answer at reveal.js page.
