### ISSUE TITLE
noexport option only for reveal?

### ISSUE THREAD

**Issue by tamasgal** [yjwen/org-reveal#407]
The `:noexport:` tag which can be added to a headline skips the tree when exported to any format.

Is there a way to only skip the export for reveal slides?

I often do analysis in a single org file which I want to export as PDF with all the details, but only show some parts of the document as a presentation.

**Comment by tamasgal** [comment]
I ended up with this solution (triggered by the author of `org-re-reveal`) which works well.

To change the settings, the corresponding code block needs to be executed to set `org-export-exclude-tags` properly. If the `Presentation` mode is toggled, all trees (or items) tagged with `noexportpresentation` are skipped when exporting.

```elisp
* Export Options                                         :noexportpresentation:
** Default
#+BEGIN_SRC elisp
(setq org-export-exclude-tags '("noexport"))
#+END_SRC

** Presentation
#+BEGIN_SRC elisp
(setq org-export-exclude-tags '("noexport" "noexportpresentation"))
#+END_SRC

#+RESULTS:
| noexport | noexportpresentation |
```

**Comment by joonro** [comment]
This is another solution in case you want a permanently different behavior. With the following, subtrees with `slideonly` will only be exported when the exporting backend is `reveal` or `beamer`, and subtrees with `handoutonly` will only be exported when the exporting backend is `latex` or `rst`. You can modify the backend specification to suit your needs.

```emacs-lisp
(defun org/parse-headings (backend)
  "Remove every headline with certain tags in the
  current buffer. BACKEND is the export back-end being used, as
  a symbol.

  "

  ; Remove subtrees with :slideonly: tag unless a slide export backend is used
  (unless (member backend '(beamer reveal))
      (org-map-entries
       (lambda ()
         (progn
           (org-narrow-to-subtree)
           (org-cut-subtree)
           (widen)
           ))
       "+slideonly"))

  ; Remove subtrees with :handoutonly: tag unless a handout export backend is used
  (unless (member backend '(latex rst))
      (org-map-entries
       (lambda ()
         (progn
           (org-narrow-to-subtree)
           (org-cut-subtree)
           (widen)
           ))
       "+handoutonly"))
)

(add-hook 'org-export-before-parsing-hook 'org/parse-headings)

```

**Comment by tamasgal** [comment]
Thanks, that's interesting! I need to study it a bit to understand what's going on though 😉 

It would be nice if this functionality could find it's way into `org-reveal`. I usually try to keep the customisation to a minimum to be able to collaborate with others easily and setting a minimum version number on e.g. `org-reveal` is easier than sharing multi-line-hooks.

What do you think? Would you mind opening a pull request?

**Comment by joonro** [comment]
I think it is a good idea, and I agree with you that less customization is better for portability. Unfortunately I'm not familiar with the inner working of org-reveal enough to actually incorporate this into the code at the moment. I can take a look when I have a chance.

FYI, you do something specific to reveal like the code below (`revealonly` tag). Basically it removes all the subtrees with a specific tag, unless specified backend(s) are used. The removing subtree part (`(org-narrow-to-subtree) (org-cut-subtree) (widen)`) is ugly but when I wrote the code, that was the only way I could come up with to consistently remove a subtree in exporting.

```emacs-lisp
(defun org/parse-headings-reveal-only (backend)
  "Remove every headline with revealonly tag in the
  current buffer. BACKEND is the export back-end being used, as
  a symbol.

  "

  ; Remove subtrees with :revealonly: tag unless the backend is reveal
  (unless (member backend '(reveal))
      (org-map-entries
       (lambda ()
         (progn
           (org-narrow-to-subtree)
           (org-cut-subtree)
           (widen)
           ))
       "+revealonly"))
)

(add-hook 'org-export-before-parsing-hook 'org/parse-headings-reveal-only)
```

**Comment by tamasgal** [comment]
To me it's still a bit magical (and full of parenthesis 😅 ), I hope I will catch up soon. (I switched to Emacs a few days ago, after being a hardcore Vim user for more than 20 years)

I guess I'll reopen the issue and hope that someone might jump in meanwhile...

Thanks for your input!

**Comment by yjwen** [comment]
Done. Please use tag `:noexport_reveal:` to skip headings for reveal.js only.

**Comment by joonro** [comment]
This is great! Thank you very much.

**Comment by tamasgal** [comment]
Amazing, thanks!
