### ISSUE TITLE
Add support for highlighting of specific code lines?

### ISSUE THREAD

**Issue by D4N** [yjwen/org-reveal#409]
Would it be possible to add support for reveal.js' highlighting of specific lines in the code via the `data-line-numbers` attribute that is passed to the `code` element (see: https://github.com/hakimel/reveal.js#line-numbers--highlights)?

If I understand the code correctly, then one "only" needs to inject the correct attribute into: https://github.com/yjwen/org-reveal/blob/aafedfd8052d1ac4b0ddf946b3258a3b5ae5bbbe/ox-reveal.el#L1043 The harder part is: how would one define the lines to be highlighted? I am unfortunately not familiar with org's datastructures, so no idea if one can add custom attributes there?

**Comment by yjwen** [comment]
Please insert line `#+ATTR_REVEAL: :code_attribs data-line-numbers="1|3"` before the source code block.

**Comment by D4N** [comment]
Thank you, didn't know this was working already!

In case anyone stumbles over this issue in the future, you can also specify ranges in the attribute:
```org
#+ATTR_REVEAL: :code_attribs data-line-numbers="1-3|5|8-12"
```
