### ISSUE TITLE
Source code blocks don't appear to respect :frag_idx

### ISSUE THREAD

**Issue by D4N** [yjwen/org-reveal#412]
Source code blocks can fragment, but I haven't figured out how to make them respect the `frag_idx` parameter. For example this org snippet:
``` org
#+ATTR_REVEAL: :frag (appear) :frag_idx 1
#+BEGIN_SRC python
class Server:
    def bind(self, port: int):
        ...
#+END_SRC

#+ATTR_REVEAL: :frag (appear) :frag_idx 2
bla
```
results in this HTML where the fragment index of the source code block is missing:
``` html
<div class="org-src-container">

<pre class="fragment (appear)"><code class="python" >class Server:
    def bind(self, port: int):
        ...
</code></pre>
</div>

<p data-fragment-index="2" class="fragment (appear)">
bla
</p>
```

Am I missing something here or is that not implemented?

**Comment by yjwen** [comment]
Was not implemented. Done now.

**Comment by D4N** [comment]
Thank you very much! I greatly appreciate this package and your work!
