### ISSUE TITLE
replace-regexp-in-string: Wrong type argument: stringp, (ly-raw string "\"æ\"")

### ISSUE THREAD

**Issue by cryoguy** [yjwen/org-reveal#414]
I guess this happened very recently.  Reveajs export failed with the following error:
`replace-regexp-in-string: Wrong type argument: stringp, (ly-raw string "\"æ\"")`
anybody else has the same issue?

I am using: Arch Linux 5.5.7
Emacs 26.3 
Org-mode 9.3

**Comment by yjwen** [comment]
Didn't see this error recently. Could you please a minimum org file that can reproduce this error?

**Comment by cryoguy** [comment]
Thanks for your quick reply.  It turns out to be one of my bibtex entry with "æ" in the abstract section.  It worked before though.  I will ask around in helm-bibtex and /or org-ref circle. Thanks!

**Comment by cryoguy** [comment]
[https://github.com/andras-simonyi/citeproc-org/issues/9](url)    The problem is citeproc-org.   org-ref works!
