### ISSUE TITLE
New item list if ATTR_REVEAL is used

### ISSUE THREAD

**Issue by theldoria** [yjwen/org-reveal#42]
If I do something like this:

    - show bullet-points
    - show more bullet-points
    #+ATTR_REVEAL: :frag roll-in
    - one
    - by
    - one

I get the following html fragment:

    <ul class="org-ul">
    <li>show bullet-points
    </li>
    <li>show more bullet-points
    </li>
    </ul>
    <ul class="org-ul">
    <li class="fragment roll-in">one
    </li>
    <li class="fragment roll-in">by
    </li>
    <li class="fragment roll-in">one
    </li>
    </ul>

Which looks really ugly if rendered. I would rather expect to become one list:

    <ul class="org-ul">
    <li>show bullet-points
    </li>
    <li>show more bullet-points
    </li>
    <li class="fragment roll-in">one
    </li>
    <li class="fragment roll-in">by
    </li>
    <li class="fragment roll-in">one
    </li>
    </ul>

**Comment by yjwen** [comment]
I recently enhanced org-reveal to support different fragment style on list items. Please pull the latest master branch and refer to section of "List Fragments".

**Comment by titaniumbones** [comment]
is it possible to use a "none" frag style in a list?  so, e.g., 
```
#+ATTR_REVEAL: :frag (none none grow shrink roll-in fade-out)
- I am visible at the beginning
- me too
- I will grow
- I will shrink
- etc. 
- etc.
```
just wondering.

**Comment by yjwen** [comment]
Great suggestion. I think there should be `none`, for the sake of
completeness.

Let me do the fix.

2015-02-25 1:50 GMT+08:00 Matt Price <notifications@github.com>:

**Comment by yjwen** [comment]
Code updated. `none` is recognized as a list item's fragment style, means no fragment.

**Comment by titaniumbones** [comment]
Wow, great! thanks.
