### ISSUE TITLE
Broken links with reveal.js 4.0

### ISSUE THREAD

**Issue by coolmast** [yjwen/org-reveal#421]
With reveal.js version 4.0 the links to the css and js files must be changed from
```
reveal.js/css/reveal.css -> reveal.js/dist/reveal.css
reveal.js/css/theme/moon.css -> reveal.js/dist/theme/moon.css
reveal.js/js/reveal.js -> reveal.js/dist/reveal.js
```
For me, it's only working after these changes. I obtained the latest reveal.js version from github and followed the installation guide.

**Comment by billbrod** [comment]
I have the same problem, how did you fix it? Are there some org-reveal config options that allow you to change those links?

**Comment by danieljamesross** [comment]
Same here.

**Comment by yjwen** [comment]
Done. Will choose existing files from reveal.js 3.0 or 4.0 candidate file paths. Please pull the latest.

**Comment by danieljamesross** [comment]
Thanks for sorting!
