### ISSUE TITLE
CSS blocked due to MIME type...

### ISSUE THREAD

**Issue by danieljamesross** [yjwen/org-reveal#422]
When using the following `#+REVEAL_ROOT` from the README:

```org
#+REVEAL_THEME: Night
#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
```
I get the following error:

> The resource from “https://cdn.jsdelivr.net/npm/reveal.js/css/theme/Night.css” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff)

**Comment by danieljamesross** [comment]
Potentially this is related to #421

**Comment by yjwen** [comment]
It is difficult for org-reveal to determine the version of remote reveal.js. A customizable variable `org-reveal-reveal-js-version` is added for explicit specification of the reveal.js version. Set it to 4 for version 4.0, 3 for version 3.x and before, or `nil` to let org-reveal to guess the version, in which case, remote URLs are always assumed to be 4.0.
