### ISSUE TITLE
this repository doesn't correspond to the latest reveal.js

### ISSUE THREAD

**Issue by ropiron** [yjwen/org-reveal#423]
I downloaded the latest reveal.js (4.0.0) but this repository doesn't correspond to it. The error says "<script>  “~/reveal.js/lib/js/head.min.js”  failed to load ".  And The "head.min.js" was deleted from 3.8.0 version of reveal.js so I downloaded 3.7.0 and it worked.
I downloaded the different version of reveal.js from tag page " https://github.com/hakimel/reveal.js/tags "

**Comment by yjwen** [comment]
Please refer to #422 for the latest solution about reveal.js version mismatch.
