### ISSUE TITLE
Are plugins initialized properly ?

### ISSUE THREAD

**Issue by pascalfleury** [yjwen/org-reveal#425]
I tried to use the speaker notes plugin, that displays the upcoming slide when pressing 's'.

The current code that is produced looks like this:

```
<script src="reveal/js/reveal.js"></script>
<script>
Reveal.initialize({
 // [...some irrelevant config...]
},
dependencies: [
 { src: 'reveal/plugin/notes/notes.js', async: true, condition: function() { return !!document.body.classList; } }]
 // [... some other plugins removed...]
});
</script>

```

This does not seem to initialize the plugins properly. Nothing happens when pressing 's' during the presentation.

I modified the generated code from the docs of reveal.js itself, to this: 

```
<script src="reveal/js/reveal.js"></script>
**<script src="reveal/plugin/notes/notes.js"></script>**
 <script>
Reveal.initialize({
  // [...some irrelevant config...]
},
**plugins: [ RevealNotes ],**
dependencies: [
 { src: 'reveal/plugin/notes/notes.js', async: true, condition: function() { return !!document.body.classList; } }]
});
</script>

```

So forcing sync loading of the plugin Javascript and adding the plugin in the list of plugins to initialize makes it work.

Has this part changed recently in reveal.js and the ox-reveal is then outdated ?

**Comment by grzm** [comment]
I noticed this, too.I believe this is a version issue. I think the org-reveal currently supports only reveal.js 3. The current release of reveal.js is version 4. The plugin initialization changed between these versions. https://revealjs.com/upgrading/#plugin-registration

I munged the generated index.html so it matched version 4, and speaker notes worked.

Haven't gotten around to digging into updating org-reveal and submitting a PR yet, though.

**Comment by yjwen** [comment]
Code updated. Plugins should be working for reveal.js 4. Please pull the latest.

**Comment by pascalfleury** [comment]
Plugins work again, thank you!!!

Not sure if it is supposed to detect the version automatically though, as I needed to set the 
`#+REVEAL_REVEAL_JS_VERSION: 4`
in my file.

**Comment by yjwen** [comment]
It should be able to detect the version automatically, unless reveal.js is not in local folder. If you find any issue about the automatic version, please feel free to reopen this issue.
