### ISSUE TITLE
Not compatible with reveal.js version 4.X

### ISSUE THREAD

**Issue by Apteryks** [yjwen/org-reveal#426]
When trying to use org-reveal with reveal.js version 4.0.2 (latest), I got the following message:

`org-reveal--css-label: Cannot read ./reveal.js/css/reveal.css`

And the exported html didn't render.

The CSS files now have the 'scss' extension, like: `css/reveal.scss`.

**Comment by yjwen** [comment]
For reveal.js 4.0.2, the CSS should be dist/reveal.css. The latest org-reveal should be able to recognize local reveal.js 4.x install and switch to the updated CSS path automatically. If not, you can give an explicit version by either in buffer option `#+REVEAL_REVEAL_JS_VERSION: 4` or variable `org-reveal-reveal-js-version`.

**Comment by Apteryks** [comment]
Hello @yjwen! Thank you for your reply, it indeed works using a recent version. What probably happened was that I was using an earlier version of org-reveal, perhaps.

Anyhow, thank you for this useful package, and sorry for the noise!
