### ISSUE TITLE
reveal_data_state property has no effect

### ISSUE THREAD

**Issue by juanerasmoe** [yjwen/org-reveal#430]
The `reveal_data_state` property has no effect with reveal 4.0.2. From what I've been able to figure out, the default values for this property (alert, sooth, ...) were deprecated from reveal.js a while ago.

Apart from that, the same effect can be achieved with the `reveal_background` property, which is covered in the Readme document.

**Comment by yjwen** [comment]
Thanks for the reminding. I've removed the section about the obsolete `data-state`, but will keep the support in ox-reveal for a while for there might be 3.9.x users still.
