### ISSUE TITLE
Skip headings via tags

### ISSUE THREAD

**Issue by novoid** [yjwen/org-reveal#433]
Hi,

I know about `:noexport:` and `:noexport_reveal:` already. However, there are use-cases that require different sets of slides. For example, I'm conducting a lecture on the same subject for two different universities. One has twice as many hours than the other. It would be very cool to be able to define tags such as `:lecture1:` and `:lecture2:` and then **use an `org-reveal` feature where I'm able to define that for this export, only slides tagged with `:lecure2:` should be exported**.

Please note that standard org has a feature `SELECT_TAGS` (and also `EXCLUDE_TAGS`) which reflects this feature request. Unfortunately, org-reveal does not respect `SELECT_TAGS`.

**Comment by yjwen** [comment]
Hi,

  org-reveal does support both `SELECT_TAGS` and `EXCLUDE_TAGS`. Please check out with the following sample file.
```
#+EXCLUDE_TAGS: lecture2
#+SELECT_TAGS: lecture1

* Heading 1                                                        :lecture1:

Contents of heading 1

** Sub-heading 1.1
Contents of heading 1.1

* Heading 2                                                        :lecture2:

Contents of heading 2

** Sub-heading 2.1
Contents of heading 2.1
```

**Comment by novoid** [comment]
Sorry for the fuzz.
I might have gotten the property version wrong.

Your example with file-based settings works. For properties, I had to use following syntax to make it work as well:

```
* Top heading
:PROPERTIES:
:EXPORT_SELECT_TAGS: lecture1
:EXPORT_EXCLUDE_TAGS: lecture2
:END:

** Heading 1 [...]
[...]
```
