### ISSUE TITLE
Confusing generation of double section tags

### ISSUE THREAD

**Issue by olberger** [yjwen/org-reveal#434]
It seems to me that org-reveal generates double <section> tags for sections, the first only containing the second, which holds attributes and content.

It may be necessary for some conversion of arbitrary depth of org TOC to a 2D layout... but when a doc only has top-level slides, this is a bit misleading.

Thanks in advance.

**Comment by yjwen** [comment]
org-reveal generates double sections without the awareness about the final layout, and the redundant section won't disturb the final presentation. Let me keep it as it is because the conversion code is much simpler.
