### ISSUE TITLE
Wish: insert icons from a webfont without inserting html

### ISSUE THREAD

**Issue by D4N** [yjwen/org-reveal#440]
I have been using org-reveal for a few presentations lately and enjoy it a lot, thank you for creating and maintaining it!

I have one usability issue at the moment (that is probably rather me specific): I often insert icons from webfonts, e.g. fontawesome into my presentations, e.g. into lists. As far as I know, I have to then resort to using `#+REVEAL_HTML:` to insert the icon, e.g. `<i class="fab fa-github"></i>`. This works, but has the disadvantage, that it breaks lists (it is not easily possible to just insert the icon into a list entry without having to write the whole list in html).

Would it be possible to add a special directive, something along the lines of: `#+REVEAL_ICON: :fontawesome (fab fa-github)`? Or maybe something completely different, I am really not sure what would work best here.

**Comment by yjwen** [comment]
Please use `@@html:...@@` to embed raw html tags into paragraphs. Like
```
* Head
  * @@html: <i class="fa fa-camera-retro"></i>@@ fa-camera-retro
```

**Comment by D4N** [comment]
Yujie Wen <notifications@github.com> writes:

> Please use `@@html:...@@` to embed raw html tags into paragraphs. Like
> ```
> * Head
>   * @@html: <i class="fa fa-camera-retro"></i>@@ fa-camera-retro
> ```

Oh wow, I did not know that this was possible! Would you accept a PR
that adds this to the documentation?

**Comment by yjwen** [comment]
Embedding raw HTML content to org is a matter of org-mode's HTML exporter. Same trick applies when exporting to plain HTML pages than reveal.js presentation. I'd prefer org-reveal's document focusing on reveal.js specific issues. :)
