### ISSUE TITLE
Assigning HTML attributes to a header - possible?

### ISSUE THREAD

**Issue by dsjoho** [yjwen/org-reveal#441]
Hi,
How to assign e.g. a class to the heading generated by org-reveal?
Simple example is using the `r-fit-text` class from https://revealjs.com/layout/
I.e.
I want my generated heading to look like
`<h2 id="org-generated-id" class="my-specified-class">Heading text</h2>`

Is this possible? How? I have not been able to find this anywhere.
I know I can influence CSS on sections and use the id as well for directly targeting a heading, but in this case I need the class applied on the heading element. The toc-progress plugin also benefits from something similar.

**Comment by yjwen** [comment]
Yes, it is possible. It is the org-mode HTML exporter, which ox-reveal derives from, that exports the heading tags and corresponding classes. You can add a `HTML_HEADLINE_CLASS` property to specific headline to customize its `class=` attributes. Below is an example

```
* Heading 1
  :PROPERTIES:
  :HTML_HEADLINE_CLASS: voo
  :END:
```

Check the document [here](https://orgmode.org/manual/CSS-support.html#CSS-support)
