### ISSUE TITLE
Removing unneeded css from head

### ISSUE THREAD

**Issue by jenssss** [yjwen/org-reveal#442]
In the new version of reveal.js (4.0), the css for print pdf which is included from https://github.com/yjwen/org-reveal/blob/499c5777174dbc7318e3f32fd50357c2823b228a/ox-reveal.el#L652-L666 seems to no longer be necessary. See the reveal docs at https://revealjs.com/upgrading/#remove-print-css-from-%3Chead%3E. Would it be possible to remove it, or maybe add an option to not include it in exports for people using newer reveal.js?

**Comment by yjwen** [comment]
Done. Removed for reveal.js 4
