### ISSUE TITLE
Add Animations

### ISSUE THREAD

**Issue by adimit** [yjwen/org-reveal#443]
In order to add [auto animations](https://revealjs.com/auto-animate/) to code fragments, I'd need the following structure in the exported html:

```html
<section data-auto-animate>
  <pre data-id="my-code-fragment"><code>code 1</code></pre>
</section>
<section data-auto-animate>
  <pre data-id="my-code-fragment"><code>code 1 1</code></pre>
</section>
```

So I need to be able to set attributes on the section and the `pre` tag. I know how to set attributes on the `code` tag: using `#+ATTR_REVEAL: :code_attribs data-id="foo"` but that makes for a very disappointing animation.

Is it possible to set attributes on the `section` and the `pre` tag?

I could try to make a PR by the end of the week, if that functionality is not yet built in.

**Comment by yjwen** [comment]
Yes, `data-id` can be set to code blocks by `:code_attribs`. Just pushed a minor fix to let `:code_attribs` being available for org-mode native highlights.

Please use heading's `REVEAL_EXTRA_ATTR` property to customize `section` tag's attributes. For example.
```
* This is a head
  :PROPERTIES:
  :REVEAL_EXTRA_ATTR: data-auto-animate
  :END:

  Blabla 1.

#+ATTR_REVEAL: :code_attribs data-id="foo"
#+BEGIN_SRC c++
int main();
#+END_SRC


* This is a head
  :PROPERTIES:
  :REVEAL_EXTRA_ATTR: data-auto-animate
  :END:

  Blabla 1.

  Blabla 2.

#+ATTR_REVEAL: :code_attribs data-id="foo"
#+BEGIN_SRC c++
  int main()
  {
    return 0;
  }
#+END_SRC


```
