### ISSUE TITLE
Using numbers in source gives error: "face-attribute: Invalid face: normal"

### ISSUE THREAD

**Issue by juboba** [yjwen/org-reveal#444]
Trying to export to reveal
```
#+begin_src js
let index = 1
#+end_src
```
Shows `face-attribute: Invalid face: normal` in minibuffer (I didn't see anything else in the `*Messages*` buffer) and no output is produced.

Changing the number to a string
```
#+begin_src js
let index = '1'
#+end_src
```
or removing the language
```
#+begin_src
let index = 1
#+end_src
```

solves the problem, but of course neither solution is good.

I'm using Reveal `4.1.0` and `org-reveal` 499c5777174dbc7318e3f32fd50357c2823b228a.

**Comment by yjwen** [comment]
Cannot reproduce the error with reveal 4.1.0 and either the latest org-reveal or 499c577. HTML did exported. Not sure it is an issue with org-reveal. Could you please try to export it to plan HTML by `C-c C-e h h` to see if the same error exists?

**Comment by juboba** [comment]
@yjwen thanks for taking a look. Indeed exporting with `h h` also shows the same error.

**Comment by juboba** [comment]
I think this is a problem with Org's export to HTML. Someone else reported this here: https://emacs-china.org/t/org-html-export-to-html-invalid-face-normal/14677
