### ISSUE TITLE
Why do you include a structure template??

### ISSUE THREAD

**Issue by gonsie** [yjwen/org-reveal#446]
Why do you define a structure template (https://github.com/yjwen/org-reveal/blob/master/ox-reveal.el#L1518)? This configuration should not be included by the reveal package. Instead, it should be left to user to configure. At most, you could give instructions to users to include this.

It took me way too long to figure out why my `<n` shortcut wasn't working as expected ☹️

**Comment by yjwen** [comment]
Oh, sorry for the troubles... Yes, it should be left to user to configure. Org-reveal should not change that.

**Comment by gonsie** [comment]
Thank you for the quick fix and for maintaining such a great package!

**Comment by yjwen** [comment]
You are welcome, and glad org-reveal helps.
