### ISSUE TITLE
External third-party plugin support is broken

### ISSUE THREAD

**Issue by egorenar** [yjwen/org-reveal#448]
Hi,

i think third-party plugin support is broken.
No external plugins work. If i modify the produced HTML and add a couple of external plugins like `menu` or `verticator`,
everything works. But i can't bring ox-reveal to generate correct reveal.js code.

I think `org-reveal-plugin-scripts-4()` completely discards any external plugins found in `#+REVEAL_PLUGINS`
because `available-plugins` contains only plugins delivered with reveal.js.

This is my configuration:
```
(setq org-reveal-external-plugins
	'((menu . "{ src: '%splugin/menu/menu.js'}")
	  (verticator . "{ src: '%splugin/verticator/verticator.js'}")))
```

According to the docs of menu plugin a script block must be included (https://github.com/denehyg/reveal.js-menu):
`<script src="node_modules/reveal.js-menu/menu.js"></script>`

And yes, i installed all required third-party plugins.
Please take a look. Thank you.

Regards

**Comment by egorenar** [comment]
I tried org-re-reveal instead and it worked w/o issues.

**Comment by egorenar** [comment]
Thanks for the fix.
It probably makes sense to fix the example because it works a bit differently.
The menu plugin must have the title `RevealMenu`.

This works for me:
`#+REVEAL_PLUGINS: (highlight RevealMenu)`

`(setq org-reveal-external-plugins '((RevealMenu . "%splugin/menu/menu.js")`

**Comment by yjwen** [comment]
Just correct `menu` to `RevealMenu`. But I am confused about org-re-reveal's way. What is the difference of `menu` and `RevealMenu` in that export engine?

**Comment by egorenar** [comment]
> Just correct `menu` to `RevealMenu`. But I am confused about org-re-reveal's way. What is the difference of `menu` and `RevealMenu` in that export engine?

E.g. if i use your package and `menu` as symbol within `org-reveal-external-plugins` and `#+REVEAL_PLUGINS: (highlight menu)`, then i get this generated.
```
Reveal.initialize({
plugins: [RevealHighlight, menu],
...
});
```

This is incorrect, because menu plugin should be passed as `RevealMenu` to `Reveal.initialize`.
This is also why `org-re-reveal` uses an extra symbol within `org-re-reveal-plugin-config`.

With `org-reveal` package i need to use `RevealMenu` within `org-reveal-external-plugins` and also
`#+REVEAL_PLUGINS: (highlight RevealMenu)`.

Not sure what is the best way, but i find the org-re-reveal's way better and also doesn't break compatibility with reveal 3.0.

Regards
Alex

**Comment by yjwen** [comment]
Then I guess `menu` is the legacy name of `RevealMenu`, just as the builtin plugin `RevealZoom`'s legacy name `zoom`. I can add an auto-mapping from `menu` to `RevealMenu`, as that done for the builtin plugins.
