### ISSUE TITLE
how to make a grid layout?

### ISSUE THREAD

**Issue by nimble2005** [yjwen/org-reveal#453]
Hello, here is what bothers me:

suppose I have 8 figures to show in one slide and I want to show them in 2 rows, which means 4 figures (columns) in each row. How can I do that? Does it mean that I have to write my own .css stylesheet and use the command like 
`#+reveal_extra_css: my-grid-layout-stylesheet.css`
in the .org file?

I am a rookie to html and css, hope someone could help. THX!

**Comment by yjwen** [comment]
The simplest way is organizing the pictures in a table, if you don't care about the appearance.
```
* Heading 1

  | [[./hlevel.png]] | [[./hlevel.png]] | [[./hlevel.png]] | [[./hlevel.png]] |
  | [[./hlevel.png]] | [[./hlevel.png]] | [[./hlevel.png]] | [[./hlevel.png]] |
```
![image](https://user-images.githubusercontent.com/4273142/135595674-f7975046-ba40-449e-a6ca-20dabf3cebe6.png)

**Comment by nimble2005** [comment]
> The simplest way is organizing the pictures in a table, if you don't care about the appearance.
> 
> ```
> * Heading 1
> 
>   | [[./hlevel.png]] | [[./hlevel.png]] | [[./hlevel.png]] | [[./hlevel.png]] |
>   | [[./hlevel.png]] | [[./hlevel.png]] | [[./hlevel.png]] | [[./hlevel.png]] |
> ```
> 
> ![image](https://user-images.githubusercontent.com/4273142/135595674-f7975046-ba40-449e-a6ca-20dabf3cebe6.png)

Thanks! Thats brilliant! In the past few days I was trying to use .css file and it also worked. Anyway, thats a really nice way! THX!

**Comment by yjwen** [comment]
You are welcome.
