### ISSUE TITLE
Setting external Reveal.js plugins per org file

### ISSUE THREAD

**Issue by bzindovic** [yjwen/org-reveal#461]
Is it possible to set external Reveal.js plugins per file, without changing org-reveal-external-plugins in my init file?

At the moment, reveal.js-menu works only if I add it explicitly to org-reveal-external-plugins. Adding
`#+REVEAL_EXTERNAL_PLUGINS: {src: '%splugin/menu/menu.js'}`
as suggested in [this issue](https://github.com/yjwen/org-reveal/issues/254#issuecomment-514260950), has no effect.

P.S. I've made my local install of Reveal.js, I have set `#+REVEAL_ROOT` and have added reveal.js-menu to its plugin sub-folder.

**Comment by yjwen** [comment]
Buffer local plugins are not implemented yet for reveal.js 4.0. Doing now.
