### ISSUE TITLE
Adding extra JS code to initialize external plugins

### ISSUE THREAD

**Issue by bzindovic** [yjwen/org-reveal#462]
I'm using external plugin (reveal.js-menu) and I'd like to set its init options. I've tried the following:
`#+REVEAL_INIT_SCRIPT: menu:{themes:true, themesPath:'%sdist/themes'}`
but it doesn't seem to be exported. I've also tried the following but got practically the same output:
`#+REVEAL_INIT_SCRIPT: {menu:{themes: true, themesPath: '%sdist/themes'}}`

Is this the right way to use the `#+REVEAL_INIT_SCRIPT`?

**Comment by bzindovic** [comment]
Superb work. It works as expected.

It only seems that it not working with path expansion parameter like `#+REVEAL_EXTERNAL_PLUGIN` does with `%s`.

**Comment by yjwen** [comment]
Done. Now it supports `%s`.

**Comment by kiyohitoyoshida** [comment]
If a statement of #+REVEAL_EXTRA_INITIAL_JS contains "%", org-reveal fails  in converting into an html file with an error message such as "org-reveal-scripts: Invalid format operation %;"
The #+REVEAL_EXTRA_INITIAL_JS is
`#+REVEAL_EXTRA_INITIAL_JS: audio:{autoplay: false, prefix: 'audio/', suffix: '.ogg', textToSpeechURL: null, defaultNotes: false, defaultText: false, advance: 0, defaultDuration: 5, defaultAudios: false, playerOpacity: 0.5, playerStyle: 'position: fixed; bottom: 4px; left: 25% ; width: 50% ; height:75px; z-index: 33;', startAtFragment: false}, plugins: [ RevealAudioSlideshow ]`

**Comment by yjwen** [comment]
I see.  Let me restrict the % replacement only for the first `%s` in the initial string. Any other % will be left intact. In case of the first `%s` should be treated literal, replace it with `%%s` instead.

**Comment by kiyohitoyoshida** [comment]
It works properly!
Thanks a lot.
