### ISSUE TITLE
Insert a timeline to a org-reveal presentation?

### ISSUE THREAD

**Issue by boina** [yjwen/org-reveal#464]
Thank you for this package. It's amazing.
I would like to include a time line (I have one created with ox-timeline).
If I include the html exported code with [[~/timeline.html]] I get I link to a new html page which is not too bad but I would like to have it included in the slide itself so I don't have to open a new window. Is there any way to do this?
Jose.

**Comment by yjwen** [comment]
First, update to the latest org-reveal, as it was just enhanced for including custom script source in #465.

Then write your time line in a separate org file and export only the body to HTML. Say we have such a time line saved in `timeline.org`. Export it to `timeline.html` by pressing `C-c C-e C-b T h`. Especially, don't miss the `C-b` in the key sequence.
```org
* 200000 BC
  Some species appeared.

* 150000 BC

  It thrived.

* 100000 BC

  It vanished.
```

Finally, setup the org file to be export to reveal.js to include ox-timeline configurations and the exported timeline file by:

1. Include timeline.min.css by `#+REVEAL_EXTA_CSS` option
2. Include timeline.min.js by `#+REVEAL_EXTRA_SCRIPT_SRC` option
3. Include the exported timeline HTML by `#+INCLUDE`

Here is an example that includes the previous exported timeline for some species.
```
#+REVEAL_EXTRA_CSS: file:///home/yujie/src/timeline-master/dist/css/timeline.min.css
#+REVEAL_EXTRA_SCRIPT_SRC:  file:///home/yujie/src/timeline-master/dist/js/timeline.min.js
* Timeline
  
  #+INCLUDE: "./timeline.html" export html
```

Export it to reveal.js and here is what I got.
![Screenshot_2021-11-14_21-27-59](https://user-images.githubusercontent.com/4273142/141683266-b4ebc652-e820-40b8-84b1-1841cdb22a0f.png)

I didn't try the horizontal timeline, but it should be done by setups in exporting the timeline org file and all other steps should be the same.

Regards,
Yujie
