### ISSUE TITLE
org-reveal-export-to-html not available in emacs batch mode

### ISSUE THREAD

**Issue by spacekookie** [yjwen/org-reveal#466]
I apologise if this is a question that has been answered before. I had a look through existing issues and didn't see anything immediately relevant.

I have a function to export slide decks in a directory which boils down to this:

```elisp
(defun export-slides ()
  (load-library "reveal")
  (setq org-reveal-root "../.templates")

  (defvar slides (delete "README.org" (directory-files "." nil "\.org$" t)))
  (print slides)
  (mapcar
    (lambda (file)
      (find-file file)
      (org-reveal-export-to-html))
    slides))
```

I would like to run this function in my Gitlab CI via `emacs --batch -l <elisp file>`. This works for another org-mode export (not shown here, just using `org-html-export-to-html` but I get this error for `ox-reveal`:

```
Symbol’s function definition is void: org-reveal-export-to-html
```

Using this function without `--batch` mode works. `ox-reveal` version: `20211030.838`. Is this a bug with `ox-reveal` or am I holding it wrong? :grin:

**Comment by yjwen** [comment]
emacs in batch mode won't call the init file (.emacs), where org-reveal get loaded. Just add some code to initialize org-reveal and then it is available to work.

Here is a minimum sample script that I tried and confirmed working with my org-reveal from MELPA.

```
(defun export-slides ()
  (find-file "./tmp.org")
  (org-reveal-export-to-html))

(package-initialize)
(require 'ox-reveal)
(export-slides)
```

**Comment by spacekookie** [comment]
Oh thank you! Adding `(require 'ox-reveal)` to my function does indeed fix things :)
