### ISSUE TITLE
 Problem with org-reveal-extra-script-src

### ISSUE THREAD

**Issue by svictor9** [yjwen/org-reveal#467]
First of all, thanks for this great package! 

I've been using successfully this in my org file:
```
#+REVEAL_EXTRA_SCRIPT_SRC: file:///home/vic/ordis/src/reveal.js/victor.js
```
The extra js is correctly included. 
But it is not included when I put the setting in my init file like this:
```
(setq org-reveal-extra-script-src "file:///home/vic/ordis/src/reveal.js/victor.js")
```
In this case, I see in the html file a bunch of declarations like `<script src="105"></script>`. There are maybe 10-20 such lines, where the number after `src=` varies. There is an error for each of course in the console. No reference at all to a `victor.js` file in the html. Am I doing something wrong?

**Comment by yjwen** [comment]
`org-reveal-extra-script-src` was expecting a list of file names, in case of multiple script file. For single file case, the file name had to be put into a list as well. For example, `(setq org-reveal-extra-script-src '(file:///some/script.js))`.

I just pushed an enhancement to support the case of single file name string value. Please pull the latest.

**Comment by svictor9** [comment]
Excellent! That works just fine. Thanks!
