### ISSUE TITLE
how to change the default size of the slide?

### ISSUE THREAD

**Issue by nimble2005** [yjwen/org-reveal#468]
Sometimes the titile of my presentation is a bit long and I somehow want to keep the title in one line. I tried to adjust the slide size according to the manual as `#+reveal_width: 1200` but it seems like nothing changed? Does anyone know how to adjust the default size of the slide, or, to always keep the title in one line? THX

[title-page](https://imgtu.com/i/ovU46f)
[code-snapshot](https://imgtu.com/i/ovUh1P)

**Comment by kiyohitoyoshida** [comment]
The font size of slide titles is specified by h2 tags.  So you can adjust the font size of the h2 tag in a CSS file.  You should make a CSS file, for example extra.css, and set the font size like this.
`.reveal h2 {
        font-size: 80%;
}`
In your org file, specify the location of the css file.
`#+reveal_extra_css: extra.css`

**Comment by nimble2005** [comment]
> The font size of slide titles is specified by h2 tags. So you can adjust the font size of the h2 tag in a CSS file. You should make a CSS file, for example extra.css, and set the font size like this. `.reveal h2 { font-size: 80%; }` In your org file, specify the location of the css file. `#+reveal_extra_css: extra.css`

Hi, thanks a lot for the reply. 

Yes, so far what I have done is to change the font size through a CSS file. On the other hand, I still want to change the slide size instead. In the [Reveal.js](https://revealjs.com/presentation-size/)  site, the manual shows it can be done as

`Reveal.initialize({
  width: 960,
  height: 700,
  margin: 0.04,
  minScale: 0.2,
  maxScale: 2.0
});`

Since I am just a rookie for CSS and HTML, I just hope to know how to change the size of the slide in org-reveal.

**Comment by kiyohitoyoshida** [comment]
In ox-reveal.el, there is a statement for the initializing;
```
Note: Options and custom variables for initializing reveal.js are
obsolete. Use '#+REVEAL_INIT_OPTIONS:' instead to give JS code
snippet for initializing reveal.js. The following is a such
example:

#+REVEAL_INIT_OPTIONS: width:1200, height:800, controlsLayout: 'edges
```
You can change the slide size by setting `#+REVEAL_INIT_OPTIONS:`

**Comment by nimble2005** [comment]
Thanks a lot! @kiyohitoyoshida. It worked!!! Great!!! Terrific!!! Just what I wanted! Again, really appreciate your help!!!
