### ISSUE TITLE
 On apple mac only: Single file displays nothing

### ISSUE THREAD

**Issue by RidaAyed** [yjwen/org-reveal#471]
Mac: Safari and Chrome show only `John Doe` hence the value from `#+Author: John Doe`. Nothing else (text, images or css).

Linux: Works (Firefox)

Since the Mac is not mine I'm not sure if it's a local policy e.g. restriction on usb

**Comment by yjwen** [comment]
Could you please try Firefox on Mac? I don't have a Mac, so I never tested org-reveal on Mac and neither can I reproduce the reported error.

**Comment by yjwen** [comment]
Please check if the fix of #472 will work.

**Comment by RidaAyed** [comment]
Thank you. Updating leads to `Loading /home/ra/.emacs.d/elpa/develop/ox-reveal-20220213.1436/ox-reveal.el (source)...done
if: Cannot generate single file presentation due to file:///home/ra/bin/reveal.js/plugin/markdown/markdown.js is not readable`

**Comment by yjwen** [comment]
Forgot to remove the URL prefix... Just fixed in fed9be1. Could you please try again?
