### ISSUE TITLE
Unable to set theme

### ISSUE THREAD

**Issue by simendsjo** [yjwen/org-reveal#475]
```
#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_THEME: moon
```

But I still get
```
  <link rel="stylesheet" href="https://unpkg.com/reveal.js@^4//dist/theme/black.css" id="theme">
```

**Comment by yjwen** [comment]
Cannot reproduce with the latest org-reveal. My local tests produced the correct theme link.
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js/dist/theme/moon.css" id="theme"/>
```
The `href` you posted is different from that given by `#+REVEAL_ROOT:`. That looks strange. Could you please double confirm?

**Comment by simendsjo** [comment]
My bad, I used `org-pandoc-export-to-revealjs` and friends, but I see I have to use other export options!
