### ISSUE TITLE
multiplex confusion

### ISSUE THREAD

**Issue by Cadair** [yjwen/org-reveal#479]
Hello,

I don't know if this is a bug or my own misunderstanding of the situation but I am completely confused as to how I am supposed to get reveal 4 and multiplexing working through org-reveal.

I have a setup where in the directory with my org file containing the slides I have a `src/` directory which contains local copies of reveal and the other dependencies I need. So `./src/reveal.js` is the local path to reveal i.e. I have the following two config options set:

```
#+REVEAL_ROOT: ./src/reveal.js/
#+REVEAL_MATHJAX_URL: ./src/mathjax/es5/tex-chtml.js
```

I tried following the instructions on the [multiplex plugin](https://github.com/reveal/multiplex#getting-started) page to install the plugin and then adding the config options to org-reveal as described in the readme, but no matter how I try and do this I still get `Uncaught ReferenceError: multiplex is not defined` in the console after I have added the `multiplex` plugin to `#+REVEAL_PLUGINS`.

From looking at the docs for the plugin, I am not sure if multiplex is supposed to be in the plugins list in the generated HTML any more?

Thanks in advance for any help.

**Comment by yjwen** [comment]
Which one was generating the error `Uncaught ReferenceError: multiplex is not defined`? Browser or Emacs?

**Comment by Cadair** [comment]
It was in the browser console.

**Comment by yjwen** [comment]
Possibly a reveal.js setup issue. Could you please share a minimum .org and the generated .html that can reproduce the issue?

**Comment by Cadair** [comment]
This repo contains the minimal setup: https://github.com/Cadair/reveal-org-multiplex-test

The specific issue is that multiplex is in this line: https://github.com/Cadair/reveal-org-multiplex-test/blob/main/talk.html#L50, if I remove that then it works as expected.

Thanks a lot.

**Comment by yjwen** [comment]
It is a bug in ox-reveal that `multiplex` is added to the `plugins` list. It was not necessary any more since reveal.js 4. Just removed. Please pull and try.

**Comment by Cadair** [comment]
That appears to have worked, thanks!

**Comment by Cadair** [comment]
Ah, it seems that it's now always in multiplex mode, generating the `_client.html` and putting an empty multiplex config in the html even when `multiplex` isn't in the plugins list.

**Comment by yjwen** [comment]
My fault. Fixed again.

**Comment by Cadair** [comment]
Seems to be working now :smile: 

Thanks a lot for your help!
