### ISSUE TITLE
feature request: REVEAL_PROLOGUE_HTML REVEAL_EPILOGUE_HTML

### ISSUE THREAD

**Issue by rytis-paskauskas** [yjwen/org-reveal#481]
I'd like to request a feature for inserting arbitrary html code block between the `<div class="reveal">` and `<div class="slides">` tags (optionally also in the location between the corresponding closing divs).

Currently, to insert a custom html code block into the reveal's `body > reveal > slides > section [> section], ...` hierarchy, the following options (that I know of) are available:

`REVEAL_PREAMBLE : CODE` inserts code between body and reveal, the result being `<body> CODE <div class='reveal'>`
`REVEAL_HTML: CODE` inserts code at the section level, anywhere after the title section.
`REVEAL_POSTAMBLE: CODE` inserts code just before the script, hence the body closing.

Schematically, it looks like this:
```html
<body> 
  PREAMBLE_CODE 
  <div reveal> 
    <div slides> 
      <section 'title'>...</section>
      [<section></section>] 
      HTML_CODE 
      [<section></section>] 
    </div><!-- slides -->
  </div><!-- reveal -->
  POSTAMBLE_CODE  
  <script></script>
</body>
```

The space between the opening `<reveal>` and `<slides>`, as well as their closing counterparts remains inaccessible (and it so happens that I need to access it). 

I've called this feature `PROLOGUE`/ `EPILOGUE` to stay in theme with the existing `PRE/POST-AMBLE` options although any other name would do just fine!

Please let me know if that is something that can be done, or whether it is already possible and I overlooked it.

Thank you very much in advance.

**Comment by yjwen** [comment]
Done as requested. Please pull the latest.

**Comment by rytis-paskauskas** [comment]
works as expected. Many thanks!
