### ISSUE TITLE
How to tell org-reveal to use latex package

### ISSUE THREAD

**Issue by FryeKai** [yjwen/org-reveal#482]
Hi,
I need to use a latex package. It works, when I export the org file as a latex.
But how to tell org-reveal to use the package as well?

Cheers,
Kai

**Comment by yjwen** [comment]
I am afraid there is no way to include a latex package, as org-reveal is an HTML backend. What is necessary of a latex package for exporting reveal.js slides?

**Comment by FryeKai** [comment]
> I am afraid there is no way to include a latex package, as org-reveal is an HTML backend. What is necessary of a latex package for exporting reveal.js slides?

For a talk, I need to use the quantum mechanics "braket" notation, which is accessible by 
\usepacke{braket}

Sadly, this does not compile in org-reveal

**Comment by FryeKai** [comment]
@kir0ul Thanks for the advice. I suppose that this is a nice workaround. But I am really struggling to get MathJax running with org-reveal properly.
I think it's load using REVEAL_MATHJAX_URL but no idea how to modify it.

**Comment by yjwen** [comment]
Here is an example.
```
#+REVEAL_MATHJAX_URL: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

* Example Slide
$\braket{1 \over w}$

```
