### ISSUE TITLE
Some way to include custom JS

### ISSUE THREAD

**Issue by VladimirAlexiev** [yjwen/org-reveal#58]
org-reveal-extra-js allows one to specify a file of custom JS. However, then I need to bother with distributing this file.
There should be some option to include custom JS in the exported HTML. Eg this doesn't work: 
```lisp
  (setq org-reveal-postamble "<script>Reveal.configure({...})</script>")
```
because the code is added *before* invoking reveal.js, so the Reveal object is not yet available.

**Comment by yjwen** [comment]
Hi,

  I have implemented embedding pictures and CSS into the exported HTML. But I have no idea how to embed the JS plug-ins. Say, if there is 
```
<script>
// Full list of configuration options available here:
// https://github.com/hakimel/reveal.js#configuration
Reveal.initialize({
dependencies: [
 { src: 'file:///d:/src/reveal.js/lib/js/classList.js', condition: function() { return !document.body.classList; } },
]
});
</script>
```
What is the correct form to embedding the text of classList.js into the HTML?

Regards,
Yujie

**Comment by VladimirAlexiev** [comment]
I don't know what is in classList.js. 
I'm only asking for some emacs variable so I can embed raw JS code in the call to Reveal.initialize, and not only dependencies.

**Comment by yjwen** [comment]
Code updated.

Custom JS to reveal.initialize can be stated by `#+REVEAL_INIT_SCRIPT` and multiple statements are concatenated, or by custom variable `org-reveal-init-script`.

Please pull the latest master branch.
