### ISSUE TITLE
REVEAL_EXTRA_JS should be a list of files/URLs

### ISSUE THREAD

**Issue by VladimirAlexiev** [yjwen/org-reveal#59]
REVEAL_EXTRA_JS should be a list of files/URLs, so that I can specify eg
```
#+REVEAL_EXTRA_JS: js/reveal-help.js js/reveal-tagcloud.js
```
Or do it on two lines, eg
```
#+REVEAL_EXTRA_JS: js/reveal-help.js
#+REVEAL_EXTRA_JS: js/reveal-tagcloud.js
```

Right now I have to specify this ugliness, and it only takes one file
```
#+REVEAL_EXTRA_JS: {src: 'js/reveal-help.js', async: true, condition: function() {return !!document.body.classList}}
```

**Comment by psifertex** [comment]
I'm loading some extra libraries to do graphing and that required specifying the callback function so for me it was easier to do `#+REVEAL_EXTRA_JS: { src: './js/Chart.min.js', async: true , callback: function() { Chart.renderChart(); } }, { src: './js/Chart.StackedBar.js', async: true }`. Figured I'd drop that here in case anyone else is trying to do something similar.

**Comment by gongzhitaao** [comment]
Is it good to have `REVEAL_EXTRA_JS` accept the same arguments as `HTML_HEAD_EXTRA`?  Or actually rename it as `REVEAL_HEAD_EXTRA`?

**Comment by VladimirAlexiev** [comment]
@psifertex: imho the best is to elaborate the defcustom to include for each value a string field `callback` (eg `Chart.renderChart()`) and a boolean field `async`.  Breaking the info into fields makes it easier for a user to fill out correctly.

@gongzhitaao HTML_HEAD_EXTRA is not appropriate since it's merely lines to be added to the `<HEAD>`

**Comment by yjwen** [comment]
Since there are possibly different requirements for the format of JS script format, I'd like to leave `REVEAL_EXTRA_JS` as it is now, where one can write whatever JS code, ugly though.

Let me close the issue for now.
