### ISSUE TITLE
Paragraph alignment affects image alignment.

### ISSUE THREAD

**Issue by talexand** [yjwen/org-reveal#70]
Setting `p { text-align: left; }` in CSS causes images to be aligned left, as they are contained in `p` blocks. This doesn't make sense semantically--images aren't text.

**Comment by yjwen** [comment]
I am afraid the images are always wrapped by `<p>`. The HTML exporter recognize bare links to image file as a inclusion of images other than a link to an image. The `<img>` tag is always wrapped by `<p>`.

The walk-around to your issue should be using CSS to correct alignment for images.

And sorry for such a late reply....

Regards,
Yujie
