### ISSUE TITLE
Enhancement to add slide notes easy template to org-structure-template-alist for <n

### ISSUE THREAD

**Issue by mlt** [yjwen/org-reveal#72]
Just an enhancement idea to add an entry to `'org-structure-template-alist` alist so one may type `<n` followed by TAB key to get begin/end block for slide notes. Perhaps the following will do it
`(add-to-list 'org-structure-template-alist '("n" "#+BEGIN_NOTES\n?\n#+END_NOTES" ""))`

**Comment by yjwen** [comment]
Just update the master branch to add easy-template for speaker notes.
Please find the detail documents [here](https://github.com/yjwen/org-reveal#easy-template-for-speaker-notes)

Regards,
Yujie
