### ISSUE TITLE
presentation is mispositioned when jumping from TOC

### ISSUE THREAD

**Issue by VladimirAlexiev** [yjwen/org-reveal#79]
org-reveal makes TOC links like this (no slash after the #). 

- http://VladimirAlexiev.github.io/Multisensor/20141008-Linguistic-LD/index.html#sec-2-7

The presentation is slightly mispositioned, go prev/next slide to see that the top of slides is hidden. In contrast, when Reveal.configure{history:true}) is set, the links that reveal makes include a slash after the # :

- http://VladimirAlexiev.github.io/Multisensor/20141008-Linguistic-LD/index.html#/sec-2-7

and everything works ok.

So you need to make TOC links with #/ not just # . (This is different from #51)

**Comment by yjwen** [comment]
Thanks for the suggestion. I've also experienced the mispositioned issue. No the code is updated as you suggested.
