### ISSUE TITLE
org-reveal-toc should put an id to the TOC section

### ISSUE THREAD

**Issue by VladimirAlexiev** [yjwen/org-reveal#80]
org-reveal-toc should put an id to the TOC section so I can control its style.

    (defun org-reveal-toc (depth info)
      "Build a slide of table of contents."
      (let ((headlines (org-export-collect-headlines info depth)))
        (and headlines
             (format "<section id=\"table-of-contents\">\n%s</section>\n" ;; added id (same as in ox-html) so I can control style
                 (org-reveal-toc-headlines headlines info)))))

**Comment by yjwen** [comment]
Have updated as you suggested. Thanks and sorry for such a late patch.
