### ISSUE TITLE
How can i customize an imported image size ?

### ISSUE THREAD

**Issue by wxjeacen** [yjwen/org-reveal#89]
I just can not change the size of imported images.

**Comment by yjwen** [comment]
Hi, 

  Sorry for a late reply.

  Since org-reveal is derived from ox-html,  you can use `#+ATTR_HTML` to specify html attributes to images. To change the image size, 

    #+ATTR_HTML: :width 50% :height 50%
    [[file:./sample.jpg]]

  will shrink the image width and height to half. Absolute values can be also recognized.

**Comment by wxjeacen** [comment]
Thanks for a great deal.
