### ISSUE TITLE
Not working with Org-mode version 8.2.10

### ISSUE THREAD

**Issue by pedroteixeira** [yjwen/org-reveal#93]
It fails with the following message:
or: Export failed. It seems you are using a stable release of Org-mode. Please use Org-reveal `stable' branch for Org-mode stable releases.

any help?

**Comment by yjwen** [comment]
Please `git pull origin stable`. There is inconsistent API between the development version (from git) and the released version of Org-mode. So org-reveal has two branches to match different APIs. master -> git Org-mode, and stable -> released Org-mode.

There is also a MELPA package of org-reveal's stable branch that is ready to use.
