### ISSUE TITLE
Multi-line HTML

### ISSUE THREAD

**Issue by marcbowes** [yjwen/org-reveal#96]
I'd like to be able to pass a block of HTML through.

`#+REVEAL_HTML: <span>Hello</span>` works well for one line, but I'm not sure how to get this working for multiple lines (other just just repeating the keyword for each line).

For example, I'm looking for something like this:

```
#+BEGIN_HTML
<div class="foo">
Hello
</div>
#+END_HTML
```

**Comment by yjwen** [comment]
OK, let me add support for `#+BEGIN_HTML`, as the HTML exporter does.

**Comment by marcbowes** [comment]
Thank you!

**Comment by yjwen** [comment]
Hi,

  There is support for `#+BEGIN_HTML` tags in org-reveal already. You can add the contents as for the HTML exporter.

  I will update Readme.org to make it clear.

Regards,
Yujie

**Comment by marcbowes** [comment]
Thanks, that worked for me!

**Comment by mister-walter** [comment]
If anyone comes across this now and is confused by `#+BEGIN_HTML` not working, use `#+BEGIN_EXPORT html` instead. org-reveal just passes this on to ox-html, which handles it correctly.
