### ISSUE TITLE
org-reveal produces only one long slide

### ISSUE THREAD

**Issue by brittAnderson** [yjwen/org-reveal#99]
Org-reveal is only producing one long slide, it does not break the slides at the proper header and there are no controls. I know that the reveal files are being accessed because the CSS is used to produce the html.

This problem is true for the Readme file as well as my own files. It is also true for a native reveal.js. If I open the introduction to reveal that works fine. If I use pandoc to convert to md, and back to html, and then use reveal the same problem occurs. 

I wonder if this could be due to some problem with line break new line characters, but I am not sure how to debug further. Please let me know what tests you might suggest I try. 

Thank you.

**Comment by yjwen** [comment]
Hi,

  By my understanding, you are generating HTML by converting org-mode file
to md, and then to HTML. I am afraid the flow won't work because some
structural information may be lost during the conversion.

  Is there any problem when using org-reveal to export Org-mode contents to
HTML directly?

Regards,
Yujie

2015-03-03 21:43 GMT+08:00 brittAnderson <notifications@github.com>:

**Comment by brittAnderson** [comment]
No. That was just a test to see if I could identify what was broken.

Here is a test.org file, and the test.html file generated. I never get
any slide breaks or controls no matter how I fiddled with the Header
level option or other commands. But I can see a proper functioning
version if I just open up the index.html that comes with the
installation of reveal.js-master

test.org:

#+Title: Does Attention alter Appearance (and other stuff)
#+Author: Britt Anderson, PhD & MD
#+Date: Feb 26, 2015
#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:nil reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+OPTIONS: toc:t
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: fade
#+REVEAL_THEME: moon
#+REVEAL_HLEVEL: 1
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal Introduction.">
#+REVEAL_POSTAMBLE: <p> Created for UWloo Neuroscience UG Group. </p>
#+REVEAL_PLUGINS: (highlight markdown)

* This is heading one

** This is subheading one

* This is heading two
#+ATTR_REVEAL: :frag grow 
- item 1
- item 2
- item 3


** and a second 

*** And a third


test.html:


<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Does Attention alter Appearance (and other stuff)</title>
<meta name="author" content="(Britt Anderson, PhD & MD)"/>

<link rel="stylesheet" href="./css/reveal.min.css"/>
<link rel="stylesheet" href="./css/theme/moon.css" id="theme"/>


<script>
    if( window.location.search.match( /print-pdf/gi ) ) {
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = './css/print/pdf.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    }
</script>
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<meta name="description" content="Org-Reveal Introduction.">
</head>
<body>
<div class="reveal">
<div class="slides">
<section>
<h1>Does Attention alter Appearance (and other stuff)</h1>
<h2>Britt Anderson, PhD &amp; MD</h2>
<h2><a href="mailto:britt@uwaterloo.ca">britt@uwaterloo.ca</a></h2>
<h2>Feb 26, 2015</h2></section>
<section>
<h2>Table of Contents</h2><ul>
<li>
<a href="#sec-">This is heading one</a>
<ul>
<li>
<a href="#sec-">This is subheading one</a>
</li>
</ul>
<li>
<a href="#sec-">This is heading two</a>
<ul>
<li>
<a href="#sec-">and a second</a>
<ul>
<li>
<a href="#sec-">And a third</a>
</li>
</ul>
</section>

<section>
<section id="sec-" >

<h2>This is heading one</h2>
</section>
<section id="sec-" >

<h2>This is subheading one</h2>
</section>

</section>
<section>
<section id="sec-" >

<h2>This is heading two</h2>
<ul class="org-ul">
<li class="fragment grow">item 1
</li>
<li class="fragment grow">item 2
</li>
<li class="fragment grow">item 2
</li>
</ul>


</section>
<section id="sec-" >

<h2>and a second</h2>
</section>
<section id="sec-" >

<h4>And a third</h4>
</section>
</section>
</div>
</div>
<p> Created for UWloo Neuroscience UG Group. </p>

<script src="./lib/js/head.min.js"></script>
<script src="./js/reveal.min.js"></script>

<script>
// Full list of configuration options available here:
// https://github.com/hakimel/reveal.js#configuration
Reveal.initialize({

controls: true,
progress: true,
history: false,
center: true,
slideNumber: true,
rollingLinks: true,
keyboard: true,
overview: true,
width: 1200,
height: 800,
margin: 0.10,
minScale: 0.50,
maxScale: 2.50,

theme: 'moon' 
transition: 'slide' 
transitionSpeed: 'default'

// Optional libraries used to extend on reveal.js
dependencies: [
 { src: './plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },
 { src: './plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
 { src: './plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } }
]
});
</script>
</body>
</html>
On 03.03, Yujie Wen wrote:
> Hi,
> 
> By my understanding, you are generating HTML by converting org-mode file
> to md, and then to HTML. I am afraid the flow won't work because some
> structural information may be lost during the conversion.
> 
> Is there any problem when using org-reveal to export Org-mode contents to
> HTML directly?
> 
> Regards,
> Yujie
> 
> 2015-03-03 21:43 GMT+08:00 brittAnderson <notifications@github.com>:
> 
> > Org-reveal is only producing one long slide, it does not break the slides
> > at the proper header and there are no controls. I know that the reveal
> > files are being accessed because the CSS is used to produce the html.
> >
> > This problem is true for the Readme file as well as my own files. It is
> > also true for a native reveal.js. If I open the introduction to reveal that
> > works fine. If I use pandoc to convert to md, and back to html, and then
> > use reveal the same problem occurs.
> >
> > I wonder if this could be due to some problem with line break new line
> > characters, but I am not sure how to debug further. Please let me know what
> > tests you might suggest I try.
> >
> > Thank you.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/yjwen/org-reveal/issues/99>.
> >
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
Britt Anderson, PhD & MD
Psychology & Centre Theoretical Neuroscience
University of Waterloo
CANADA
tel: 519.888.4567 x 33056

**Comment by yjwen** [comment]
Hi,

  I just tried with the test.org and there are slides for each headings. And there is nothing wrong with the generated HTML that you pasted.

  Let me confirm one possible reason. Are you using Firefox or Chrome? IE based browsers don't support HTML5 standard quite well. It is suggested to use Firefox/Chrome to show the slides.

Regards,
Yujie

**Comment by brittAnderson** [comment]
I am using Firefox version 35.0.1. In this browser the index.html that comes with reveal.js opens and displays properly, but the test.html does not. I am not saying the problem is with org-reveal per se, just that I cannot get org-reveal to work on my machine, and am not able to determine the location of the problem. 
On Tue, 10 Mar 2015 04:51:21 -0400,
Yujie Wen wrote:

**Comment by yjwen** [comment]
I saw the reveal.js paths in test.html are relative ones, like:

     <link rel="stylesheet" href="./css/reveal.min.css"/> <link rel="stylesheet" href="./css/theme/moon.css" id="theme"/>

Then could you please try to place the test.html into reveal.js's root director (same as index.html that come with the reveal.js release) and open it there.

Please also refer to https://github.com/yjwen/org-reveal/#set-the-location-of-revealjs for details about let org-reveal to know where your reveal.js is.

**Comment by brittAnderson** [comment]
The problem is that reveal.min.js does not exist. When I manually edit
the html file to refer to reveal.js everything works. I see that you
refer to this explicitly in ox-reveal.el, but when I download
reveal.js-master there is no reveal.min.js file in the js directory.
That seems to be the problem.

Maybe it is something weird with my installation, but the fact that the
C-c C-e R R command is generating html referring to the missing js file
is the problem.

Cheers,
Britt

On 10.03, Yujie Wen wrote:
> I saw the reveal.js paths in test.html are relative ones, like:
> 
>  <link rel="stylesheet" href="./css/reveal.min.css"/> <link rel="stylesheet" href="./css/theme/moon.css" id="theme"/>
> 
> Then could you please try to place the test.html into reveal.js's root director
> (same as index.html that come with the reveal.js release) and open it there.
> 
> Please also refer to https://github.com/yjwen/org-reveal/#
> set-the-location-of-revealjs for details about let org-reveal to know where
> your reveal.js is.
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
Britt Anderson, PhD & MD
Psychology & Centre Theoretical Neuroscience
University of Waterloo
CANADA
tel: 519.888.4567 x 33056

**Comment by yjwen** [comment]
OK, I see!
It is because reveal.js has renamed reveal.min.js to reveal.js recently. Org-reveal has been also updated to follow the file name changes. If your org-reveal is from github, please simply pull the latest.
MELPA's ox-reveal should also have been updated, but I am not sure.

Regards,
Yujie
